window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["CVS"] = [
  { "d":1, "prompt":"You enter. Staff greets you. Respond.", "answers":["Annyeonghaseyo!", "Annyeong hashimnikka!", "Annyeong!"], "translations":["Hello! (peace-doing-are-you?)", "Hello! (formal)", "Hi! (casual)"], "notes":"Korean convenience stores (편의점, Pyeonuijeom) — CU, GS25, 7-Eleven, Emart24 — are everywhere and open 24/7. Staff greeting is standard. Responding with Annyeonghaseyo is polite. Korean CVS culture is extraordinary — they're more like miniature supermarkets with hot food, cooking stations, and seating areas." },
  { "d":1, "prompt":"Pay by card.", "answers":["Kadeu-ro halkgeyo", "Kadeu-ro gyesan hagetseumnida", "Kadeu-ro hae"], "translations":["Card-by will-do-polite (I'll pay by card)", "Card-by pay will-formal", "Card-by do (casual)"], "notes":"카드 (Kadeu) = card. Korean CVS is extremely cashless — tap pay, Samsung Pay, and Kakao Pay are all accepted. 포인트 적립 하실 건가요? (Points earn will-you-do? — 'will you earn points?') is a common follow-up question from staff." },
  { "d":1, "prompt":"Staff asks if you need a bag. Say yes.", "answers":["Ne, juseyo", "Ne, butakhabnida", "Eung, jwo"], "translations":["Yes, give-please", "Yes, I-request-formal", "Yeah, give (casual)"], "notes":"봉투 (Bongtu) = plastic bag. 비닐봉투 (Binilbongtu) = vinyl/plastic bag. Korean CVS chains charge a small fee (₩20–50) per bag as an environmental measure. 종이봉투 (Jongi bongtu) = paper bag (also available). Bringing your own bag (에코백, Ekobek) is becoming more common." },
  { "d":1, "prompt":"Staff asks if you need a bag. Say no.", "answers":["Gwaenchana-yo, isseoyo", "Gwaenchanseumnida, itseumnida", "Gwaenchana, isseo"], "translations":["It's fine, I have one-polite", "It's fine-formal, I have one-formal", "Fine, I have one (casual)"], "notes":"괜찮아요 (Gwaenchanayo) = it's fine/no need. 가방에 넣을게요 (Gabange neuteulgeyo — 'I'll put it in my bag') makes your intention clear. 필요 없어요 (Piryo eopseoyo — 'I don't need one') is also natural." },
  { "d":1, "prompt":"Ask where the snacks / ramyeon are.", "answers":["Ramyeon eodisseoyo?", "Ramyeon-i eodiissseumnikka?", "Ramyeon eodisseo?"], "translations":["Ramen where-is-polite?", "Ramen-topic where-is-formal?", "Ramen where? (casual)"], "notes":"라면 (Ramyeon) = instant noodles — Korean CVS has an enormous selection. 컵라면 (Keop ramyeon) = cup noodles. 과자 (Gwaja) = snacks/chips. 편의점 라면 (CVS ramen) culture is massive in Korea — many have hot water dispensers and seating specifically for eating ramen on the spot." },
  { "d":1, "prompt":"Ask for a receipt.", "answers":["Yeongsujung juseyo", "Yeongsujung butakhabnida", "Yeongsujung jwo"], "translations":["Receipt give-please", "Receipt I-request-formal", "Receipt give (casual)"], "notes":"영수증 (Yeongsujung) = receipt. Korean CVS receipts include loyalty points information. 멤버십 있으세요? (Membership isseuseyo? — 'do you have membership?') is a common follow-up. CU, GS25, and 7-Eleven all have their own app-based loyalty programs with good discounts." },
  { "d":2, "prompt":"Ask if they can microwave your food.", "answers":["I geo deri-wo juseyo", "I siksik-pum-eul geolli juseyo", "I geo deriwo jwo"], "translations":["This one heat-up give-please (please heat this up)", "This food-obj microwave give-please (formal)", "This one heat give (casual)"], "notes":"데워 주세요 (Deriwo juseyo) = please heat it up. 전자레인지 (Jeonja-reinji) = microwave. Korean CVS microwaves are self-serve at most locations — staff will point you to it. 몇 분이요? (Myeot buniyo? — 'how many minutes?') they might ask." },
  { "d":2, "prompt":"Ask for chopsticks and a spoon.", "answers":["Jeotgarak-gwa sujeo juseyo", "Jeotgarak-gwa sujeo butakhabnida", "Jeotgarak-gwa sujeo jwo"], "translations":["Chopsticks-and spoon give-please", "Chopsticks-and spoon I-request-formal", "Chopsticks-and spoon give (casual)"], "notes":"젓가락 (Jeotgarak) = chopsticks. 숟가락 (Sutkarak) = spoon. 포크 (Pokeu) = fork. These are available at the counter — just ask. Korean CVS staff will hand you a kit with chopsticks, spoon, and napkins. 앞치마 (Apchima = apron) available at some stores too." },
  { "d":2, "prompt":"Ask for hot water.", "answers":["Tteugeoun mul juseyo", "Tteugeoun mul-eul jushigesseumnikka?", "Tteugeoun mul jwo"], "translations":["Hot water give-please", "Hot water could-give-formal?", "Hot water give (casual)"], "notes":"뜨거운 물 (Tteugeoun mul) = hot water. Korean CVS usually has a hot water dispenser (온수기, Onsugyi) for cup noodles — it's often self-serve near the hot food area. 온수기 어디 있어요? (Onsugyi eodi isseoyo? — 'where is the hot water machine?') if you can't find it." },
  { "d":2, "prompt":"Ask if they sell painkillers.", "answers":["Dutongyak isseoyo?", "Dutongyak-i itsseumnikka?", "Dutongyak isseo?"], "translations":["Painkiller exist-polite?", "Painkiller-topic exist-formal?", "Painkiller exist? (casual)"], "notes":"두통약 (Dutongyak) = headache medicine. 타이레놀 (Tairenyol — Tylenol) and 게보린 (Geborin) are common OTC painkillers at Korean CVS. 소화제 (Sohwaje) = digestive medicine, 감기약 (Gamgiyak) = cold medicine. Korean CVS sell a wide range of OTC medications — very convenient." },
  { "d":2, "prompt":"Ask what time they close.", "answers":["Myeot si-e dalayo?", "Yeongip-i eonje kkeutnaemnikka?", "Myeot si-e dara?"], "translations":["What time-at close-polite?", "Business-topic when end-formal?", "What time close? (casual)"], "notes":"24시 편의점 (Isipsa si pyeonuijeom) = 24-hour convenience store — most Korean CVS in cities never close! 닫다 (Datda) = to close. You'll rarely need to ask this in Korea — urban CVS are almost always open. Rural or small-town CVS may have limited hours." },
  { "d":2, "prompt":"Ask for change / smaller bills.", "answers":["Geo-seureum juseyo", "Geo-seureum-eul butakhabnida", "Geo-seureum jwo"], "translations":["Change give-please", "Change I-request-formal", "Change give (casual)"], "notes":"거스름돈 (Geo-seureum-don) = change (money back). 잔돈 (Jandon) = small change/coins. CVS staff are used to making change. It's polite to have smaller bills when possible. Cashless payment is so common that some CVS have very little cash on hand." },
  { "d":3, "prompt":"Ask if they sell phone chargers.", "answers":["Haedeupeuon chungeonji isseoyo?", "Huedeupone chungeonji itsseumnikka?", "Huedeupone chungeonji isseo?"], "translations":["Cell-phone charger exist-polite?", "Cell-phone charger-topic exist-formal?", "Cell-phone charger exist? (casual)"], "notes":"휴대폰 충전기 (Huedeupone chungeonji) = phone charger. 케이블 (Keibel) = cable. USB-C, Lightning, and Micro-USB cables are usually stocked. Korean CVS are great for emergency electronics purchases. 보조배터리 (Bojo baeteori) = portable battery/power bank — also commonly sold." },
  { "d":3, "prompt":"Ask where you can sit and eat inside.", "answers":["Anja meogeureo do doeyeyo?", "Sik-sa gong-ga-ni eodiisseoyo?", "Anja meogeo-do dweyo?"], "translations":["Sit eat-to also okay-polite?", "Dining space-topic where-is-polite?", "Sit eat-also okay? (casual)"], "notes":"Korean CVS usually have a small seating area (식사 공간, Siksagong-gan or just 테이블, Teibeul). 이 자리 써도 돼요? (I jari sseodo dwaeyo? — 'can I use this seat?') is polite if others are around. CVS seating culture in Korea is very relaxed — staying a while is totally normal." },
  { "d":3, "prompt":"Ask if they have a different flavor.", "answers":["Dareun mat isseoyo?", "Dareun mat-i itsseumnikka?", "Dareun mat isseo?"], "translations":["Different flavor exist-polite?", "Different flavor-topic exist-formal?", "Different flavor exist? (casual)"], "notes":"맛 (Mat) = flavor/taste. Korean CVS snacks come in extraordinary variety — 허니버터 (Honey butter), 불닭 (Fire chicken), 짜파게티 (Jjapaghetti), 새우깡 (Prawn crackers). 이것 말고 다른 것 있어요? (This-one besides different-thing exist? — 'anything other than this one?') is a full sentence version." },
  { "d":3, "prompt":"You want to return an item.", "answers":["I geo banpum hae juseyo", "I sanshin-pum banpum butakhabnida", "I geo banpum hae jwo"], "translations":["This one return do give-please", "This purchased-item return I-request-formal", "This one return do (casual)"], "notes":"반품 (Banpum) = return/refund. 영수증 있어요? (Yeongsujung isseoyo? — 'do you have a receipt?') is what staff will ask first. CVS return policies vary — most accept returns within the same day or 24 hours for unopened items. Food items generally can't be returned once opened." },
  { "d":4, "prompt":"Cashier asks about a loyalty card. Say you don't have one.", "answers":["Melbeosip eopseoyo", "Membeoship-i eopsseumnida", "Melbeosip eopseo"], "translations":["Membership not-exist-polite (I don't have a membership)", "Membership-topic not-exist-formal", "Membership not-exist (casual)"], "notes":"멤버십 (Melbeosip) = membership/loyalty card. CU에서 하나 만드시겠어요? (Would you like to make one at CU?) — Korean CVS will often offer to create a membership on the spot via their app. CU, GS25, and 7-Eleven each have their own points programs with real discounts worth signing up for." },
  { "d":4, "prompt":"Say just these please at checkout.", "answers":["I geo-man-ieyo", "I geot-deul-man butakhabnida", "I geo-man-iya"], "translations":["This one-only-is-polite (it's just this/these)", "These ones-only I-request-formal", "This one-only (casual)"], "notes":"이것만 (I geot-man) = just this/only this. 다 됐어요 (Da dwaesseoyo — 'that's all') is equally natural at checkout. 이게 다예요 (Ige da-yeyo — 'this is everything') works well too. Short and clear expressions are best at a busy CVS counter." }
];
