window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["directions"] = [
  { "d":1, "prompt":"Say I'm lost.", "answers":["Gil-eul ireosseoyo", "Gil-eul ireossseumnida", "Gil ireosseo"], "translations":["Road-obj lost-polite (I lost my way)", "Road-obj lost-formal", "Road lost (casual)"], "notes":"길을 잃었어요 (Gil-eul ireosseoyo) = 'I lost my way.' 여기가 어디예요? (Yeogiga eodiyeyo? — 'where is this?') or 제가 어디 있어요? (Jega eodi isseoyo? — 'where am I?') are natural follow-ups. Koreans are very helpful with directions — don't hesitate to ask anyone." },
  { "d":1, "prompt":"Ask where the subway / train station is.", "answers":["Jihacheol yeok-i eodiyeyo?", "Jihacheol yeok-i eodiissseumnikka?", "Jihacheol yeok eodi isseo?"], "translations":["Subway station-topic where-is-polite?", "Subway station-topic where-is-formal?", "Subway station where is? (casual)"], "notes":"지하철 (Jihacheol) = subway. 역 (Yeok) = station. Seoul's subway system (서울 지하철) is world-class — 9 lines covering the entire city. Lines are color-coded and fully signposted in Korean, English, Chinese, and Japanese. 기차역 (Gichayeok) = train station for KTX/intercity trains." },
  { "d":1, "prompt":"Ask is it far?", "answers":["Meoleo yo?", "Meoriseumnikka?", "Meoleo?"], "translations":["Far-polite? (is it far?)", "Far-formal?", "Far? (casual)"], "notes":"멀다 (Meolda) = far. 가까워요? (Gakkaweoyo? — 'is it close?') is the opposite. Koreans' sense of distance can vary — always ask 걸어서 몇 분이에요? (Georeoseo myeot bunieyeo? — 'how many minutes walking?') to get a more useful answer than just 'far' or 'close.'" },
  { "d":1, "prompt":"Ask can I walk there?", "answers":["Georeoseo galsu isseoyo?", "Do-boroyo galsu itsseumnikka?", "Georeoseo gal su isseo?"], "translations":["Walking-by can-go-polite? (can I walk there?)", "On-foot-by can-go-formal?", "Walking-by can go? (casual)"], "notes":"걸어서 (Georeoseo) = on foot/walking. 도보로 (Doboro) = by foot (more formal). 가까우면 걸어갈게요 (Gakkauwomyeon georeogalgeyo — 'if it's close I'll walk') shows your intent. Seoul is a very walkable city in many neighborhoods." },
  { "d":1, "prompt":"Say thank you after someone gives you directions.", "answers":["Gamsahaeyo, deobu-ne chatasseoyo!", "Gamsahamnida, alryeo juseoseo!", "Gomawoyo, deobu-ne chatasseoyo!"], "translations":["Thank-you, thanks-to-you found-polite! (thank you, I found it thanks to you!)", "Thank-you-formal, informed-give-because!", "Thank-you, thanks-to-you found! (casual)"], "notes":"덕분에 (Deokbune — 'thanks to you') is the warm Korean phrase for gratitude towards someone's specific help. 알려 주셔서 감사해요 (Alryeo jushyeoseo gamsahayo — 'thank you for telling me') specifically thanks the act of explaining. Korean strangers often go far beyond just pointing." },
  { "d":2, "prompt":"Ask how long it takes on foot.", "answers":["Georeoseo eolmana geollyeyo?", "Do-boro eolmana soyo-doesimnikka?", "Georeoseo eolma geollyeo?"], "translations":["Walking-by how-long will-take-polite?", "On-foot how-long require-formal?", "Walking-by how-long takes? (casual)"], "notes":"걸어서 몇 분이에요? (Georeoseo myeot bunieyeo? — 'how many minutes walking?') is very precise and practical. Koreans often underestimate walking times — mentally add 5 minutes to whatever they say. Naver Maps walking mode is excellent for Korean streets." },
  { "d":2, "prompt":"Ask if there's a bus stop nearby.", "answers":["Geundeo-e beoseu jeong-ryujang isseoyo?", "Geundeo-e beoseu jeong-ryu-ga itsseumnikka?", "Geundeo-e beoseu jeong-ryu isseo?"], "translations":["Nearby-at bus stop exist-polite?", "Nearby-at bus stop-topic exist-formal?", "Nearby-at bus stop exist? (casual)"], "notes":"버스 정류장 (Beoseu jeong-ryujang) = bus stop. 지하철역 (Jihacheol yeok) = subway station. Korean public transit apps: Kakao Map (카카오맵), Naver Map (네이버 지도), and T Map all show real-time bus arrivals. Seoul's public transit is extremely efficient and affordable." },
  { "d":2, "prompt":"You didn't understand the directions. Ask to repeat.", "answers":["Dasi hanbeon malhae juseyo", "Dasi hanbeon malsseum hae jushipsio", "Dasi hanbeon malhae jwo"], "translations":["Again once-more speak give-please", "Again once speech give-please-formal", "Again once speak give (casual)"], "notes":"다시 한번 (Dasi hanbeon) = once more/again. 조금만 더 천천히요 (Jogeumman deo cheoncheonhiyo — 'just a little more slowly please') is a gentle follow-up. Koreans giving directions often won't mind repeating — in fact many will walk you partway to make sure you understand correctly." },
  { "d":2, "prompt":"Say I'll use my phone's map.", "answers":["Huedeupone ji-do ssalkgeyo", "Huedeupone ji-do-reul sawong hagetseumnida", "Huedeupone ji-do ssalkge"], "translations":["Phone map will-use-polite (I'll use my phone map)", "Phone map-obj use will-formal", "Phone map will-use (casual)"], "notes":"지도 (Ji-do) = map. 네이버 지도 (Naeibeo ji-do — Naver Map) is the best app for Korean navigation — more accurate and detailed than Google Maps for Korea. 카카오맵 (KakaoMap) is also excellent, especially for public transit and real-time traffic." },
  { "d":2, "prompt":"Ask which exit to use at the subway.", "answers":["Myeot beon chulgu-ro na-ga-yo?", "Myeot beon chulgu-ro nageashimnikka?", "Myeot beon chulgu-ro na-ga?"], "translations":["What number exit-by go-out-polite?", "What number exit-by go-out-formal?", "What number exit-by go-out? (casual)"], "notes":"출구 (Chulgu) = exit. 몇 번 출구 (Myeot beon chulgu) = what number exit. Korean subway exits are numbered — very precise and consistent. 1번 출구 (Ilbeon chulgu) = Exit 1. Most destination directions in Seoul are given by exit number — learn to say this and it's very useful." },
  { "d":2, "prompt":"A stranger walked you to your destination. Thank warmly.", "answers":["Jinjja gamsahaeyo, eomcheong dori usyeosseoyo!", "Jeongmal gamsahamnida, soo-go hasyeotseumnida!", "Jinjja gomawoyo! Deokbune chatasseoyo!"], "translations":["Really thank-you, extremely helpful-was-polite!", "Really thank-you-formal, took-effort-formal!", "Really thank-you! Thanks-to-you found! (casual)"], "notes":"수고하셨습니다 (Sugo hasyeotseumnida — 'you worked hard/took trouble') is the Korean phrase for acknowledging someone went out of their way. 덕분에 찾았어요 (Deokbune chajasseoyo — 'I found it thanks to you') is heartfelt. Korean kindness with directions is legendary — this full thanks is very appropriate." },
  { "d":3, "prompt":"Say I think I went the wrong way.", "answers":["Gil-eul teulli-n geot gatayo", "Gil-eul teulli-n geot gatseumnida", "Gil teulli-n geot gata"], "translations":["Way-obj wrong-thing seems-polite (I think I went the wrong way)", "Way-obj wrong-thing seems-formal", "Way wrong seems (casual)"], "notes":"틀리다 (Tteullida) = to be wrong/incorrect. 반대 방향인가요? (Bandae banghyang-inga-yo? — 'is it the opposite direction?') is a useful follow-up. Don't be embarrassed — Koreans are very gracious about redirecting lost visitors." },
  { "d":3, "prompt":"Ask is this the right direction for [destination]?", "answers":["[Mokjeokji] bang-hyang-i majayo?", "[Mokjeokji]-ro ganeun bang-hyangi itsseumnikka?", "[Mokjeokji] bang-hyang maje?"], "translations":["[Destination] direction-topic right-polite?", "[Destination]-to going direction-topic exist-formal?", "[Destination] direction right? (casual)"], "notes":"방향 (Banghyang) = direction. 맞아요? (Majayo? — 'is this right?') is the simplest confirmation question. 이쪽으로 가면 돼요? (Ijjuk-euro ga-myeon dwaeyo? — 'is it okay to go this way?') is also very natural and widely understood." },
  { "d":3, "prompt":"Ask if there's a taxi stand nearby.", "answers":["Geundeo-e taeksi seunggang-jang isseoyo?", "Geundeo-e taeksi seunggang-ga itsseumnikka?", "Geundeo-e taeksi seunggang isseo?"], "translations":["Nearby-at taxi stand exist-polite?", "Nearby-at taxi embarkation-topic exist-formal?", "Nearby-at taxi stand exist? (casual)"], "notes":"택시 승강장 (Taeksi seunggang-jang) = taxi stand. 택시 타는 곳 (Taeksi taneun got — 'place to take a taxi') is more casual. KakaoTaxi (카카오택시 app) eliminates the need for a physical stand — you can summon a taxi anywhere. Uber is available in Korea but less popular than KakaoTaxi." },
  { "d":4, "prompt":"Acknowledge complex directions: turn left then straight then second right.", "answers":["Jwachoek hwan-hu jikjin, du beonjjae oreunjjok, majayo?", "Jwachoek hwan, jikjin, du beonjjae oreunjjok hoejeon, geu-reoseumnikka?", "Jwachoek, jikjin, du beonjjae oreunjjok, maje?"], "translations":["Left turn-after straight, second right, right-polite?", "Left turn, straight, second right turn, that-formal?", "Left, straight, second right, right? (casual)"], "notes":"좌회전 (Jwaoejeon) = left turn, 우회전 (Uhwoejeon) = right turn, 직진 (Jikjin) = straight. 두 번째 (Du beonjjae) = the second. Repeating directions back to the giver is excellent practice and very well appreciated — Koreans love when you confirm understanding carefully." },
  { "d":4, "prompt":"You found the place. Express relief and gratitude.", "answers":["Chatasseoyo! Gamsahaeyo, jinjja daeseungyo!", "Do-chakhaetsseumnida! Gamsahamnida, doreumsim deuryo!", "Chatasseoyo! Jinjja gamsahaeyo, deo-bune!"], "translations":["Found-it! Thank-you, really lucky-polite! (found it! thank you so much!)", "Arrived-formal! Thank-you-formal, helped-so!", "Found-it! Really thank-you, thanks-to-you! (casual)"], "notes":"찾았어요! (Chajasseoyo! — 'I found it!') is the natural success exclamation. 덕분에 (Deokbune — 'thanks to you') closes it perfectly. If the person helped you in person, 정말 감사해요, 수고하셨어요 (Jeongmal gamsahaeyo, sugo hasyeotseoyo — 'truly thank you, you took great trouble') is the full warm version." }
];
