window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["market"] = [
  { "d":1, "prompt":"Greet the vendor at the stall.", "answers":["Annyeonghaseyo!", "Annyeong hashimnikka!", "Annyeong!"], "translations":["Hello! (peace-doing-are-you?)", "Hello! (formal)", "Hi! (casual)"], "notes":"Always greet vendors warmly — 안녕하세요 (Annyeonghaseyo) sets a positive tone immediately. Korean traditional markets (재래시장, Jaerae sijang) like Gwangjang Market, Namdaemun, and Dongdaemun are social, lively places where good manners lead to better service and sometimes extra items." },
  { "d":1, "prompt":"Ask how much something is.", "answers":["Eolmayeyo?", "Gagyeog-i eolmaseumnikka?", "Eolmaya?"], "translations":["How-much-is-polite?", "Price-topic how-much-formal?", "How much? (casual)"], "notes":"얼마예요? (Eolmayeyo?) is the simplest and most natural price question. In Korean markets, prices may not always be tagged — vendors expect this question. 깎아 주세요 (Kkakka juseyo — 'please give a discount') is the natural follow-up when the price seems high." },
  { "d":1, "prompt":"Say I'll take this one.", "answers":["I geol-lo halkgeyo", "I geol-lo butakhabnida", "I geo jwo"], "translations":["This-as will-do-polite (I'll take this one)", "This-as I-request-formal", "This give (casual)"], "notes":"이걸로 할게요 (I geol-lo halkgeyo) = 'I'll take this one.' 이거 주세요 (I-geo juseyo) = 'please give me this.' 살게요 (Salgeyo — 'I'll buy it') is equally natural. Decisive purchasing signals confidence to Korean market vendors — they appreciate it." },
  { "d":1, "prompt":"Say something looks too expensive.", "answers":["Jom bisaneyo", "Sangdanghi bisamnida", "Neomu bisayo"], "translations":["A-little expensive-polite (it's a little expensive)", "Considerably expensive-formal", "Too expensive (casual)"], "notes":"비싸다 (Bissada) = expensive. 조금 비싸네요 (Jogeum bissaneyo — 'it's a bit expensive') is the natural opening for negotiation. Korean market vendors generally expect some bargaining — expressing that something is expensive is the first step, not an insult." },
  { "d":1, "prompt":"Ask to try a sample.", "answers":["Matbwa bwado doeyeyo?", "Matbwa bwado doeseumnikka?", "Matbwa bwado dweyo?"], "translations":["Taste-try also okay-polite?", "Taste-try also okay-formal?", "Taste-try okay? (casual)"], "notes":"맛보다 (Matboda) = to taste. 시식해도 돼요? (Siik-haedo dwaeyo? — 'may I try a sample?') is more formal. Korean market vendors at food stalls (특히 광장시장 Gwangjang Market) enthusiastically offer samples — tasting is expected and part of the shopping culture." },
  { "d":1, "prompt":"Sample is delicious. React.", "answers":["Jinjja massisseoyo!", "Jeongmal masitseumnida!", "Jinjja massisseo! Daebak!"], "translations":["Really delicious-polite!", "Really delicious-formal!", "Really delicious! Jackpot! (casual)"], "notes":"맛있어요 (Massisseoyo) = delicious. 이거 살게요! (I-geo salgeyo! — 'I'll buy this!') makes the compliment actionable. Vendors love genuine reactions — expressing real enthusiasm often triggers a little extra or a better deal. 대박 맛있어요! (Daebak massisseoyo!) is very expressive." },
  { "d":1, "prompt":"Say see you next time.", "answers":["Ddo olgeyo!", "Ddo bangmun-hagetseumnida!", "Ddo ol-ge!"], "translations":["Again will-come-polite! (I'll be back!)", "Again will-visit-formal!", "Again will-come! (casual)"], "notes":"또 올게요 (Ddo olgeyo — 'I'll come again') is very powerful with Korean market vendors — it signals loyalty and often earns better prices next time. 자주 올게요 (Jaju olgeyo — 'I'll come often') is even stronger. Regular customers (단골, Dangol) get the best treatment at Korean markets." },
  { "d":2, "prompt":"Ask if it's fresh.", "answers":["Singsingheyo?", "Singsinghaseumnikka?", "Singsinghae?"], "translations":["Fresh-polite? (is it fresh?)", "Fresh-formal?", "Fresh? (casual)"], "notes":"싱싱하다 (Singsinghada) = fresh (specifically for food). 오늘 거예요? (Oneul geoyeyo? — 'is it from today?') is also very natural. Korean markets take freshness seriously — most produce is sourced daily. 언제 들어온 거예요? (Eonje deureoon geoyeyo? — 'when did it come in?') gets a more precise answer." },
  { "d":2, "prompt":"Ask for a smaller portion.", "answers":["Jogeumyo jukeo juseyo", "Jogeumyo jukeo jushigesseumnikka?", "Jogeumyo jukeo jwo"], "translations":["A-little less-give give-please (please give a smaller portion)", "A-little less could-give-formal?", "A-little less give (casual)"], "notes":"조금 (Jogeum) = a little. 적게 (Jeokge) = less/smaller amount. 반만 주세yo (Banman juseyo — 'give me half') is even more direct. Korean market portions at food stalls tend to be generous — no embarrassment in asking for less." },
  { "d":2, "prompt":"Ask for a bag.", "answers":["Bongtu juseyo", "Bongtu butakhabnida", "Bongtu jwo"], "translations":["Bag give-please", "Bag I-request-formal", "Bag give (casual)"], "notes":"봉투 (Bongtu) = bag (plastic). 비닐봉투 (Binilbongtu) = vinyl bag. 장바구니 (Jangbaguni) = shopping basket/bag. Bring your own reusable bag (에코백, Ekobek) to Korean markets — bags may be charged or unavailable at some eco-conscious stalls." },
  { "d":2, "prompt":"Pay in cash.", "answers":["Hyeon-geum-euro halgeyo", "Hyeon-geum-euro gyesan hagetseumnida", "Hyeon-geum-euro hae"], "translations":["Cash-by will-do-polite (I'll pay in cash)", "Cash-by pay will-formal", "Cash-by do (casual)"], "notes":"현금 (Hyeon-geum) = cash. Traditional Korean markets often prefer or require cash — card readers are less common at small stalls. Always carry some 1만원 (₩10,000) and 5천원 (₩5,000) bills for market shopping. ATMs near major markets are easy to find." },
  { "d":2, "prompt":"The vendor speaks too fast. Ask to slow down.", "answers":["Cheoncheonhi malhae juseyo", "Cheoncheonhi malsseum hae jushipsio", "Cheoncheonhi malhae jwo"], "translations":["Slowly speak give-please", "Slowly speech give-please-formal", "Slowly speak give (casual)"], "notes":"천천히 (Cheoncheonhi) = slowly. 좀 더 천천히 말씀해 주세요 (Jom deo cheoncheonhi malsseum-hae juseyo — 'please speak a little more slowly') is the full polite version. Korean market vendors won't be offended — they're used to helping customers and often enjoy the interaction with foreigners." },
  { "d":2, "prompt":"Say I come here often.", "answers":["Yeogi jaju wayo", "Yeogi jaju bangmun-haemnida", "Yeogi jaju wa"], "translations":["Here often come-polite (I come here often)", "Here often visit-formal", "Here often come (casual)"], "notes":"자주 (Jaju) = often. 단골이에요 (Dangol-ieyo — 'I'm a regular') is a magic phrase at Korean markets — vendors treat regular customers (단골, Dangol) far better with preferential pricing and extra portions. Saying this early establishes your status." },
  { "d":3, "prompt":"Ask what's in season.", "answers":["Yijeum mwoga jesari-eyo?", "Hyeon-jae-e mwoga jeol-eun-ga-yo?", "Yijeum mwoga jeol-iya?"], "translations":["Now what-is season-polite?", "Currently what-is in-season-polite?", "Now what in-season? (casual)"], "notes":"제철 (Jecheol) = in season (specifically for produce). 제철 과일/야채 (Jecheol gwail/yachae) = in-season fruit/vegetables. Seasonal produce in Korea: 딸기 (Ttalgi — strawberry, spring), 복숭아 (Boksungah — peach, summer), 감 (Gam — persimmon, autumn), 귤 (Gyul — tangerine, winter)." },
  { "d":3, "prompt":"Ask how to cook an unfamiliar vegetable.", "answers":["I geo eotteoke yori haeyo?", "I chaeso eotteoke yori hasimnikka?", "I geo eotteoke yori hae?"], "translations":["This one how cook-polite?", "This vegetable how cook-formal?", "This one how cook? (casual)"], "notes":"채소 (Chaeso) = vegetable. 요리하다 (Yorihada) = to cook. Korean market vendors are often brilliant cooks with practical tips — asking how to cook something opens wonderful conversations. 어떻게 먹어요? (Eotteoke meogeoyo? — 'how do you eat this?') is the simplest phrasing." },
  { "d":3, "prompt":"Ask for a discount for buying multiple items.", "answers":["Yeoreo gae sa-myeon kkakka juseyo?", "Daeryang gumae shi halin bwa juseyo", "Yeoreo gae sa-myeon ssa-ge hae jwo"], "translations":["Multiple buy-if discount-give please?", "Bulk purchase-at discount try give-please (formal)", "Multiple buy-if cheap-make give (casual)"], "notes":"깎아 주세요 (Kkakka juseyo — 'please give a discount') is the essential market bargaining phrase. 더 사면 얼마예요? (Deo sa-myeon eolmayeyo? — 'if I buy more, how much?') is a smart negotiating opener. Korean market bargaining is friendly and expected — vendors rarely take offence." },
  { "d":3, "prompt":"Compliment the vendor's produce.", "answers":["Yeogi hangangyo sin-seohan geot gata-yo!", "Yeo-gi sanshin-pum-i hangasang singsinghaeyeo!", "Yeogi geonneun-da jinjja sinsinghae!"], "translations":["Here always fresh-thing seems-polite! (the produce here always looks fresh!)", "Here products-topic always fresh-formal!", "Here produce really fresh! (casual)"], "notes":"싱싱하다 (Singsinghada) = fresh. 항상 (Hangsang) = always. 품질 (Pumjil) = quality. 품질이 정말 좋아요 (Pumjiri jeongmal joahayo — 'the quality is really good') is a meaningful compliment — Korean vendors take great pride in their produce quality." },
  { "d":4, "prompt":"Vendor says can't go lower. Accept gracefully.", "answers":["Geuraeyo, I geol-lo halkgeyo", "Algetseumnida, I geol-lo hagetseumnida", "Geurae, I geo salge"], "translations":["Okay, this-as will-do-polite (okay, I'll take it)", "Understood-formal, this-as will-do-formal", "Okay, this will-buy (casual)"], "notes":"알겠어요 (Algeseoyo — 'I understand/okay') gracefully closes the negotiation. 그래요, 할게요 (Geuraeyo, halkgeyo — 'okay, I'll do it') is equally smooth. Never show frustration after negotiation — Koreans value gracious acceptance, and vendors may throw in a small extra if you're pleasant about it." },
  { "d":4, "prompt":"Vendor throws in a free extra. Express surprise and thanks.", "answers":["Aisee, jinjja yo?! Gamsahaeyo!", "Gamsahamnida! Neomu gamsa-hamnida!", "Daebak! Gamsahaeyo!"], "translations":["Wow, really?! Thank-you-polite!", "Thank-you-formal! Very thank-you-formal!", "Jackpot! Thank-you! (casual)"], "notes":"끼워 준다 (Kkiwo junda — 'throwing in/adding') is the Korean market generosity custom. 덤 (Deom) = a free extra item thrown in at markets — a beautiful Korean market tradition. 이게 다예요? (Ige da-yeyo? — 'is this all for me?') with a surprised expression adds warmth to the reaction." }
];
