window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["office"] = [
  { "d":1, "prompt":"Greet a colleague in the morning.", "answers":["Annyeonghaseyo!", "Annyeong hashimnikka!", "Annyeong!"], "translations":["Hello! (peace-doing-are-you?)", "Hello! (formal)", "Hi! (casual)"], "notes":"Annyeonghaseyo to everyone you pass — in Korean offices, greeting colleagues when you arrive is very important. 출근하셨어요? (Chulgeun-hashyeotseoyo? — 'did you come in?') acknowledges the colleague's presence warmly. Korean office culture is formal — always use speech levels appropriate to hierarchy." },
  { "d":1, "prompt":"Say see you tomorrow.", "answers":["Naeil bwayo!", "Naeil boepgesseumnida!", "Naeil bwa!"], "translations":["Tomorrow see-polite! (see you tomorrow!)", "Tomorrow see-honorific-formal!", "Tomorrow see! (casual)"], "notes":"내일 봐요 (Naeil bwayo) = see you tomorrow. 수고하셨습니다 (Sugo-hashyeotsseumnida — 'you worked hard today') is the very Korean way to acknowledge a colleague leaving — almost always said at day's end in Korean workplaces." },
  { "d":1, "prompt":"Colleague apologizes for something small. Reassure them.", "answers":["Gwaenchanayo!", "Gwaenchansseumnida!", "Gwaenchana!"], "translations":["It's okay-polite! (it's fine!)", "It's okay-formal!", "It's fine! (casual)"], "notes":"괜찮아요 (Gwaenchanayo) = it's fine/it's okay. 신경 쓰지 마세요 (Shingyeong sseuji maseyo — 'don't worry about it') is warm reassurance. In Korean office culture, small apologies are common — reassuring colleagues genuinely and warmly maintains good 분위기 (Bunwigi — atmosphere)." },
  { "d":1, "prompt":"Say I'll be right back.", "answers":["Geum-bang olgeyo", "Geum-bang doraogetsseumnida", "Geum-bang ol-ge"], "translations":["Right-away will-come-polite (I'll be right back)", "Right-away will-return-formal", "Right-away come (casual)"], "notes":"금방 (Geumbang) = right away/very soon. 잠깐 자리 비울게요 (Jamkkan jari biulgeyo — 'I'll be away from my seat briefly') is more formal and specific. In Korean offices, letting colleagues know you're temporarily stepping away is considered courteous." },
  { "d":1, "prompt":"Ask where the bathroom is.", "answers":["Hwa-jangsil-i eodiyeyo?", "Hwa-jangsil-i eodiissseumnikka?", "Hwa-jangsil eodisseo?"], "translations":["Bathroom-topic where-is-polite?", "Bathroom-topic where-is-formal?", "Bathroom where? (casual)"], "notes":"화장실 (Hwajang-sil) = bathroom/restroom (literally 'flower decoration room'). 남자 화장실 (Namja hwajang-sil) = men's room. 여자 화장실 (Yeoja hwajang-sil) = women's room. Korean office buildings have well-maintained restrooms — often on dedicated floors in large buildings." },
  { "d":1, "prompt":"Say I'm going home now.", "answers":["Ijeun galgeyo, sugu haseyo", "Meonjeo deugasseumnida, sugu haseyo", "Igal-ge, sugu hasyeo"], "translations":["Now will-go, work-hard (I'm leaving, take care)", "First I-leave-formal, work-hard (leaving first, goodbye)", "Going, work-hard (casual)"], "notes":"먼저 들어가겠습니다 (Meonjeo deugasseumnida — 'I'll leave first') is the formal way to say goodbye when you leave before others. 수고하세요 (Sugo haseyo — 'keep working hard') is said to those still working. This combination is essential Korean workplace etiquette." },
  { "d":2, "prompt":"Apologize for being late.", "answers":["Neujeotseo joesonghaeyo", "Neujeun geot joesonghaeyo", "Neujeotseo mianhaee"], "translations":["Late-because sorry-polite (sorry for being late)", "Late-thing sorry-polite", "Late-because sorry (casual)"], "notes":"늦다 (Neutda) = to be late. 교통 때문에 (Gyotong ttaemune — 'because of traffic') is the standard explanation. In Korean work culture, punctuality is important — even being slightly late warrants a genuine apology. 지각 (Jigak) = tardiness (formal/HR term)." },
  { "d":2, "prompt":"Say I'm still learning.", "answers":["Ajik baeugo isseoyo", "Ajik baeeugo itsseumnida", "Ajik baeugo isseo"], "translations":["Still learning-am-polite", "Still learning-am-formal", "Still learning (casual)"], "notes":"아직 배우고 있어요 (Ajik baeugo isseoyo) = 'I'm still learning.' 부족한 점 있으면 말씀해 주세요 (Bujokan jeom isseumyeon malsseum-hae juseyo — 'please tell me if there are areas I need to improve') shows humility and openness — very valued in Korean workplace culture (겸손, Gyeomson)." },
  { "d":2, "prompt":"Sympathize with a tired colleague.", "answers":["Gosamyeo! Jom swiseyo", "Sugo hashipnida! Jom swishipsio", "Gosaesseo! Jom swieyo"], "translations":["You-worked-hard! Rest a bit-polite", "Worked-hard-formal! Rest-formal", "Worked-hard! Rest a bit (casual)"], "notes":"고생했어요 (Gosaenghaesseoyo) = 'you worked hard/went through hardship.' 수고했어요 (Sugo-haesseoyo) = 'good work/you worked hard.' Both are essential Korean phrases for acknowledging someone's effort. Showing empathy for colleagues' workload is a core part of Korean team culture." },
  { "d":2, "prompt":"Ask do you want coffee?", "answers":["Keopi deu-shilgeyo?", "Keopi deu-shige tsseumnikka?", "Keopi maseulgeyo?"], "translations":["Coffee will-have-honorific-polite? (would you like coffee?)", "Coffee will-have-honorific-formal?", "Coffee will-drink-polite? (casual)"], "notes":"드시다 (Deusida) is the honorific form of 먹다/마시다 (to eat/drink) — always use it when offering food/drink to seniors. 드릴까요? (Deurilkkayo? — 'shall I give you?') is a polite offering form. Korean office coffee culture is strong — making coffee for senior colleagues is a common gesture." },
  { "d":2, "prompt":"Say proper goodbye to a leaving colleague.", "answers":["Sugu haseyo, annyeong-hi gaseyo", "Sugu hashyeotsseumnida, annyeong-hi gashipsio", "Sugu haesseo, annyeong!"], "translations":["Work-hard do, peacefully-go-polite (good work, goodbye!)", "Worked-hard-formal, peacefully-go-formal", "Worked-hard, peace! (casual)"], "notes":"수고하셨습니다 + 안녕히 가세요 (Sugo-hashyeotsseumnida + Annyeong-hi gaseyo) is the complete formal farewell. This combination is so common in Korean workplaces that it becomes instinctive. The 수고 acknowledgement is culturally very important — always recognize colleagues' effort." },
  { "d":2, "prompt":"Colleague invites you to lunch. Say yes!", "answers":["Ne, gachi gayo!", "Ne, gachi samsuhashipsida!", "Gachi ga!", "Ne, joayo!"], "translations":["Yes, together go-polite! (yes, let's go together!)", "Yes, together go-formal!", "Together go! (casual)", "Yes, good-polite! (yes, great!)"], "notes":"같이 (Gachi) = together. 점심 (Jeomsim) = lunch. Korean office lunch culture is very communal — eating together strengthens team bonds. 뭐 먹을까요? (Mwo meogeulkkayo? — 'what shall we eat?') is the exciting follow-up. Refusing lunch without good reason can seem antisocial in Korean offices." },
  { "d":3, "prompt":"Politely excuse yourself from a conversation.", "answers":["Joesonghaeyo, jamkkan sillyeehalkgeyo", "Sillyehamnida, jamkkan jariseo ireoseo ya haetseumnida", "Jamkkan sillyeehalkge"], "translations":["Sorry, briefly excuse-will-polite (sorry, I'll excuse myself briefly)", "Excuse-me-formal, briefly seat-from rise-must", "Briefly excuse (casual)"], "notes":"실례하겠습니다 (Sillyehagetseumnida — 'I'll take the liberty/excuse me') is the formal way to exit gracefully. 잠깐 실례할게요 (Jamkkan sillyehalgeyo — 'I'll briefly excuse myself') is natural in offices. Koreans value acknowledging interruptions — a small bow while saying this is appropriate." },
  { "d":3, "prompt":"Say you don't understand. Ask for clarification.", "answers":["Joesonghaeyo, jom deo seolmyeong hae jushigesseosseoyo?", "Sillyehamnida, dashi hanbeon seolmyeong butakhabnida", "Jom deo seolmyeong hae jwo"], "translations":["Sorry, a-bit more explain could-give-would-polite?", "Excuse-me-formal, again once explain I-request-formal", "A-bit more explain give (casual)"], "notes":"설명해 주세요 (Seolmyeong-hae juseyo — 'please explain') is the core request. 이해가 잘 안 됐어요 (Ihaega jal an dwaesseoyo — 'I didn't quite understand') is softer than 'I don't understand.' In Korean work culture, admitting confusion is done carefully — always with a respectful tone and never bluntly." },
  { "d":3, "prompt":"Thank a colleague who genuinely helped you.", "answers":["Jinjja gamsahaeyo, eomcheong dori usyeosseoyo", "Jeongmal gamsahamnida, doreomsim deuryo", "Gamsahaeyo, jinjja dori usyeotseo"], "translations":["Really thank-you, extremely helpful-was-polite", "Really thank-you-formal, help-gave-formal", "Thank-you, really helpful-was (casual)"], "notes":"정말 도움이 됐어요 (Jeongmal doumi dwaesseoyo — 'it was really helpful') is specific and sincere. 덕분에 (Deokbune — 'thanks to you') can be added: 덕분에 해결됐어요 (Deokbune haegyeol-dwaesseoyo — 'it was resolved thanks to you'). Specific gratitude is very meaningful in Korean work culture." },
  { "d":4, "prompt":"Ask for feedback on your work politely.", "answers":["Jeo-ui eopmu-e daehan peedeubaek jushigesseosseoyo?", "Jeo-ui eopmu-e daehan pyeongga butakhabnida", "Jeo-ui eopmu peedeubaek jwo"], "translations":["My work-about feedback could-give-polite?", "My work-about evaluation I-request-formal", "My work feedback give (casual)"], "notes":"피드백 (Peedeubaek) = feedback (English loanword). 평가 (Pyeongga) = evaluation/assessment. Asking for feedback in Korean offices requires framing it humbly — 부족한 점 알려 주세요 (Bujokan jeom alryeo juseyo — 'please let me know my shortcomings') is very naturally Korean." },
  { "d":4, "prompt":"Say I'll try my best.", "answers":["Cheonsin halkgeyo", "Seongsim-euro im-ham-hagetseumnida", "Cheonsin halkge"], "translations":["Best-will-do-polite (I'll give my best)", "Sincerely-with work-will-formal (I'll work sincerely)", "Best will-do (casual)"], "notes":"최선을 다 할게요 (Cheoson-eul da halgeyo — 'I'll give my full best effort') is the most natural. 열심히 하겠습니다 (Yeolssimhi hagetseumnida — 'I'll work hard') is the classic Korean commitment phrase — heard constantly in offices, schools, and sports contexts in Korea." }
];
