window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["pharmacy"] = [
  { "d":1, "prompt":"Say you have a headache.", "answers":["Meori-ga apa-yo", "Dutongi itsseumnida", "Meori apa"], "translations":["Head-topic hurts-polite (my head hurts)", "Headache-topic exist-formal (I have a headache)", "Head hurts (casual)"], "notes":"머리가 아파요 (Meori-ga apayo) = 'my head hurts.' 두통 (Dutong) = headache (medical term). Korean pharmacies (약국, Yakguk) are excellent first stops — pharmacists are trained to advise on OTC medication and are a primary healthcare touchpoint for many Koreans." },
  { "d":1, "prompt":"Say you have a stomachache.", "answers":["Bae-ga apa-yo", "Boktongi itsseumnida", "Bae apa"], "translations":["Stomach-topic hurts-polite (my stomach hurts)", "Stomach-pain-topic exist-formal", "Stomach hurts (casual)"], "notes":"배가 아파요 (Baega apayo) = 'my stomach/belly hurts.' 복통 (Boktong) = abdominal pain (medical). 소화불량 (Sohwabullyang) = indigestion. Korean pharmacies stock excellent 소화제 (Sohwaje — digestive medicine) — very useful after heavy Korean meals." },
  { "d":1, "prompt":"Say you have a fever.", "answers":["Yeol-i na-yo", "Yeori issseumnida", "Yeol na"], "translations":["Fever-topic come-out-polite (I have a fever)", "Fever-topic exist-formal", "Fever comes (casual)"], "notes":"열이 나요 (Yeori nayo) = 'I have a fever.' 체온을 재다 (Cheon-eul jaeda) = to take temperature. 38도 이상이에요 (Sampaldo isang-ieyo — 'it's 38°C or above'). Korean pharmacists will often take your temperature before recommending medication." },
  { "d":1, "prompt":"Say you have a cold.", "answers":["Gam-gi geori-n geot gatayo", "Gamgi-e geollireotsseumnida", "Gam-gi geori-n geot gata"], "translations":["Cold-to caught-thing seems-polite (I think I caught a cold)", "Cold-to caught-formal", "Cold caught seems (casual)"], "notes":"감기 (Gamgi) = cold/flu. 걸리다 (Geollida) = to catch (an illness). 독감 (Dok-gam) = influenza/serious flu. 감기약 (Gamgiyak) = cold medicine. Korean pharmacies carry excellent cold remedies. Pharmacists often recommend 쌍화탕 (Ssanghwatang) — a traditional herbal cold remedy beloved in Korea." },
  { "d":1, "prompt":"Ask for pain medication.", "answers":["Jintongje juseyo", "Jintongje butakhabnida", "Jintongje jwo"], "translations":["Painkiller give-please", "Painkiller I-request-formal", "Painkiller give (casual)"], "notes":"진통제 (Jintongje) = painkiller/analgesic. 타이레놀 (Tylenol) and 이부프로펜 (Ibuprofen) are common OTC options. Also ask for 게보린 (Geborin) — a very popular Korean OTC painkiller combining acetaminophen, caffeine, and aspirin. Pharmacists will recommend the best option for your specific pain." },
  { "d":1, "prompt":"Say it hurts here.", "answers":["Yeogi apa-yo", "I buuun-i apsseumnida", "Yeogi apa"], "translations":["Here hurts-polite (it hurts here)", "This area-topic hurts-formal", "Here hurts (casual)"], "notes":"여기 아파요 (Yeogi apayo — 'it hurts here') + pointing is universally understood. 아프다 (Apeuda) = to hurt/be in pain. 심해요 (Simhaeyo — 'it's severe') adds useful context. Korean pharmacists are trained for physical consultation — don't hesitate to show exactly where it hurts." },
  { "d":1, "prompt":"Pharmacist gives you medicine. Say thank you.", "answers":["Gamsahaeyo!", "Gamsahamnida!", "Gomawoyo!"], "translations":["Gratitude-polite! (thank you!)", "Gratitude-formal!", "Grateful-polite! (thank you!)"], "notes":"약사 (Yaksa) = pharmacist. Korean pharmacists are highly educated (6-year pharmacy degree required) and provide genuinely useful medical advice. 잘 낫겠습니다 (Jal natgetseumnida — 'I hope to get well') is a polite closing. 건강하세요 (Geongang-haseyo — 'stay healthy') is a warm farewell." },
  { "d":2, "prompt":"Ask how many times a day to take the medicine.", "answers":["Haru-e myeot beon meogeoyo?", "Haru-e myeot beon bokwong-haeyya haseumnikka?", "Haru-e myeot beon meogeo?"], "translations":["One-day-in how-many times eat-polite? (how many times a day to take?)", "One-day-in how-many times take-must-formal?", "One-day-in how-many times eat? (casual)"], "notes":"하루에 (Harue) = per day. 몇 번 (Myeot beon) = how many times. 식후에 (Sikhue — 'after meals') vs 식전에 (Sikjeone — 'before meals') — timing instructions on Korean medicine labels. 복용법 (Bokyongbeop) = dosage instructions. Always ask clearly if the label is only in Korean." },
  { "d":2, "prompt":"Say you feel dizzy.", "answers":["Eo-jireowo-yo", "Hyeon-gi-jeungyi issseumnida", "Eo-jireowo"], "translations":["Dizzy-polite (I feel dizzy)", "Dizziness-topic exist-formal", "Dizzy (casual)"], "notes":"어지러워요 (Eojireowoyo) = 'I'm dizzy.' 현기증 (Hyeon-gi-jeung) = dizziness (medical term). 빙빙 돌아요 (Bing-bing dorayo — 'spinning around') is more expressive and vivid. Dizziness can signal various conditions — Korean pharmacists will ask follow-up questions to narrow down the cause." },
  { "d":2, "prompt":"Say you feel nauseous.", "answers":["Meswi-ga na-yo", "Oesim-i issseumnida", "Meswi-ga na"], "translations":["Nausea-topic comes-polite (I feel nauseous)", "Nausea-topic exist-formal", "Nausea comes (casual)"], "notes":"메스꺼워요 (Meskkeowoyo) = 'I feel nauseous' (more vivid). 구역질 (Gu-yeokjil) = nausea/urge to vomit. 체하다 (Chehada) = to have indigestion/upset stomach. Korean pharmacies stock excellent 멀미약 (Meolmiyak — motion sickness medicine) and 소화제 (Sohwaje — digestive medicine)." },
  { "d":2, "prompt":"Ask if you need a prescription.", "answers":["Cheobang-jeon pi-lyo haeyo?", "Cheobang-jeon-i piryohasimnikka?", "Cheobang-jeon pi-lyo hae?"], "translations":["Prescription necessary-polite? (do I need a prescription?)", "Prescription-topic necessary-formal?", "Prescription need? (casual)"], "notes":"처방전 (Cheobang-jeon) = prescription. 전문의약품 (Jeonmun-uiyakpum) = prescription-only medicine. 일반의약품 (Ilban-uiyakpum) = OTC medicine. Some medications available OTC in Korea require prescriptions elsewhere (and vice versa) — Korean pharmacists will clearly tell you what's needed." },
  { "d":2, "prompt":"Ask for a bandage.", "answers":["Bandage juseyo", "Bando-eo juseyo", "Bandage jwo"], "translations":["Bandage give-please", "Bandage give-please (using band-aid term)", "Bandage give (casual)"], "notes":"반창고 (Banchang-go) = adhesive bandage/plaster. 밴드 (Baendeu) = band-aid (brand name used generically). 거즈 (Geojeu) = gauze. 의료용 테이프 (Uiryoyong teipeu) = medical tape. Korean pharmacies are extremely well-stocked with wound care supplies — much cheaper than hospital emergency rooms for minor wounds." },
  { "d":2, "prompt":"Ask for a thermometer.", "answers":["Cheononge juseyo", "Cheonong-gyega issseumnikka?", "Cheonong-ge jwo"], "translations":["Thermometer give-please", "Thermometer-topic exist-formal?", "Thermometer give (casual)"], "notes":"체온계 (Cheon-ong-gye) = thermometer. 귀 체온계 (Gwi cheon-ong-gye) = ear thermometer. 이마 체온계 (Ima cheon-ong-gye) = forehead thermometer. Korean pharmacies carry digital thermometers of various types. Normal Korean body temperature: 36.5°C. Fever threshold: 37.5°C or above." },
  { "d":3, "prompt":"Say you have a sore throat.", "answers":["Mokuyi apa-yo", "Insaengi apaeotsseumnida", "Mok apa"], "translations":["Throat-topic hurts-polite (my throat hurts)", "Throat-topic hurts-formal", "Throat hurts (casual)"], "notes":"목 (Mok) = throat/neck. 목이 아파요 (Mogi apayo) = 'my throat hurts.' 목이 쉬었어요 (Mogi swieo-seoyo — 'my throat is hoarse') is also useful. Korean pharmacists commonly recommend 스프레이 (Seupeurei — throat spray) or 목 사탕 (Mok satang — throat lozenges) for initial relief before seeing a doctor." },
  { "d":3, "prompt":"Say you have a cough.", "answers":["Gi-chim-i na-yo", "Haekkarim-i itsseumnida", "Gi-chim na"], "translations":["Cough-topic comes-polite (I have a cough)", "Coughing-topic exist-formal", "Cough comes (casual)"], "notes":"기침 (Gichim) = cough. 기침이 나요 (Gichimi nayo) = 'I have a cough/am coughing.' 가래 (Garae) = phlegm. 목 시럽 (Mok sirrop — 'throat syrup') or 기침약 (Gichimyak — cough medicine) are common pharmacy recommendations. 하루 종일 기침해요 (Haru jongjil gichimhaeyo — 'I've been coughing all day') gives useful context." },
  { "d":3, "prompt":"Say you have a runny nose.", "answers":["Ko-mul-i na-yo", "Bi-ryu-ga itsseumnida", "Ko-mul na"], "translations":["Nose-water-topic comes-polite (I have a runny nose)", "Runny-nose-topic exist-formal", "Nose-water comes (casual)"], "notes":"콧물 (Ko-mul) = nasal discharge/runny nose (literally 'nose water'). 코가 막혔어요 (Koga makhyeosseoyo — 'my nose is blocked/stuffy') is the opposite symptom. Korean pharmacies stock excellent antihistamines and decongestants. 알레르기 비염 (Allereugi birye-om) = allergic rhinitis." },
  { "d":3, "prompt":"Ask if you should see a doctor.", "answers":["Byeongwon-e ga-ya haeyo?", "Byeongwon-e ga-ya haseumnikka?", "Byeongwon ga-ya hae?"], "translations":["Hospital-to go-must-polite? (should I go to the hospital?)", "Hospital-to go-must-formal?", "Hospital go-must? (casual)"], "notes":"병원 (Byeongwon) = hospital/clinic. 내과 (Naegwa) = internal medicine (general practitioner). 응급실 (Eunggeupssil) = emergency room. Korean pharmacists will honestly tell you if your condition warrants a doctor visit. 근처에 내과 있어요? (Geuncheoe naegwa isseoyo? — 'is there a clinic nearby?') is a useful follow-up." },
  { "d":4, "prompt":"Declare an allergy to a specific medicine.", "answers":["[Yakpum]-e allereugi isseoyo", "[Yakpum]-e allereugi ga itsseumnida", "[Yakpum]-e allereugi isseo"], "translations":["[Medicine]-to allergy exist-polite (I have an allergy to [medicine])", "[Medicine]-to allergy-topic exist-formal", "[Medicine]-to allergy exist (casual)"], "notes":"알레르기 (Allereugi) = allergy. 아스피린 (Aseupiron — aspirin), 페니실린 (Penissillin — penicillin) are common drug allergies to know in Korean. Always state allergies clearly and firmly — Korean pharmacists take this very seriously and will check for contraindications thoroughly." },
  { "d":4, "prompt":"Pharmacist says go to hospital. Ask where.", "answers":["Byeongwon-e ga-ya haeyo? Geundeo byeongwon-i eodiisseoyo?", "Byeongwon bangmun-i pilryohasimnikka? Geundeo byeongwon-i eodiissseumnikka?", "Byeongwon ga-ya hae? Eodisseo?"], "translations":["Hospital-to go-must-polite? Nearby hospital-topic where-is?", "Hospital visit-topic necessary-formal? Nearby hospital where-is?", "Hospital go-must? Where? (casual)"], "notes":"응급실 (Eunggeupssil) = emergency room. 가장 가까운 병원 (Gajang gakkaun byeongwon — 'nearest hospital'). Korean emergency number: 119 (ambulance and fire). 24시간 병원 (Isipsa sigan byeongwon) = 24-hour clinic — common in Korean cities and very useful for late-night medical needs." }
];
