window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["restro"] = [
  { "d":1, "prompt":"Get the server's attention.", "answers":["Yeogiyo!", "Jeogiyo!", "Jeo-gi!"], "translations":["Here! (excuse me, server!)", "Over there! (excuse me!)", "That-place! (hey!, casual)"], "notes":"여기요! (Yeogiyo!) literally means 'over here!' and is the standard and completely acceptable way to call staff in Korean restaurants. Some modern restaurants use a table button (벨, Bell) instead — push it to summon staff." },
  { "d":1, "prompt":"Staff asks how many people. Say two.", "answers":["Du myeong-ieyo", "Du bun-imnida", "Dul-ieyo / Du myeong"], "translations":["Two people-am-polite (it's two people)", "Two (honorific)-am-formal", "Two-is / Two people (casual)"], "notes":"두 명 (Du myeong) = two people. 분 (Bun) is the honorific counter for people — use it to sound extra polite. Korean restaurants often have 2-person minimum for certain dishes (for 2 or more): 2인분 (Iinbun) = two servings minimum." },
  { "d":1, "prompt":"Ask for water.", "answers":["Mul juseyo", "Mul jushigesseumnikka?", "Mul jwo"], "translations":["Water give-please", "Water could-give-formal?", "Water give (casual)"], "notes":"물 (Mul) = water. Korean restaurants often provide complimentary water (수돗물, Sudot-mul or 정수기 물, Jeongsugyi mul). Cold water pitchers are usually self-serve. Servers may ask 생수 드릴까요? (Still water?) in upscale restaurants." },
  { "d":1, "prompt":"Ask for the menu.", "answers":["Menyupan juseyo", "Menyupan butakhabnida", "Menyu jwo"], "translations":["Menu give-please", "Menu I-request-formal", "Menu give (casual)"], "notes":"메뉴판 (Menyupan) = menu board/booklet. Many Korean restaurants now have menus via QR code or on wall boards — look around before asking. 추천 메뉴가 뭐예요? (What's the recommended menu?) is a great follow-up." },
  { "d":1, "prompt":"Food arrives. Server says enjoy. Respond.", "answers":["Gamsahaeyo!", "Gamsahamnida!", "Gomawoyo!"], "translations":["Gratitude-polite! (thank you!)", "Gratitude-formal!", "Grateful-polite! (thank you!)"], "notes":"잘 먹겠습니다 (Jal meokgesseumnida — 'I will eat well') is the traditional Korean phrase said before eating — like saying grace. It's very culturally appreciated. 맛있어 보여요 (Massisseo boyeoyo — 'it looks delicious') is a warm response on food arrival." },
  { "d":1, "prompt":"Ask for the bill.", "answers":["Gyesan hae juseyo", "Gyesan butakhabnida", "Gyesan hae jwo"], "translations":["Bill settle give-please", "Bill I-request-formal", "Bill settle give (casual)"], "notes":"계산 (Gyesan) = payment. 영수증 주세요 (Yeongsujung juseyo) = receipt please. In Korean restaurants, one person often pays the full bill (더치 페이, Dochi pe-i — Dutch pay, is growing but not universal). The host typically insists on paying — accept gracefully." },
  { "d":1, "prompt":"Pay by card.", "answers":["Kadeu-ro halkgeyo", "Kadeu-ro gyesan hagetseumnida", "Kadeu-ro hae"], "translations":["Card-by will-pay-polite", "Card-by pay will-formal", "Card-by do (casual)"], "notes":"카드 (Kadeu) = card. Korea is very cashless — card is standard everywhere. 일시불로 해주세요 (Ilsibul-ro haejuseyo — 'please do it as a one-time payment') vs. 할부로 (Halbu-ro — 'in installments'). Mobile payment (카카오페이, 삼성페이) is also very common." },
  { "d":1, "prompt":"Say you're full.", "answers":["Bae bul-leo-yo", "Bae-ga bul-leo-tsseumnida", "Bae bul-leo"], "translations":["Stomach full-polite (I'm full)", "Stomach-topic full-formal", "Stomach full (casual)"], "notes":"배 불러요 (Bae bulreoyo) = I'm full. 잘 먹었습니다 (Jal meogeotsseumnida — 'I ate well') is the traditional closing phrase after a meal — like a verbal bow of gratitude. Very culturally appreciated and always makes a good impression." },
  { "d":2, "prompt":"Ask if this dish is spicy.", "answers":["I eum-sik maewayo?", "I yo-ri-ga maeuseumnikka?", "I geo maeweo?"], "translations":["This food spicy-polite?", "This dish-topic spicy-formal?", "This one spicy? (casual)"], "notes":"맵다 (Maepda) = spicy. 안 맵게 해주세요 (An maepge haejuseyo — 'please make it not spicy') is essential for chili-sensitive eaters. Korean food is often significantly spicy — even dishes not labelled as spicy can have moderate heat. Ask first." },
  { "d":2, "prompt":"Say no onions please.", "answers":["Pa bbae juseyo", "Pa je-geo butakhabnida", "Pa bbae jwo"], "translations":["Onion remove give-please (please remove onion)", "Onion remove I-request-formal", "Onion remove give (casual)"], "notes":"파 (Pa) = green onion/scallion (very common in Korean food). 양파 (Yangpa) = regular onion. 빼다 (Bbaeda) = to remove/leave out. 빼 주세요 (Bbae juseyo) is the key phrase for removing any ingredient — just add the ingredient before it." },
  { "d":2, "prompt":"Ask for more side dishes / bread / rice.", "answers":["Banchan deo juseyo", "Banchan deo jushigesseumnikka?", "Banchan deo jwo"], "translations":["Side-dishes more give-please", "Side-dishes more could-give-formal?", "Side-dishes more give (casual)"], "notes":"반찬 (Banchan) = Korean side dishes — the small plates served alongside rice. They're FREE refills in most traditional restaurants. 더 주세요 (Deo juseyo — 'more please') can be used for any item. Refilling banchan is completely expected and welcomed." },
  { "d":2, "prompt":"Ask for napkins.", "answers":["Hyuji juseyo", "Hyuji butakhabnida", "Hyuji jwo"], "translations":["Tissue/napkin give-please", "Tissue I-request-formal", "Tissue give (casual)"], "notes":"휴지 (Hyuji) = tissue/napkin (literally tissue paper). In many Korean restaurants, tissues are in a tissue box on the table — look before asking. 냅킨 (Naepkin) is also used for formal cloth/paper napkins." },
  { "d":2, "prompt":"Ask if a dish has meat in it.", "answers":["I eum-sik-e gogi isseoyo?", "I yo-ri-e gogi itsseumnikka?", "I geo-e gogi isseo?"], "translations":["This food-in meat exist-polite?", "This dish-in meat exist-formal?", "This one-in meat exist? (casual)"], "notes":"고기 (Gogi) = meat. 소고기 (Sogogi) = beef, 돼지고기 (Doaejigogi) = pork, 닭고기 (Dalkgogi) = chicken. Important: in Korean, 고기 often specifically means red meat — chicken (닭) and seafood (해물, Haemul) may not be considered 고기 by some cooks." },
  { "d":2, "prompt":"Say you don't eat meat.", "answers":["Jeoneun gogi an meogeoyo", "Jeoneun gogi-reul meokji anseumnida", "Na gogi an meogeo"], "translations":["I meat not eat-polite", "I meat-obj eat-not-formal", "I meat not eat (casual)"], "notes":"채식주의자 (Chaesilju-uija) = vegetarian. 완전 채식 (Wanjeon chaesik) = vegan. Vegetarian options in traditional Korean restaurants can be limited — many dishes use anchovy broth or shrimp paste as base. Temple food restaurants (사찰음식, Sachal eumsik) are excellent vegetarian options." },
  { "d":2, "prompt":"Ask for a takeaway box.", "answers":["Ssaigeo juseyo", "Ssaigeo butakhabnida", "Ssaigeo jwo"], "translations":["Wrap-and-give give-please (doggy bag, please)", "Wrap I-request-formal", "Wrap give (casual)"], "notes":"싸가다 (Ssagada) = to wrap and take. 포장 (Pojang) = packaging/takeaway. 남은 거 싸주세요 (Nameun geo ssajuseyo — 'please wrap up the leftovers') is fully natural. Taking leftovers home is perfectly normal in Korea — no social stigma at all." },
  { "d":3, "prompt":"Ask for a vegetarian option.", "answers":["Chaesik menu isseoyo?", "Chaesig menu-ga itsseumnikka?", "Gogi obs-neun geon isseo?"], "translations":["Vegetarian menu exist-polite?", "Vegetarian menu-topic exist-formal?", "Meat not-exist-thing is? (casual)"], "notes":"채식 (Chaesik) = vegetarian diet. 고기 없는 (Gogi eomneun) = without meat. In cities, 비건 (Bigan — vegan) restaurants are growing. Temple food (사찰음식, Sachal eumsik) restaurants specialize in plant-based Korean cooking and are excellent." },
  { "d":3, "prompt":"Ask what the most popular dish is.", "answers":["Je-il in-gi menyu-ga mweoyeyo?", "Je-il in-gi ineun yo-ri-ga mueoshimnikka?", "Yeogi je-il inn-geo mweoyeyo?"], "translations":["Most popular menu-topic what-is-polite?", "Most popular-is dish-topic what-formal?", "Here most popular-thing what? (casual)"], "notes":"인기 (In-gi) = popular. 대표 메뉴 (Daepyo menyu) = signature/representative dish. 이집 뭐가 맛있어요? (Ijip mwoga massisseoyo? — 'what's delicious at this place?') is very colloquial and often gets the most honest answer." },
  { "d":3, "prompt":"Accept a server's dish recommendation.", "answers":["Ne, geugeol-lo halkgeyo!", "Ne, geugeol-lo butakhabnida!", "Geugeol-lo jwo!"], "translations":["Yes, that-as will-do-polite! (yes, I'll have that!)", "Yes, that-as I-request-formal!", "That-as give! (casual)"], "notes":"그걸로 할게요 (Geugeol-lo halkgeyo) = 'I'll go with that one' — one of the most useful ordering phrases in Korean. 추천해 주셔서 감사해요 (Chucheon-hae jushyeoseo gamsahaeyo — 'thank you for the recommendation') is a warm extra." },
  { "d":3, "prompt":"Say you'll pay separately.", "answers":["Ttareo ttareo gyesan halkgeyo", "Gak-ja gyesan hagetseumnida", "Ttareo ttareo gyesan hae"], "translations":["Separately separately pay will-polite (we'll pay separately)", "Each-person pay will-formal", "Separately separately pay (casual)"], "notes":"따로 (Ttaro) = separately. 각자 (Gakja) = each person. 더치페이 (Dochi pe-i — Dutch pay) is a growing concept, especially among younger Koreans. 1/N으로 나누어 주세요 (Il-bun-eui en-euro nanueo juseyo — 'please split it N ways') works in many restaurants." },
  { "d":3, "prompt":"The food is wrong. Politely say so.", "answers":["Joesonghaeyo, jeo-ge jumunhan geon anin geot gatayo", "Sillyehamnida, jeo-ui jumun-gwa dareun geot gatseumnida", "I geo ana, jeo igo jumun mot haesseo"], "translations":["Sorry, me-to ordered-thing not-is seems-polite", "Excuse-me, my order-with different-thing seems-formal", "This not-right, I this ordered not-did (casual)"], "notes":"주문한 거 맞아요? (Jumunhan geo majayo? — 'is this what I ordered?') or simply pointing and saying 이게 아닌 것 같아요 (I-ge anin geot gatayo — 'I think this isn't right') works well. Always use gentle, uncertain phrasing — don't accuse directly." },
  { "d":3, "prompt":"Compliment the food as you leave.", "answers":["Eumsigeul jinjja massissotseoyo!", "Jeongmal masitseumnida, gomapsseumnida!", "Jinjja massisseotseo, ddo olgeyo!"], "translations":["Food really delicious-was-polite! (the food was really delicious!)", "Really delicious-formal, thank-you-formal!", "Really delicious-was, again will-come! (casual)"], "notes":"잘 먹었습니다 (Jal meogeotsseumnida — 'I ate well') is the essential closing phrase — always say this when leaving a restaurant or after being hosted. It's culturally important and the equivalent of 'thank you for the meal.'" },
  { "d":4, "prompt":"Ask about allergens — you're allergic to nuts.", "answers":["Gyeonggwa-ryu allereugi isseoyo, i yo-ri-e isseoyo?", "Gyeonggwa-ryu allereugi-ga isseo i yo-ri-e poham-doeotsseumnikka?", "Gyeonggwa-ryu allereugi isseo, i geo-e isseo?"], "translations":["Nuts allergy exist, this dish-in exist-polite?", "Nuts allergy-topic exist this dish-in included-formal?", "Nuts allergy exist, this one-in exist? (casual)"], "notes":"견과류 (Gyeonggwaryu) = tree nuts. 땅콩 (Ttangkong) = peanut. 알레르기 (Allereugi) = allergy. Korean cuisine uses sesame (참기름, Chamgireum), pine nuts (잣, Jat), and walnuts (호두, Hodu) — always specify which nut you're allergic to for clarity." },
  { "d":4, "prompt":"Compliment the chef and ask if they'll pass on the message.", "answers":["Eumsigeul jinjja massisseotseoyo! Jubang-e jeonhae juseyo", "Yo-ri-ga meossisseumnida! Jubangjangnimkke jeonhae butakhabnida", "Jinjja massisseotseo! Jubangnim-hante jeonhae jwo"], "translations":["Food really delicious-was! Kitchen-to convey give-please", "Dish excellent-formal! Chef-honorific-to convey I-request-formal", "Really delicious-was! Chef-to convey give (casual)"], "notes":"주방장 (Jubang-jang) = head chef. 요리사 (Yorisa) = cook/chef. 칭찬 전해 주세요 (Chingchan jeonhae juseyo — 'please pass on the compliment') is a lovely phrase. Korean chefs take pride deeply in their work — this gesture is genuinely appreciated." }
];
