window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["shopping"] = [
  { "d":1, "prompt":"Staff greets you. You're just browsing.", "answers":["Geuryang bogo isseoyo", "Geuryang bogo itsseumnida", "Geuryang bolgeyo"], "translations":["Just looking-am-polite (just browsing)", "Just looking-am-formal", "Just will-look (casual)"], "notes":"그냥 보고 있어요 (Geuryang bogo isseoyo — 'just looking') is the standard. 구경하는 중이에요 (Gugyeong-haneun jungeeyeyo — 'I'm just browsing around') is a longer natural alternative. Korean store staff are attentive but generally won't pressure you after you say this." },
  { "d":1, "prompt":"Ask how much something is.", "answers":["Eolma-yeyo?", "Gagyeok-i eolma-na doeseumnikka?", "Eolmaya?"], "translations":["How-much-is-polite? (how much is it?)", "Price-topic how-much will-be-formal?", "How-much? (casual)"], "notes":"얼마예요? (Eolmayeyo?) is the simplest, most natural price question. 가격 (Gagyeok) = price (formal). 값 (Gap) = price (informal). In most Korean stores, prices are tagged. In markets, bargaining (흥정, Heungjong) is expected — start with this question." },
  { "d":1, "prompt":"You decided to buy it.", "answers":["I geol-lo halkgeyo", "I geol-lo butakhabnida", "I geo jwo"], "translations":["This-as will-do-polite (I'll take this one)", "This-as I-request-formal", "This give (casual)"], "notes":"이걸로 할게요 (I geol-lo halkgeyo) = 'I'll go with this one' — a very natural purchasing phrase. 살게요 (Salgeyo — 'I'll buy it') is also completely natural. 이거 주세요 (I-geo juseyo — 'please give me this') is the simplest option." },
  { "d":1, "prompt":"The item is too small.", "answers":["Jogeumyo jakayo", "Jogeumyo jakseumnida", "Jogeumyo jak-eo"], "translations":["A-little small-polite (it's a little small)", "A-little small-formal", "A-little small (casual)"], "notes":"작다 (Jakda) = small. 너무 작아요 (Neomu jakayo — 'too small') or 작은 것 같아요 (Jakeun geot gatayo — 'it seems small') are natural. Korean sizing (한국 사이즈, Hanguk saijeu) can run smaller than European or American sizing — always try before buying." },
  { "d":1, "prompt":"The item is too big.", "answers":["Jogeumyo keoyeo", "Jogeumyo keoseumnida", "Jogeumyo keo"], "translations":["A-little big-polite (it's a little big)", "A-little big-formal", "A-little big (casual)"], "notes":"크다 (Keuda) = big. 너무 커요 (Neomu keoyo — 'too big'). Korean clothing sizes: XS, S, M, L, XL, XXL (same as international but can run small). For shoes: Korean sizes are in mm — e.g., 250 = 25cm = roughly US 7." },
  { "d":1, "prompt":"Ask if you can try it on.", "answers":["Ibo bwado doeyeyo?", "Ibo bwa-do doeseumnikka?", "Ibo bwado dweyo?"], "translations":["Wear-try-also okay-polite? (can I try it on?)", "Wear-try-also okay-formal?", "Wear-try okay? (casual)"], "notes":"입어 봐도 돼요? (Ibo bwado dwaeyo?) = 'may I try it on?' 탈의실 (Tarbisil) = fitting room/changing room. 피팅룸 (Fitting-rum) is also widely understood. Korean stores generally allow try-ons — but smaller boutiques may ask you to purchase first." },
  { "d":1, "prompt":"It fits perfectly!", "answers":["Jinjja jal matayo!", "Jeongmal jal mannseumnida!", "Jinjja jal ma-ja!"], "translations":["Really well fits-polite! (it fits perfectly!)", "Really well fits-formal!", "Really well fits! (casual)"], "notes":"잘 맞아요 (Jal majayo) = it fits well. 딱 맞아요 (Ttak majayo — 'fits exactly/perfectly') is even more emphatic — 딱 (Ttak) means exactly/just right. 완벽해요 (Wanbyeokhaeyo — 'it's perfect!') works for expressing overall delight." },
  { "d":2, "prompt":"Ask for a different color.", "answers":["Dareun saek-kkal isseoyo?", "Dareun saek-kkal-euro itsseumnikka?", "Dareun saek-kkal isseo?"], "translations":["Different color exist-polite?", "Different color-as exist-formal?", "Different color exist? (casual)"], "notes":"색깔 (Saek-kkal) = color. Common Korean colors: 빨간 (Ppalgan — red), 파란 (Paran — blue), 검은 (Geomeun — black), 흰 (Huin — white), 노란 (Noran — yellow), 초록 (Chorok — green), 보라 (Bora — purple), 분홍 (Bunhong — pink)." },
  { "d":2, "prompt":"Ask for a bigger size.", "answers":["Deo keun size isseoyo?", "Deo keun saijeu-ga itsseumnikka?", "Deo keun size isseo?"], "translations":["More big size exist-polite?", "More big size-topic exist-formal?", "More big size exist? (casual)"], "notes":"더 큰 (Deo keun) = bigger. 한 사이즈 위 (Han saijeu wi — 'one size up') is very precise. Korean fashion brands often have their own sizing — S/M/L/XL/XXL, but also 44/55/66/77 (especially for women's clothing — these are old Korean size numbers)." },
  { "d":2, "prompt":"Ask if there's a sale on.", "answers":["Seillo haeyo?", "Hallein-i issseumnikka?", "Seillo hae?"], "translations":["Sale do-polite? (is there a sale?)", "Discount-topic exist-formal?", "Sale? (casual)"], "notes":"세일 (Seillo) = sale (from English). 할인 (Halin) = discount. 얼마 할인돼요? (Eolma halin dwaeyo? — 'how much discount?'). Major Korean sale periods: 블랙프라이데이 (Black Friday), end-of-season sales, and 쿠팡/네이버 online deals are extremely competitive." },
  { "d":2, "prompt":"Ask for gift wrapping.", "answers":["Seonmul pojang hae juseyo", "Seonmul pojang butakhabnida", "Seonmul pojang hae jwo"], "translations":["Gift wrapping do give-please", "Gift wrapping I-request-formal", "Gift wrapping do (casual)"], "notes":"선물 (Seonmul) = gift. 포장 (Pojang) = packaging/wrapping. 예쁘게 싸주세요 (Yeppuge ssajuseyo — 'please wrap it beautifully') — Koreans place high value on beautiful gift presentation. Wrapping is often done with elegant paper and ribbons, especially for Chuseok (추석) and Seollal (설날) gifts." },
  { "d":2, "prompt":"Staff says they're sold out. Respond.", "answers":["Ah, geureotgun-yo. Daesin hal geotsseumnikka?", "Ah, eomnaemnikka. Eonjeyyoa-lo deul eoreayo?", "Ah, eomne. Eonje deu-reo?"], "translations":["Ah, I see. Alternative have-formal?", "Ah, none-formal. When come-in-formal?", "Ah, none. When come-in? (casual)"], "notes":"없어요 (Eopseoyo) = doesn't exist / sold out. 품절 (Pumjeol) = sold out (official term on tags). 재입고 (Jaibgo) = restock. 언제 재입고 되나요? (Eonje jaibgo doenayo? — 'when will it be restocked?') is useful if you really want the item." },
  { "d":2, "prompt":"Ask if they can order it for you.", "answers":["Jumun hae jusilsu isseoyo?", "Jumun hae jusilsu itsseumnikka?", "Jumun hae jwo?"], "translations":["Order do could-give-polite?", "Order do could-give-formal?", "Order do-give? (casual)"], "notes":"주문 (Jumun) = order. 맞춤 제작 (Matchum jejak) = custom order. 온라인으로 주문할 수 있어요 (Onlaine-euro jumuhal su isseoyo — 'can order online') — most Korean brands have excellent online shops. Naver Shopping is Korea's dominant shopping portal." },
  { "d":3, "prompt":"Ask about the return policy.", "answers":["Gyohwan jeong-chaeg-i eotteoke doeoyo?", "Banpum jeong-chaeg-i eoddeon-ga-yo?", "Gyohwan dweyo?"], "translations":["Exchange policy-topic how-is-polite?", "Return policy-topic what-is-polite?", "Exchange okay? (casual)"], "notes":"교환 (Gyohwan) = exchange. 반품 (Banpum) = return/refund. 환불 (Hwanbul) = refund. In Korea, returns are generally allowed within 7–30 days with receipt. 영수증 보관하세요 (Yeongsujung bogwanhaseyo — 'keep your receipt') — it's legally required for exchanges." },
  { "d":3, "prompt":"Ask what material the item is made of.", "answers":["Museun sojae-yeyo?", "Eoddeon sojaero mandeureotsseumnikka?", "Museun sojae ya?"], "translations":["What material-is-polite?", "What material-made-formal?", "What material? (casual)"], "notes":"소재 (Sojae) = material/fabric. 재질 (Jaejil) = composition. Common materials: 면 (Myeon — cotton), 폴리에스터 (Polieseuteo — polyester), 가죽 (Gajuk — leather), 실크 (Silkeu — silk), 울 (Ul — wool). Check labels: 혼방 (Honbang) = blend." },
  { "d":3, "prompt":"Ask for a discount if buying multiple items.", "answers":["Yeoreo gae sa-myeon halin dweyo?", "Daeryang gumae si halin-i itsseumnikka?", "Yeoreo gae sa-myeon ssa-ge hae jwo"], "translations":["Multiple buy-if discount okay-polite?", "Bulk purchase-at discount-topic exist-formal?", "Multiple buy-if cheap-make give (casual)"], "notes":"여러 개 (Yeoreo gae) = multiple items. 할인 (Halin) = discount. 묶음 할인 (Mukeum halin) = bundle discount. In Korean markets (시장, Sijang) this is expected and part of the shopping experience — don't be shy. 좀 싸게 해주세요 (Jom ssage haejuseyo — 'please make it a bit cheaper') is direct and natural." },
  { "d":3, "prompt":"Exchange an item — wrong size.", "answers":["Size gyohwan hae juseyo", "Size gyohwan butakhabnida", "Size gyohwan hae jwo"], "translations":["Size exchange do give-please", "Size exchange I-request-formal", "Size exchange do (casual)"], "notes":"사이즈 교환 (Saijeu gyohwan) = size exchange. 영수증 (Yeongsujung) = receipt — always bring it. 구매하셨던 상품이요? (Gumae-hashyeotseon sangpumieyo? — 'the item you purchased?') is what staff will ask. Exchanges in Korean stores are generally smooth if you have the receipt." },
  { "d":4, "prompt":"Ask for a gift receipt.", "answers":["Seonmul yeongsujung juseyo", "Gyohwan-yong yeongsujung butakhabnida", "Seonmul yeongsujung jwo"], "translations":["Gift receipt give-please", "Exchange-use receipt I-request-formal", "Gift receipt give (casual)"], "notes":"선물용 영수증 (Seonmulyong yeongsujung) = gift receipt. 교환 영수증 (Gyohwan yeongsujung) = exchange receipt. Korean gift culture is strong — presentation and thoughtful gifting matter deeply. Receipts for gifts are common for expensive items (화장품 Hwajangpum = cosmetics, 전자기기 Jeonja-gigi = electronics)." },
  { "d":4, "prompt":"Complain that the item broke after one use and ask for a refund.", "answers":["Han beon sseotseonunde gojjang nasso, hwanbul hae juseyo", "Han beon saseundeyo geoljham-i isseo hwanbul butakhabnida", "Han beon ssotseo gojjang nasso, hwanbul hae jwo"], "translations":["One time used-but broke, refund give-please", "One time used-but defect-is refund I-request-formal", "One time used-and broke, refund give (casual)"], "notes":"환불 (Hwanbul) = refund. 불량품 (Bullyangpum) = defective product. 고장 (Gojjang) = breakdown/malfunction. Under Korea's consumer protection law (소비자 기본법), defective products can be returned within a reasonable period. Be firm but polite — Korean service culture takes quality complaints seriously." }
];
