window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["small_talk"] = [
  { "d":1, "prompt":"Ask how someone is (casual).", "answers":["Jal jinaesseoyo?", "Eotteoke jinaeshimnikka?", "Jal jinae?"], "translations":["Well lived-polite? (have you been well?)", "How living-formal?", "Well living? (casual)"], "notes":"잘 지내셨어요? (Jal jinaesseoyo?) implies time has passed since you last met. Unlike English 'how are you', Koreans may genuinely answer this — it's not purely rhetorical. Asking shows real care." },
  { "d":1, "prompt":"Reply that everything is great.", "answers":["Jal jinaesseoyo!", "Deokbune jal issseumnida!", "Jal jinae, gomawo!"], "translations":["Well lived-polite! (I've been well!)", "Thanks-to-you well am-formal! (I'm well, thanks to you!)", "Well living, grateful! (casual)"], "notes":"덕분에 (Deokbune — 'thanks to you') is a beautifully Korean response — implying the other person's goodwill contributed to your wellbeing. Far warmer than a plain 'I'm fine.' Koreans use it genuinely." },
  { "d":1, "prompt":"Say it's very hot today.", "answers":["Oneul Nar-ssi jinjja deowoyo!", "Oneul sangdanghi deopseumnida!", "Jinjja deo!"], "translations":["Today weather really hot-polite! (it's really hot today!)", "Today considerably hot-formal!", "Really hot! (casual)"], "notes":"진짜 (Jinjja) = really/truly (casual intensifier, very common). 상당히 (Sangdanghi) = considerably (formal). 날씨 (Nal-ssi) = weather. Weather is a major Korean small talk topic — especially summer heat, which Koreans discuss passionately." },
  { "d":1, "prompt":"Say the weather is beautiful.", "answers":["Nal-ssi jinjja joahayo!", "Oneul nal-ssi meotjseumnida!", "Nal-ssi daebak-iya!"], "translations":["Weather really good-polite! (the weather is really nice!)", "Today weather splendid-formal!", "Weather awesome! (casual)"], "notes":"대박 (Daebak) is a very popular Korean exclamation meaning 'jackpot/awesome' — used for anything impressive or great. 멋지다 (Meotjida) = splendid/cool. Korean has wonderfully expressive weather vocabulary." },
  { "d":1, "prompt":"Say you're very hungry.", "answers":["Bae-ga jinjja gopaayo!", "Sangdanghi baegopseumnida!", "Bae gopa jukgesseo!"], "translations":["Stomach-topic really hungry-polite! (I'm really hungry!)", "Considerably hungry-formal!", "Stomach hungry dying! (I'm starving, casual)"], "notes":"배고파 죽겠어 (Bae gopa jukgesseo — 'dying of hunger') is a classic Korean hyperbole. 죽겠다 (Jukgesseo — 'I could die') is used constantly for hunger, tiredness, boredom — it's expressive, never literal." },
  { "d":1, "prompt":"Say you're tired.", "answers":["Jinjja pigonaeseoyo", "Sangdanghi pigonaesumnida", "Jinjja pikon-hae / Jukgesseo"], "translations":["Really tired-polite (I'm really tired)", "Considerably tired-formal", "Really tired / dying (I'm dead tired, casual)"], "notes":"피곤해요 (Pigonhaeyo) = I'm tired. Adding 죽겠어 (Jukgesseo — 'could die') makes it more expressive: 피곤해 죽겠어 (I'm so tired I could die). Very common and dramatic — Koreans use this phrase constantly." },
  { "d":1, "prompt":"Agree enthusiastically.", "answers":["Majayo!", "Geureomnida!", "Macha!"], "translations":["Right-polite! (that's right!)", "That's right-formal!", "Right! (casual)"], "notes":"맞아요 (Majayo) = that's right! 그렇습니다 (Geureomnida) is formal agreement. 맞아! (Macha!) is very casual and enthusiastic. Koreans show agreement often during conversation — 네네 (Ne-ne), 맞아맞아 (Right right) signals active listening." },
  { "d":1, "prompt":"Express surprise.", "answers":["Eojjeoke yo!", "Aisseumnikka?", "Daebak!"], "translations":["How-so-polite! (how is that possible?!)", "Really-formal? (is that so?!)", "Jackpot! (awesome / wow!)"], "notes":"대박! (Daebak!) is the most popular Korean exclamation — literally 'jackpot' but means 'wow/no way/amazing.' 어떻게요! (Eotteoke-yo!) expresses disbelief. 진짜요? (Jinjjayo? — 'Really?!') is also very natural for surprise." },
  { "d":1, "prompt":"Say you don't know.", "answers":["Moreugesseosseoyo", "Moreugesseumnida", "Molla / Mol-la-yo"], "translations":["Don't-know-would-polite (I'm not sure / I don't know)", "Don't-know-formal", "Don't know (casual)"], "notes":"모르겠어요 (Moreugesseosseoyo) has the -겠 softener — 'I'm not sure I know.' More casual: 모르겠는데요 (Moreugenneundeyo — 'I'm not sure, actually'). 몰라 (Molla) is very casual and can sound abrupt with strangers." },
  { "d":1, "prompt":"Say something is very good.", "answers":["Jinjja joahayo!", "Jeongmal joetsseumnida!", "Daebak-iya!"], "translations":["Really good-polite! (it's really good!)", "Really good-formal!", "Jackpot! (awesome!, casual)"], "notes":"진짜 좋아요! (Jinjja joahayo!) = 'it's really good!' 대박이야 (Daebak-iya) is the casual slang version — 'jackpot/awesome.' Koreans are very expressive in showing appreciation and enthusiasm." },
  { "d":2, "prompt":"Ask what someone's been up to.", "answers":["Yojeum eotteoke jinaeseyo?", "Yojeum eotteoke jinaeshimnikka?", "Yojeum mwo hae?"], "translations":["Recently how living-polite?", "Recently how living-formal?", "Recently what doing? (casual)"], "notes":"요즘 (Yojeum) = recently/lately. 어떻게 지내세요? (Eotteoke jinaeshaeyo?) is the most natural 'what have you been up to?' Koreans often add 어떠세요? (Eotteo-seyo? — how are things?) as a warm follow-up." },
  { "d":2, "prompt":"Say you've been busy.", "answers":["Yojeum jinjja bappayo", "Yojeum sangdanghi bapseumnida", "Yojeum jinjja bappa / Jukgesseo"], "translations":["Recently really busy-polite (I've been really busy)", "Recently considerably busy-formal", "Recently really busy / dying (I'm swamped, casual)"], "notes":"바빠요 (Bappayo) = I'm busy. 바빠 죽겠어 (Bappa jukgesseo — 'so busy I could die') is the hyperbolic casual version. Koreans wear busyness as a badge of honour — admitting you're extremely busy is very relatable." },
  { "d":2, "prompt":"Say the food was delicious.", "answers":["Jinjja massisseoyo!", "Jeongmal masitseumnida!", "Daebak massisseo!"], "translations":["Really delicious-polite! (it was really delicious!)", "Really delicious-formal!", "Jackpot delicious! (it was amazingly good!, casual)"], "notes":"맛있어요 (Massisseoyo) = delicious. 맛있다! (Masitda!) is the casual exclamation. Koreans are passionate about food — genuine enthusiasm for a meal is always the right social move. 맛집 (Matjip) = a delicious/famous restaurant (a word you'll use a lot in Korea)." },
  { "d":2, "prompt":"Say you love it here.", "answers":["Yeogi jinjja joahayo!", "Yeogi jeongmal joatsseumnida!", "Yeogi daebak-iya!"], "translations":["Here really like-polite! (I really love it here!)", "Here really good-formal!", "Here jackpot! (this place is awesome!, casual)"], "notes":"여기 정말 좋아요! (Yeogi jeongmal joahayo!) is simple and heartfelt. Koreans will be visibly pleased to hear this. Adding 계속 있고 싶어요 (Gyesok itsgo sipeoyo — 'I want to stay forever') is an even bigger compliment." },
  { "d":2, "prompt":"React to good news someone shares.", "answers":["Jinjja yo?! Jinja joahayo!", "Jeongmal itsseumnikka?! Chukahamnida!", "Daebak! Jinja?!"], "translations":["Really?! Really good-polite! (no way! That's great!)", "Really-formal?! Congratulations-formal!", "Jackpot! Really?! (wow, seriously?!, casual)"], "notes":"축하합니다 (Chukahamnida) = congratulations (formal). 정말이요?! (Jeongmalyo?! — 'Really?!') shows genuine excitement. Koreans love enthusiastic reactions to good news — being understated can seem cold." },
  { "d":2, "prompt":"Say something is very cheap.", "answers":["Jinjja ssayo!", "Sangdanghi ssamnida!", "Daebak ssayo!"], "translations":["Really cheap-polite! (it's really cheap!)", "Considerably cheap-formal!", "Jackpot cheap! (amazingly cheap!, casual)"], "notes":"싸다 (Ssada) = cheap/inexpensive. 저렴하다 (Jeoryomhada) is more formal/polished. 엄청 싸요! (Eomcheong ssayo! — 'incredibly cheap!') is a common exclamation. Shopping in Korea can be great value — Korean markets especially." },
  { "d":2, "prompt":"Ask if they've tried local food.", "answers":["Hanguk eumsik meogeo bwasseoyo?", "Hanguk eumsik deuryeo bwashyeotseumnikka?", "Hanguk eumsik meogeo bwasseo?"], "translations":["Korean food eat-try-polite? (have you tried Korean food?)", "Korean food eat-try-honorific-formal?", "Korean food eat-try? (casual)"], "notes":"먹어 봤어요? (Meogeo bwasseoyo? — 'have you tried eating?') uses the -아/어 보다 pattern ('try doing'). 한국 음식 (Hanguk eumsik) = Korean food. Asking this opens incredibly enthusiastic conversations — food is central to Korean culture." },
  { "d":3, "prompt":"Say you've been exploring the city.", "answers":["Saeok-eul neolri danyeosseoyo", "Saeok-eul guhaseuk-haetsseumnida", "Saeok jinjja meokkeodanyeotseo"], "translations":["City-obj widely toured-polite (explored the city widely)", "City-obj sightseeing-did-formal", "City really ate-up toured (devoured the city, casual)"], "notes":"돌아다니다 (Doradanida) = to wander around. 도시를 쭉 돌아다녔어요 (Dosireul jjuk doradanyeotseoyo — 'wandered all around the city') is very natural. 먹으러 다녔어요 (Meogeureo danyeotseoyo — 'went around eating') is the most honest Korean tour statement." },
  { "d":3, "prompt":"Ask for a local tip nobody tells tourists.", "answers":["Yeogi hyeonji-in-man aneun got isseoyo?", "Gwangwanggaeg-i moreuneun got issseumnikka?", "Yeogi jinjja hyeonji matjip eodisseo?"], "translations":["Here local-only know-place exist-polite? (is there a local-only spot here?)", "Tourist not-know-place exist-formal?", "Here really local restaurant where? (casual)"], "notes":"현지인 (Hyeonjiin) = local person. 맛집 (Matjip) = famous delicious restaurant — one of the most important Korean words for food exploration. Koreans love sharing hidden gems and will often be more enthusiastic than you expected." },
  { "d":3, "prompt":"Say you prefer it here over where you live.", "answers":["Soljikhie jeoneun yeogi deo joahayo", "Soljikhie jeogeun yeogi deo joatsseumnida", "Yagsshigi yeogi deo joayo"], "translations":["Honestly I here more like-polite (honestly I like it here more)", "Honestly I here more good-formal", "Honestly here more good (casual)"], "notes":"솔직히 (Soljikhie) = honestly. 솔직히 말하면 (Soljikhie marhamyeon — 'to be honest') is a great opener. Koreans respond very warmly when foreigners say they prefer Korea to their home — it's a genuine compliment to the culture." },
  { "d":3, "prompt":"React to something amazing you just saw.", "answers":["Jinjja nollawosseoyo!", "Jeongmal gyeongikseumnida!", "Daebak! Micho-seo!"], "translations":["Really surprised-polite! (I was really amazed!)", "Really marvellous-formal!", "Jackpot! Crazy! (casual)"], "notes":"미쳤어 (Micheosseo — 'I went crazy/I'm blown away') is the ultra-casual version of amazement — very common among younger Koreans. 경이롭다 (Gyeongiropda) = marvellous/wonderful. 장관이에요 (Janggwanieyo) = spectacular view." },
  { "d":4, "prompt":"Compare something to your home country.", "answers":["Jeohuighuk-gwa jinjja dareunjiman yeogi deo joahayo", "Boguk-gwa sangdanghi dareumyeo yeogi sekeom-iseumnida", "Jinjja dallayo geunde yeogi-ga deo joayo"], "translations":["My-country-with really different-but here more like-polite", "Home-country-with considerably different here charm-is-formal", "Really different but here-subject more good (casual)"], "notes":"볼수록 매력 있어요 (Bolsurok maeryeok isseoyo — 'the more you look, the more charm it has') is a beautiful Korean expression. Koreans appreciate nuanced cultural comparisons — showing genuine interest in differences rather than judging is always warmly received." },
  { "d":4, "prompt":"Have a genuine exchange about cultural differences.", "answers":["Saram-deul-i eomcheong dajeonghae-seo jinjja nolrapseoyo", "Munhwa-ga sangdanghi dareo measseoyo", "Hankuk-saram-deul jinjja ppari ppari-haeyo!"], "translations":["People really warm-so really surprising-polite (the warmth of people really surprised me)", "Culture considerably different interesting-formal", "Korean-people really hurry hurry! (Koreans are really so speedy!, casual)"], "notes":"빨리빨리 (Ppalli ppalli — 'hurry hurry') is a famous Korean cultural concept describing the fast-paced, get-it-done-now attitude. Koreans are proud of their efficiency and will laugh and agree warmly when you notice it. It's one of Korea's most self-aware cultural exports." }
];
