window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["social"] = [
  { "d":1, "prompt":"Say good luck!", "answers":["Hwaiting!", "Jamshig isseoyo!", "Hwaiting! Janhal su isseo!"], "translations":["Fighting! (you can do it! — Korean encouragement)", "Confidence exist-polite! (have confidence!)", "Fighting! Can do well! (casual)"], "notes":"화이팅! (Hwaiting!) — from English 'fighting' — is the signature Korean encouragement cheer. Used constantly in sports, exams, job interviews, and any challenging situation. 잘 될 거예요! (Jal doel geoyeyo! — 'it'll go well!') is a warm alternative. Koreans yell 화이팅 with genuine enthusiasm." },
  { "d":1, "prompt":"Say me too / same here.", "answers":["Jeo-do yo!", "Jeong-mal geuryeoyo!", "Na-do!"], "translations":["I-also-polite! (me too!)", "Really-like-that-polite! (exactly/same here!)", "I-also! (casual)"], "notes":"저도요 (Jeodo-yo) = 'me too' (polite). 나도 (Nado) = 'me too' (casual). 저도 똑같아요 (Jeodo ttokgatayo — 'I'm exactly the same') for emphasis. Korean agreement is often expressed enthusiastically — 맞아요 맞아요 (Majayo majayo — 'right, right') shows you're fully engaged." },
  { "d":1, "prompt":"Agree enthusiastically: Exactly! That's right!", "answers":["Majayo! Jeongmal geuryeoyo!", "Geeureomnida! Majayo!", "Macha! Jinjja geuryeo!"], "translations":["Right-polite! Really-like-that-polite! (exactly! that's right!)", "That's-right-formal! Right-polite!", "Right! Really-like-that! (casual)"], "notes":"맞아요! (Majayo!) = 'right!/correct!' 그렇죠! (Geurejjyo! — 'isn't that so?') seeks agreement. 정말요! (Jeongmalyo! — 'really?/exactly!') 맞아 맞아 (Macha macha — 'right right') shows enthusiastic agreement during conversation — Koreans use this as active listening signals." },
  { "d":1, "prompt":"Say that's a great idea!", "answers":["Joeun aidi-a-yo!", "Jeongmal joeun saenggang-imnida!", "Joeun aidi-a! Daebak!"], "translations":["Good idea-polite! (that's a good idea!)", "Really good thought-formal! (really great idea!)", "Good idea! Jackpot! (casual)"], "notes":"아이디어 (Aidi-a) = idea (English loanword). 생각 (Saenggang) = thought/idea (Korean). 그거 정말 좋은 생각이에요 (Geugo jeongmal joeun saenggangiyeyo — 'that's really a great thought') is the full natural version. Koreans enjoy collaborative brainstorming and enthusiastically building on ideas." },
  { "d":1, "prompt":"Compliment someone who looks nice today.", "answers":["Oneul jinjja meotyeosseoyo!", "Oneul sangdanghi gogeupeureoushimnikka!", "Oneul jinjja eepeoyo!"], "translations":["Today really cool/stylish-polite! (you look really cool today!)", "Today considerably elegant-formal!", "Today really pretty/handsome! (casual)"], "notes":"멋있어요 (Meossisseoyo) = cool/stylish (for anyone). 예뻐요 (Yeppeoyo) = pretty (for women). 잘 생겼어요 (Jal saengyeotseoyo) = handsome (for men). Korean compliment culture is warm and direct — appearance compliments are common and generally very well received, especially among younger Koreans." },
  { "d":1, "prompt":"Someone made you laugh. React.", "answers":["Jinjja usgyeo-yo! Kkakkal-kkakkal!", "Jinjja usgyeo-sseumnida!", "Kkakkal-kkakkal! Jinjja usgyeo!"], "translations":["Really funny-polite! Hahaha!", "Really funny-formal!", "Hahaha! Really funny! (casual)"], "notes":"웃기다 (Usgida) = funny/amusing. 크크크 (Keukeukeu) is the Korean written laugh (like lol). ㅋㅋㅋ (Keukeukeu) in text = lol/haha. 빵 터졌어요 (Ppang teojyeotseoyo — 'it exploded!') means you burst out laughing. Koreans love humor and genuinely react with full-body laughter." },
  { "d":2, "prompt":"Say I'm so happy to meet you.", "answers":["Mannaeseo jinjja bangapayo!", "Mannaeotseo jeongmal bangapseumnida!", "Mannaeseo jinjja bangawo!"], "translations":["Met-so really glad-polite! (so happy to meet you!)", "Met-so really glad-formal!", "Met-so really glad! (casual)"], "notes":"만나서 반가워요 (Mannaeseo bangapayo) = nice to meet you. 만나서 정말 좋아요 (Mannaeseo jeongmal joahayo — 'it's really great to meet you') adds extra warmth. Koreans appreciate sincere first-meeting enthusiasm — it sets a warm, open tone for the relationship." },
  { "d":2, "prompt":"Say don't worry about it.", "answers":["Geokjeong maseyo", "Geokjeong haji mashipsio", "Geokjeong haji ma"], "translations":["Worry don't-polite (don't worry)", "Worry do don't-formal", "Worry do don't (casual)"], "notes":"걱정 마세요 (Geokjeong maseyo) = 'don't worry.' 괜찮을 거예요 (Gwaenchan-eul geoyeyo — 'it'll be fine') is warm reassurance. 다 잘 될 거예요 (Da jal doel geoyeyo — 'everything will go well') is the optimistic version. Korean culture values encouraging words — give them generously." },
  { "d":2, "prompt":"Say I really enjoyed today.", "answers":["Oneul jinjja jeulgeowo-tsseumnida!", "Oneul sangdanghi jeulgeowo-tsseumnida!", "Oneul jinjja jeulgeowo-tsseosseo!"], "translations":["Today really enjoyable-was-polite!", "Today considerably enjoyable-was-formal!", "Today really enjoyable-was! (casual)"], "notes":"즐거웠어요 (Jeulgeoweosseoyo) = 'it was enjoyable.' 오늘 진짜 재미있었어요 (Oneul jinjja jaemiitseosseoyo — 'today was really fun') is the casual version. 덕분에 즐거운 시간이었어요 (Deokbune julgeoueun siganieosseoyo — 'it was enjoyable time thanks to you') is warm and specific." },
  { "d":2, "prompt":"Someone shares good news. React with excitement.", "answers":["Jinjja yo?! Jinjja joahayo!", "Jeongmal itsseumnikka?! Chukahamnida!", "Daebak! Jinjja?!"], "translations":["Really?! Really good-polite! (no way! that's amazing!)", "Really-formal?! Congratulations-formal!", "Jackpot! Really?! (casual)"], "notes":"축하해요! (Chukahaeyo! — 'congratulations!') is the key response to good news. 대박! (Daebak!) for exciting news. 진짜요? (Jinjjayo? — 'really?!') expresses genuine surprise. Koreans match your energy when you bring good news — be enthusiastic and it will be reciprocated fully." },
  { "d":2, "prompt":"Say you're so kind to someone who did something nice.", "answers":["Jinjja chimchan-haseyo!", "Sangdanghi chinjeol-haseumnida!", "Jinjja chimchan-hae!"], "translations":["Really kind-honorific-polite! (you're really kind!)", "Considerably kind-honorific-formal!", "Really kind! (casual)"], "notes":"친절하다 (Chinjeolhada) = kind/thoughtful. 착하다 (Chakhada) = good-natured/kind. 마음이 따뜻해요 (Maeumi ttadeuthaeyo — 'your heart is warm') is a beautiful Korean compliment — 마음 (Maeum — heart/mind) compliments are deeply meaningful in Korea." },
  { "d":2, "prompt":"Encourage someone nervous before a presentation.", "answers":["Hwaiting! Jal hal su isseo-yo!", "Jamshig isseoyo! Chamshinneul balhwi haseyo!", "Hwaiting! Janghal su isseo!"], "translations":["Fighting! Can do well-polite! (you can do it!)", "Confidence-have! True-self-obj demonstrate-honorific! (be your best!)", "Fighting! Can do great! (casual)"], "notes":"화이팅! (Hwaiting!) is the essential encouragement cry. 잘 할 수 있어요! (Jal hal su isseoyo! — 'you can do it well!') is sincere. 믿어요! (Mideo-yo! — 'I believe in you!') is simple and powerful. Koreans give encouragement loudly and genuinely — your enthusiasm will boost them." },
  { "d":3, "prompt":"Say take care of yourself.", "answers":["Momjo-sim haseyo", "Momjo-sim hashipsio", "Momjo-sim hae"], "translations":["Body-careful do-polite (take care of yourself)", "Body-careful do-formal", "Body-careful do (casual)"], "notes":"몸 조심하세요 (Momjosim-haseyo) = 'take care of yourself/your body.' 건강하세요 (Geongang-haseyo — 'be healthy') is also very commonly used as a warm farewell. 잘 지내세요 (Jal jinaeshaeyo — 'live well') is another warm goodbye. Koreans care genuinely about each other's health." },
  { "d":3, "prompt":"Say let's do this again!", "answers":["Ddo hamkke ha-yo!", "Ddo gachi hapsida!", "Ddo hamkke haja!"], "translations":["Again together do-polite! (let's do this together again!)", "Again together do-formal-let's!", "Again together do! (casual)"], "notes":"또 만나요 (Ddo mannayo — 'let's meet again') or 다음에 또 봐요 (Daeume ddo bwayo — 'let's meet again next time') are natural closings. 자주 봐요 (Jaju bwayo — 'let's see each other often') signals you genuinely enjoyed the time together — a very warm social closing." },
  { "d":3, "prompt":"Thank someone genuinely — beyond just thank you.", "answers":["Jinjja jinjja gamsahaeyo, maeum-eul da heun-deul-lyeo-tsseumnida", "Jeongmal gamsahamnida, eomcheong dori usyeotseo-yo", "Jinjja gamsahaeyo, maeumi ddeodteowo-yo"], "translations":["Really really thank-you, heart-obj all moved-polite", "Really thank-you-formal, extremely helpful-was", "Really thank-you, heart-warm (casual)"], "notes":"마음이 따뜻해요 (Maeumi ttadeuthaeyo — 'my heart is warm') is a deeply Korean expression of genuine gratitude. 진심으로 감사해요 (Jinsim-euro gamsahaeyo — 'from my true heart, thank you') is the most heartfelt. Koreans respond very deeply to sincere, specific gratitude — it creates lasting bonds." },
  { "d":3, "prompt":"Say I'm proud of you.", "answers":["Jinjja ja-rang-seureowo-yo!", "Sangdanghi ja-rang-seureowo-tsseumnida!", "Jinjja ja-rang-seureowo!"], "translations":["Really proud-polite! (I'm really proud of you!)", "Considerably proud-was-formal!", "Really proud! (casual)"], "notes":"자랑스럽다 (Jarangseureopda) = proud. 잘했어요! (Jalhaesseoyo! — 'you did well!') is often said together with pride. 대견해요 (Daegyeonhaeyo) = I'm impressed/proud (slightly different nuance — used by older to younger, like parent to child). Expressing pride openly is warm and valued in Korean culture." },
  { "d":4, "prompt":"Say I believe in you!", "answers":["Miteo-yo!", "Jamshig isseoyo!", "Miteo! Hal su isseo!"], "translations":["Believe-polite! (I believe in you!)", "Confidence-exist-polite! (have confidence!)", "Believe! Can do! (casual)"], "notes":"믿어요 (Mideo-yo) = 'I believe (in you).' 당신을 믿어요 (Dangsineul mideo-yo — 'I believe in you') is the explicit version. 넌 할 수 있어 (Neon hal su isseo — 'you can do it') is the casual pep talk. Expressing belief in someone is a very meaningful act in Korean culture — it's taken seriously and sincerely." },
  { "d":4, "prompt":"Make a self-deprecating joke about your language ability.", "answers":["Jeoneun hangugeo-ga gajang eolyeowo-yo!", "Hangugeo-ga je-il eolyeopdago saengganghaetsseumnida!", "Hangugeo-ga jinjja eolyeowo! Eojakdo molla-yo!"], "translations":["I-topic Korean-subject most difficult-polite! (Korean is hardest for me!)", "Korean-subject most difficult-I thought-formal!", "Korean really difficult! Don't-know-yet! (casual)"], "notes":"어렵다 (Eoryeopda) = difficult. 저는 아직 많이 부족해요 (Jeoneun ajik manhi bujokhaeyo — 'I'm still lacking a lot') is humble and very Korean. 한국어 천재 아니에요 (Hangugeo cheonjae anieyo — 'I'm no Korean genius') is a self-deprecating joke Koreans will warm to immediately." },
  { "d":4, "prompt":"Respond humbly to a compliment and return it.", "answers":["Andwaeyo, [ireum]-ssi-ga deo jalhaseyo!", "Gwado-ha-shin malsseum-i-seyo, [ireum]-ssi-ga deo jirye-baro-u-seyo!", "Andwae, ne-ga deo jalhaeyo!"], "translations":["No-way, [name]-polite-title more does-well-polite! (no way, [name] is better!)", "Exaggerated speech-formal, [name] more distinguished-formal!", "No-way, you more does-well! (casual)"], "notes":"과찬이세요 (Gwachan-iseyo — 'you flatter me / that's too much praise') is the classic Korean humble response to a compliment. Deflecting compliments and returning them is very culturally Korean. 아니에요, 훨씬 더 잘하세요 (Anieyo, hwolssin deo jalhaseyo — 'no, you're much better') is warm and instinctive." }
];
