window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["taxi"] = [
  { "d":1, "prompt":"You get in. Say where you're going.", "answers":["[Mokjeokji]-uro ga juseyo", "[Mokjeokji]-uro butakhabnida", "[Mokjeokji]-uro ga jwo"], "translations":["[Destination]-to go give-please (please go to [destination])", "[Destination]-to I-request-formal", "[Destination]-to go (casual)"], "notes":"목적지 (Mokjeokji) = destination. Just say the place name clearly: 명동으로 가주세요 (Myeongdong-euro gajuseyo — 'please go to Myeongdong'). KakaoTaxi (카카오택시) is the dominant ride-app — use it to set destination in Korean and show the driver your screen." },
  { "d":1, "prompt":"Say please stop here.", "answers":["Yeogi-seo seo juseyo", "Yeogi-seo jeong-geo butakhabnida", "Yeogi-seo seo jwo"], "translations":["Here-at stop give-please", "Here-at stop I-request-formal", "Here-at stop (casual)"], "notes":"여기서 세워 주세요 (Yeogi-seo sewo juseyo) is the standard. 여기요! (Yeogiyo!) can also get the driver's attention before giving instructions. Korean taxi drivers are generally very professional — clear, direct instructions work best." },
  { "d":1, "prompt":"Ask if they accept card.", "answers":["Kadeu doeo yo?", "Kadeu gyesan ganeunghasmikka?", "Kadeu dweyo?"], "translations":["Card okay-polite? (is card okay?)", "Card payment possible-formal?", "Card okay? (casual)"], "notes":"카드 (Kadeu) = card. Korean taxis almost universally accept cards — it's the default. KakaoTaxi charges automatically through the app so no payment discussion needed. 카드 단말기 (Kadeu danmalgi) = card reader/terminal." },
  { "d":1, "prompt":"Ask roughly how much the ride costs.", "answers":["Eolma na-ollkayo?", "Deukchige eolma-na doeseumnikka?", "Eolma ya?"], "translations":["How-much will-come-out-polite? (roughly how much?)", "Approximately how-much will-be-formal?", "How much? (casual)"], "notes":"얼마나 나올까요? (Eolmana naolkkayo?) = 'how much will it come to?' Korean taxis use meters (미터기, Miteogi). Base fare is around ₩4,800 (basic taxi) with additional per-km/time charges. Kakao shows the estimated fare upfront." },
  { "d":1, "prompt":"Ask how long the ride will take.", "answers":["Eolmana geollyeyo?", "Sigan-i eolma-na soyo-doesimnikka?", "Eolma geollyeo?"], "translations":["How-much will-take-polite? (how long will it take?)", "Time-topic how-much require-formal?", "How-long take? (casual)"], "notes":"걸리다 (Geollida) = to take (time). 교통 체증 (Gyotong chejung) = traffic congestion. Seoul traffic (특히 강남 Teuki Gangnam) can be notoriously bad during rush hours. Naver Maps and Kakao Maps show realistic travel-time estimates." },
  { "d":1, "prompt":"You've arrived. Pay and thank the driver.", "answers":["Da wasseyo! Gamsahaeyo, eolmayeyo?", "Do-chakhaetsseumnida. Gamsahamnida", "Da waatseo! Eolmayeyo?"], "translations":["Arrived! Thank-you, how-much-is-it?", "Arrived-formal. Thank-you-formal", "Arrived! How-much? (casual)"], "notes":"다 왔어요 (Da wasseoyo) = 'we've arrived.' Kakao Taxi payment is automatic — no need to ask price. For traditional taxis, 미터기 (Miteogi — meter) shows the amount. 수고하세요 (Sugo haseyo — 'take care/good work') is a warm farewell to drivers." },
  { "d":2, "prompt":"Say a little further ahead please.", "answers":["Jom deo ap-euro ga juseyo", "Jom deo ap-euro jinginhae juseyo", "Jom deo ap-euro ga jwo"], "translations":["A-bit more ahead-to go give-please", "A-bit more ahead-to proceed give-please (formal)", "A-bit more ahead-to go (casual)"], "notes":"앞으로 (Ap-euro) = forward/ahead. 조금 (Jogeum) = a little. 거기서 조금만 더 (Geogi-seo jogeumman deo — 'just a little more from there') is natural. Korean drivers respond well to calm, clear directional cues." },
  { "d":2, "prompt":"Say turn left.", "answers":["Jjo-geuro gaseo jwachoek-euro doraseo juseyo", "Jwachoek-euro hwan-hae juseyo", "Jwachoek-euro dora jwo"], "translations":["There-to going left-to turn give-please", "Left-to turn give-please (formal phrasing)", "Left-to turn give (casual)"], "notes":"좌측 (Jwachoek) = left side (formal). 왼쪽 (Woenjjok) = left (everyday). 우측/오른쪽 (Ucheuk/Oreunjjok) = right. Koreans also give landmark-based directions: 저기 편의점 지나서 좌회전 (After that convenience store, turn left) — very common." },
  { "d":2, "prompt":"Say turn right.", "answers":["Oreunjjok-euro hwan-hae juseyo", "Ucheuk-euro hwan-hae juseyo", "Oreunjjok-euro dora jwo"], "translations":["Right-to turn give-please", "Right-side-to turn give-please (formal)", "Right-to turn give (casual)"], "notes":"오른쪽 (Oreunjjok) = right. 우회전 (Uhoejeon) = right turn (used on road signs). GPS apps like Naver Maps or Kakao Maps announce turns in Korean — a great way to hear the vocabulary in action during your ride." },
  { "d":2, "prompt":"Say go straight ahead.", "answers":["Jikjin-euro ga juseyo", "Jikjin-euro butakhabnida", "Jikjin-euro ga jwo"], "translations":["Straight-to go give-please", "Straight I-request-formal", "Straight go (casual)"], "notes":"직진 (Jikjin) = go straight (road term). 쭉 가주세요 (Jjuk gajuseyo — 'just keep going') is also very natural. 계속 (Gyesok) = continue/keep going. These are the words you'll hear Korean GPS navigation use." },
  { "d":2, "prompt":"Driver says cash only. Acknowledge.", "answers":["Ah, hyeon-geum-euro halgeyo", "Ah, hyeon-geum-euro gyesan hagetseumnida", "Ah, hyeon-geum isseo"], "translations":["Ah, cash-as will-do-polite (ah, I'll pay cash)", "Ah, cash-as pay will-formal", "Ah, cash exist (casual — ah I have cash)"], "notes":"현금 (Hyeongeum) = cash. Some older taxis are cash-only. It's always wise to carry some small bills (1만원, 5천원 — ₩10,000 and ₩5,000 notes). ATMs (ATM) are widely available near subway stations and convenience stores." },
  { "d":2, "prompt":"Ask for a receipt.", "answers":["Yeongsujung juseyo", "Yeongsujung butakhabnida", "Yeongsujung jwo"], "translations":["Receipt give-please", "Receipt I-request-formal", "Receipt give (casual)"], "notes":"영수증 (Yeongsujung) = receipt. Korean taxi receipts show trip details — very useful for expense claims. Kakao Taxi sends a digital receipt to your app automatically. For traditional taxis, ask before getting out as they may not offer one unprompted." },
  { "d":2, "prompt":"Ask the driver to drive more carefully.", "answers":["Jogeumyo cheoncheonhi gajuseyo", "Johom deo anjeonha-ge unjeong butakhabnida", "Jogeumyo cheoncheonhi ga jwo"], "translations":["A-little slowly go-give-please (please drive a little more slowly)", "A-bit more safely drive I-request-formal", "A-little slowly go (casual)"], "notes":"천천히 (Cheoncheonhi) = slowly. 안전하게 (Anjeonhage) = safely. Korean taxis can drive fast in cities. Saying this politely is completely fine — drivers are used to passenger requests and take them seriously. 조심해서 가주세요 (Josimhaeseo gajuseyo — 'please drive carefully') is also natural." },
  { "d":3, "prompt":"Ask the driver to use GPS / fastest route.", "answers":["Naebi-ro ppareun gil-ro ga juseyo", "Gajang ppareun gillo ga juseyo", "Naebi-ro ppareun gillo ga jwo"], "translations":["Navigation-by fastest route-by go give-please", "Fastest route-by go give-please", "Navigation-by fastest route-by go (casual)"], "notes":"내비 (Naebi) = navigation/GPS (from 내비게이션, Navigation). 빠른 길 (Ppareun gil) = fast route. 가장 빠른 길로 가주세요 (Gajang ppareun gillo gajuseyo — 'please take the fastest route') is clear and direct. Most Korean drivers already use Naver Maps or Kakao Maps." },
  { "d":3, "prompt":"Traffic is bad. Ask if there's another route.", "answers":["Gyotong-i jinjja makhyeosseoyo, dareun gilro isseoyo?", "Gyotong-i jinhwa-hae dareun nore-ga itsseumnikka?", "Jinjja maxhyeotseo, dareun gillo ga jwo"], "translations":["Traffic really blocked-polite, different route exist-polite?", "Traffic congested different path-topic exist-formal?", "Really blocked, different route-by go (casual)"], "notes":"막히다 (Makhida) = to be jammed/blocked (traffic). 교통 (Gyotong) = traffic. 우회 (Uhoe) = detour. Saying 막히는 거 같은데, 다른 길 없어요? (Makhineun geo gateunde, dareun gil eopseoyo? — 'seems like it's jammed, is there another way?') is very natural Korean." },
  { "d":3, "prompt":"Confirm you're going the right way.", "answers":["[Mokjeokji]-ro gago inneun geo majayo?", "[Mokjeokji]-ro ga-go isseumnikka?", "[Mokjeokji]-ro ganeun geo maje?"], "translations":["[Destination]-to going-is that right-polite?", "[Destination]-to going-formal?", "[Destination]-to going that right? (casual)"], "notes":"맞아요? (Majayo? — 'is that right?') can be added to any confirmation question. 방향이 맞아요? (Banghyangi majayo? — 'is the direction right?') is also useful. Koreans generally appreciate passengers who stay engaged rather than just staring at their phone." },
  { "d":3, "prompt":"Ask the driver to wait a moment.", "answers":["Jamkkanman gidaryeo juseyo", "Jamkkan gidaryeo jushigesseumnikka?", "Jamkkan gidaryeo jwo"], "translations":["Moment-only wait give-please", "Moment wait could-give-formal?", "Moment wait give (casual)"], "notes":"잠깐만 (Jamkkanman) = just a moment/just briefly. 기다려 주세요 (Gidaryeo juseyo — 'please wait') is the core phrase. 미터기 켜놓고 기다리세요 (Miteogi kyeonoko gidariseyo — 'please wait with the meter running') shows you understand Korean taxi etiquette." },
  { "d":4, "prompt":"Ask the driver for a local restaurant recommendation.", "answers":["Inyeong-e masijineun sigdang isseoyo?", "Yeogin-e geundaehan sigdang chucheon butakhabnida", "Yeogi matjip eodisseo?"], "translations":["Nearby delicious restaurant exist-polite? (is there a good restaurant nearby?)", "Nearby restaurant recommend I-request-formal", "Here famous-restaurant where? (casual)"], "notes":"맛집 (Matjip) = famous/delicious restaurant (one of the most useful Korean food words). Taxi drivers are excellent local experts — they know where locals actually eat. 현지인들이 자주 가는 곳 (Hyeonjindeuri jaju ganeun got — 'a place locals go often') gets the most authentic tips." },
  { "d":4, "prompt":"The meter seems high. Politely question it.", "answers":["Joesonghaeyo, miteogi jogeumyo nop-eun geot gata-yo", "Sillyehamnida, miteogi sangdanghi nop-eun geot gatseumnida", "Miteogi jogeumyo nop-eun geot gata"], "translations":["Sorry, meter a-little high-thing seems-polite", "Excuse-me, meter considerably high-thing seems-formal", "Meter a-little high-thing seems (casual)"], "notes":"미터기 (Miteogi) = taxi meter. Korean taxis have 기본 요금 (Gibun yogeum — base fare) with 추가 요금 (Chuga yogeum — additional charges) for night driving (밤 할증, Bam haljjeung) or highway use. Always screenshot the meter when you get in for reference." }
];
