window.DECKS = window.DECKS || {};
window.DECKS["ko"] = window.DECKS["ko"] || {};
window.DECKS["ko"]["workdinner"] = [
  { "d":1, "prompt":"Say cheers!", "answers":["Geonbae!", "Geonbae hapsida!", "Geonbae!"], "translations":["Cheers! (empty cup!)", "Cheers-let's-do-formal! (formal cheers)", "Cheers! (casual)"], "notes":"건배 (Geonbae) literally means 'empty glass' — equivalent to 'cheers!' 위하여! (Wihayeo! — 'to/for [something]!') is used for more specific toasts. In Korean drinking culture, never pour your own drink — always pour for others first and let others pour for you." },
  { "d":1, "prompt":"Compliment the food at the dinner.", "answers":["Eumsigi jinjja massisseoyo!", "Eumsigi jeongmal masitseumnida!", "Jinjja massisseoyo! Daebak!"], "translations":["Food really delicious-polite! (the food is really delicious!)", "Food really delicious-formal!", "Really delicious! Jackpot! (casual)"], "notes":"잘 먹겠습니다 (Jal meokgesseumnida — 'I will eat well') is said BEFORE eating — a culturally essential phrase. 잘 먹었습니다 (Jal meogeotsseumnida — 'I ate well') is said AFTER. These two bookend phrases are fundamental Korean dining etiquette." },
  { "d":1, "prompt":"Respond to please eat a lot.", "answers":["Gamsahaeyo, jal meokgesseumnida!", "Gamsahamnida, manhi deuketsseumnida!", "Gomawoyo, jal meokgesseumnida!"], "translations":["Thank-you, will-eat-well-polite! (thank you, I'll eat well!)", "Thank-you-formal, a-lot-will-take-formal!", "Thank-you, will-eat-well-polite!"], "notes":"많이 드세요 (Manhi deuseyo — 'please eat a lot') is the standard host invitation. 잘 먹겠습니다 (Jal meokgesseumnida — 'I will eat well') in response is the correct and culturally warm reply. Koreans take hosting very seriously — enthusiastic appreciation of food shows respect." },
  { "d":1, "prompt":"Receive a drink poured for you. Accept graciously.", "answers":["Gamsahaeyo!", "Gamsahamnida!", "Gomawoyo!"], "translations":["Thank-you-polite!", "Thank-you-formal!", "Thank-you! (casual)"], "notes":"In Korean drinking culture, always hold your glass with two hands (or support your right wrist with your left hand) when receiving a pour — this is a sign of respect. Never pour your own drink. Pour for others proactively, especially seniors. 한 잔 더 하실래요? (Han jan deo hasilraeyo? — 'would you like one more?') is the polite offer." },
  { "d":1, "prompt":"Say you had a wonderful time.", "answers":["Jinjja julgeoweosseoyo!", "Jeongmal julgeoweotseumnida!", "Jinjja julgeoweosseo! Daebak!"], "translations":["Really enjoyable-was-polite! (it was really enjoyable!)", "Really enjoyable-was-formal!", "Really enjoyable! Jackpot! (casual)"], "notes":"즐거웠어요 (Julgeoweosseoyo) = 'it was enjoyable/fun.' 덕분에 (Deokbune — 'thanks to you') adds warmth: 덕분에 즐거운 저녁이었어요 (Deokbune julgeoueun jeonyeogieosseoyo — 'it was a wonderful evening thanks to you'). Korean work dinners (회식, Hoisik) are important team-bonding events." },
  { "d":2, "prompt":"Politely decline more alcohol.", "answers":["Gwenchanayo, jeon-naeyo", "Gwaenchanseumnida, jeon-naemnida", "Gwenchanayo, eolma amseo-seo"], "translations":["It's fine, I have enough-polite", "It's fine-formal, I have enough-formal", "It's fine, not much already-polite"], "notes":"괜찮아요 (Gwaenchanayo) = 'it's fine/no thanks.' 저는 됐어요 (Jeoneun dwaesseoyo — 'I'm good/that's enough for me') is also very natural. In Korean culture, declining drinks from a senior is done gently — never abruptly. 조금만 주세요 (Jogeumman juseyo — 'just a little please') is a graceful middle ground." },
  { "d":2, "prompt":"Pour a drink for someone senior.", "answers":["Jae-ga ddaeredeurigesseumnida", "Han jan deurigesseumnida", "Han jan deurilkkeyo"], "translations":["I will pour-honorific-formal (I'll pour for you)", "One cup give-will-formal (I'll give you one cup)", "One cup give-will (polite)"], "notes":"따라드리다 (Ttaradeurida) = to pour (for someone senior — honorific). 따르다 (Ttareuda) = to pour (neutral). Pouring drinks for seniors before your own is fundamental Korean social etiquette. Saying 한 잔 따라드릴게요 (Han jan ttara-deurilgeyo — 'I'll pour you one cup') proactively is very impressive." },
  { "d":2, "prompt":"Say you'll have just one glass.", "answers":["Han jan-man halkgeyo", "Han jan-man hagetseumnida", "Han jan-man hae"], "translations":["One cup-only will-do-polite (just one cup)", "One cup-only will-do-formal", "One cup-only do (casual)"], "notes":"한 잔만 (Han janman) = just one cup. 오늘은 조금만 마실게요 (Oneuleun jogeumman masillgeyo — 'I'll just drink a little today') is a full natural sentence. In Korean work dinner culture, one is expected to drink at least a token amount — complete abstinence can sometimes be awkward without explanation." },
  { "d":2, "prompt":"Propose a toast to the team.", "answers":["Uri tim-eul wihayeo, geonbae!", "Uri tim-eul wihayeo geonbae hapsida!", "Tim-eul wihae, geonbae!"], "translations":["Our team-obj for/to, cheers!", "Our team-obj for-formal, cheers-let's-do!", "Team-for, cheers! (casual)"], "notes":"위하여! (Wihayeo!) = 'to [something]!' — the Korean toast word. 우리 팀을 위하여! (Uri timul wihayeo! — 'to our team!'). 수고 많으셨습니다 (Sugo maneushyeotsseumnida — 'you all worked very hard') as a prelude to a toast shows leadership and genuine appreciation." },
  { "d":2, "prompt":"Compliment the venue.", "answers":["Jinjja jeogun eotseoyo!", "Jeongmal bun-wigi-ga jotsseumnida!", "Yeogi jinjja daebak-iya!"], "translations":["Really good atmosphere-polite! (great atmosphere!)", "Really atmosphere-topic good-formal!", "Here really jackpot! (this place is awesome!, casual)"], "notes":"분위기 (Bunwigi) = atmosphere/vibe. 세팅이 너무 좋아요 (Seting-i neomu joahayo — 'the setting is really great') is also natural. Korean work dinner venues are often selected very carefully by the organizer — noticing and complimenting the choice is a genuine sign of appreciation." },
  { "d":3, "prompt":"Offer to pay the bill.", "answers":["Jega nael-geyo", "Jega gyesan halkgeyo", "Nae-ga nael-ge"], "translations":["I will pay-polite (I'll pay)", "I will pay-polite", "I will pay (casual)"], "notes":"제가 낼게요 (Jega naelgeyo — 'I'll pay') is the direct offer. 이번엔 제가 살게요 (Ibeonem jega salgeyo — 'I'll buy this time') signals you're treating the whole group. In Korean work dinners, the most senior person often insists on paying — be ready for the 'bill fight' (계산 전쟁, Gyesan jeonjaeng)." },
  { "d":3, "prompt":"Senior insists on paying. Thank and promise next time.", "answers":["Gamsahaeyo! Daeum beonem jega naelgeyo", "Gamsahamnida! Daeum beonem jega gyesan hagetseumnida", "Gomawoyo! Daeum beonem nae-ga nael-ge"], "translations":["Thank-you! Next time I will pay-polite", "Thank-you-formal! Next time I will pay-formal", "Thank-you! Next time I will pay (casual)"], "notes":"다음번엔 제가 낼게요 (Daeum beonem jega naelgeyo — 'next time I'll pay') is essential — it gracefully accepts generosity while promising reciprocity. This exchange is a recognized Korean social ritual. Never skip the promise to reciprocate when someone senior pays for you." },
  { "d":3, "prompt":"Ask what someone's research / work focuses on.", "answers":["Eoddeon yeong-gu haseyo?", "Eoddeon eopmu-reul dam-dang-hashimnikka?", "Museun yeong-gu hae?"], "translations":["What-kind research do-polite? (what research do you do?)", "What-kind duties-obj handle-formal?", "What research do? (casual)"], "notes":"연구 (Yeonggu) = research. 전공 (Jeongong) = major/specialty. 어떤 분야세요? (Eotteon bunyayeseyo? — 'what field are you in?') is also natural. Korean work culture involves discussing work even at dinner — showing interest in colleagues' fields is valued and often leads to deep conversations." },
  { "d":3, "prompt":"Thank the host for organizing the dinner.", "answers":["Jawari marryeo juseoseo gamsahaeyo", "Hoisik-eul jurihae jushyeoseo gamsahamnida", "Jawari marryeo juseoseo gomawoyo"], "translations":["Seat-obj prepared give-because thank-you-polite", "Work-dinner-obj arranged give-because thank-you-formal", "Seat-obj prepared give-because thank-you (casual)"], "notes":"자리를 마련해 주셔서 감사합니다 (Jarireul maryeon-hae jushyeoseo gamsahamnida) = 'thank you for preparing this occasion.' 준비해 주셔서 (Junbi-hae jushyeoseo — 'because you prepared it') acknowledges effort specifically. In Korea, the organizer works hard — explicit thanks for their effort is very meaningful." },
  { "d":4, "prompt":"Make a heartfelt toast speech.", "answers":["Oneul jinjja jeulgeowo-tsseumnida! Uri tim jinjja dae-bak! Geonbae!", "Oneul junbi-hae jushyeoin-eun bune gamsahamnida! Wihayeo!", "Oneul jinjja jeulgeowo-tsseumnida! Wihayeo! Geonbae!"], "translations":["Today really enjoyable-was! Our team jackpot! Cheers!", "Today prepared-who-gave-is person-to thank-you-formal! To/for!", "Today really enjoyable! To/for! Cheers! (casual)"], "notes":"위하여! (Wihayeo! — 'to/for!') is the key toast word. 오늘 정말 즐거웠습니다 (Oneul jeongmal jeulgeowotsseumnida — 'today was truly enjoyable') is a beautiful opener. End all toasts with 건배! — Koreans always expect the group word together. Drinking culture (술 문화, Sul munhwa) is an important part of Korean workplace bonding." },
  { "d":4, "prompt":"Say whether you enjoy work dinners and socializing with colleagues.", "answers":["Hoisik jinjja joahayo! Dongnyorodeul manna-neun ges joa-yo", "Hoisig-eul maeu joa-habnida, gwan-gyega gateukagesseumnida", "Hoisik daebak joayo! Dongnyorodeul gachi meogneun ges joa"], "translations":["Work-dinner really like-polite! Colleagues meeting-thing good", "Work-dinner very like-formal, relationship becomes-closer-formal", "Work-dinner jackpot good! Colleagues together eating-thing good (casual)"], "notes":"회식 (Hoisik) = Korean work dinner/drinking outing — a deeply embedded Korean workplace institution. 동료 (Dongnyoro) = colleague. 친목도모 (Chinmok domo) = socializing/fellowship building. Korean workplace relationships (인간관계, Ingan-gwangye) are built significantly through these social outings." }
];
