window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["CVS"] = [
  { "d":1, "prompt":"You enter. Staff greets you. Respond.", "answers":["Oi boa tarde!", "Olá!", "Bom dia!"], "translations":["Hey, good afternoon!", "Hello!", "Good day!"], "notes":"Always greet back in Brazil — skipping it is considered cold. Even a quick Oi! or Tudo bem! sets a warm tone and makes the whole interaction smoother." },
  { "d":1, "prompt":"Pay by card.", "answers":["No cartão", "Aceita cartão?", "Vou pagar no cartão"], "translations":["On the card", "Do you accept card?", "I'll pay by card"], "notes":"After saying no cartão, you'll be asked débito ou crédito? (debit or credit?). Contactless payment (pagamento por aproximação) is very common in Brazilian city stores." },
  { "d":1, "prompt":"Staff asks if you need a bag. Say yes.", "answers":["Sim por favor", "Uma sacola obrigado/a", "Pode dar uma sacola"], "translations":["Yes, please", "A bag, thank you", "Can you give a bag?"], "notes":"Sacola (bag) — many Brazilian stores now charge for plastic bags to reduce waste. Ask Tem sacola? first if unsure whether it's free." },
  { "d":1, "prompt":"Staff asks if you need a bag. Say no.", "answers":["Não obrigado/a", "Não precisa", "Sem sacola obrigado/a"], "translations":["No, thank you", "No need", "Without a bag, thanks"], "notes":"Não obrigado/a is the polite no — obrigado/a agrees with the speaker's gender. Just saying Não alone can sound abrupt; adding obrigado/a is always smoother." },
  { "d":1, "prompt":"Ask where the snacks / ramyeon are.", "answers":["Onde ficam os salgadinhos?", "Onde está [item]?", "Em que seção fica?"], "translations":["Where are the snacks?", "Where is [item]?", "In what section is it?"], "notes":"Salgadinhos (salty snacks) are hugely popular in Brazil — chips, crackers, peanuts. Fica (is located) is the go-to verb for asking where things are in a store." },
  { "d":1, "prompt":"Ask for a receipt.", "answers":["O comprovante por favor", "Me dá o recibo?", "Preciso do recibo"], "translations":["The receipt, please", "Give me the receipt?", "I need the receipt"], "notes":"In Brazil, the nota fiscal (tax receipt) is legally important — it protects consumer rights and can be used for insurance claims. Always ask for it." },
  { "d":2, "prompt":"Ask if they can microwave your food.", "answers":["Pode esquentar isso?", "Tem micro-ondas?", "Pode aquecer pra mim?"], "translations":["Can you heat this?", "Do you have a microwave?", "Can you heat this for me?"], "notes":"Many Brazilian convenience stores have a micro-ondas (microwave) available for customers — especially useful for instant noodles. Esquentar (to warm) is the casual everyday verb." },
  { "d":2, "prompt":"Ask for chopsticks and a spoon.", "answers":["Tem talheres?", "Hashi e colher por favor", "Me dá talheres?"], "translations":["Do you have cutlery?", "Chopsticks and spoon, please", "Give me cutlery?"], "notes":"Talheres (cutlery) is the general term. Hashi is the Brazilian word for chopsticks, borrowed from Japanese — Brazil has the largest Japanese diaspora outside Japan." },
  { "d":2, "prompt":"Ask for hot water.", "answers":["Água quente por favor", "Tem água quente?", "Um pouco de água quente"], "translations":["Hot water, please", "Do you have hot water?", "A little hot water"], "notes":"Água quente (hot water) for instant noodles — a common convenience store request. Many Brazilian stores have a hot water dispenser available for customers near the food section." },
  { "d":2, "prompt":"Ask if they sell painkillers.", "answers":["Tem analgésico?", "Vende remédio pra dor?", "Tem paracetamol?"], "translations":["Do you have painkiller?", "Do you sell pain medicine?", "Do you have paracetamol?"], "notes":"Dipirona is Brazil's most beloved painkiller — very effective, widely available, and barely found outside Brazil. Paracetamol and dipirona are both common OTC options at convenience stores." },
  { "d":2, "prompt":"Ask what time they close.", "answers":["A que horas fecham?", "Até que horas abrem?", "Que horas fecha?"], "translations":["At what time do they close?", "Until what time are they open?", "What time does it close?"], "notes":"Brazilian convenience stores in cities often stay open 24 hours (24 horas) — especially near nightlife areas. Que horas fecha? to confirm, just in case." },
  { "d":2, "prompt":"Ask for change / smaller bills.", "answers":["Pode me dar troco?", "Tem notas pequenas?", "Preciso de troco"], "translations":["Can you give me change?", "Do you have small bills?", "I need change"], "notes":"Troco (change) is the key word — also means exchange. Brazilians often struggle with change (moeda), so having small bills (notas pequenas) is always handy at smaller stores." },
  { "d":3, "prompt":"Ask if they sell phone chargers.", "answers":["Tem carregador de celular?", "Vende carregador?", "Onde fica o carregador?"], "translations":["Do you have a phone charger?", "Do you sell chargers?", "Where is the charger?"], "notes":"Carregador de celular (cell phone charger) — universal USB-C cables are more likely available than brand-specific ones. Very useful in a pinch when your battery is dying." },
  { "d":3, "prompt":"Ask where you can sit and eat inside.", "answers":["Posso comer aqui?", "Onde posso comer?", "Tem área para sentar?"], "translations":["Can I eat here?", "Where can I eat?", "Is there a seating area?"], "notes":"Brazilians often eat convenience store food on the spot. Posso comer aqui? (Can I eat here?) is a polite way to check. Many stores have a small area with stools or counters." },
  { "d":3, "prompt":"Ask if they have a different flavor.", "answers":["Tem em outro sabor?", "Tem mais sabores?", "Que sabores têm?"], "translations":["Do you have it in another flavor?", "Do you have more flavors?", "What flavors do you have?"], "notes":"Sabor (flavor) — Brazil has wonderfully unique chip and snack flavors: queijo (cheese), bacon, frango (chicken), picanha (steak). Worth exploring the local options!" },
  { "d":3, "prompt":"You want to return an item.", "answers":["Posso devolver isso?", "Quero devolver", "Aceita devolução?"], "translations":["Can I return this?", "I want to return (it)", "Do you accept returns?"], "notes":"Aceita devolução? (Do you accept returns?) — convenience stores often have limited return policies. Always check before buying perishable or single-use items." },
  { "d":4, "prompt":"Cashier asks about a loyalty card. Say you don't have one.", "answers":["Não tenho cartão fidelidade", "Não não tenho", "Ainda não tenho"], "translations":["I don't have a loyalty card", "No, I don't have one", "I still don't have one"], "notes":"Cartão fidelidade (loyalty card) — some Brazilian chains have these, giving points or discounts. Ainda não tenho (I still don't have one) is a polite and natural way to decline." },
  { "d":4, "prompt":"Say just these please at checkout.", "answers":["Só isso obrigado/a", "É só isso", "Só essas coisas"], "translations":["Only this, thanks", "It is only this", "Only these things"], "notes":"Só isso (just this/that) is one of the most useful phrases in all of Brazilian Portuguese — works in any shopping, ordering, or checkout context. Simple and universally understood." }
];
