window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["directions"] = [
  { "d":1, "prompt":"Say I'm lost.", "answers":["Estou perdido/a", "Não sei onde estou", "Me perdi"], "translations":["I am lost", "I don't know where I am", "I lost myself"] },
  { "d":1, "prompt":"Ask where the subway / train station is.", "answers":["Onde fica o metrô?", "Onde é a estação?", "Como chego à estação?"], "translations":["Where is the subway?", "Where is the station?", "How do I arrive at the station?"] },
  { "d":1, "prompt":"Ask is it far?", "answers":["É longe?", "Fica longe?", "É muito longe?"], "translations":["Is it far?", "Stays far?", "Is it very far?"] },
  { "d":1, "prompt":"Ask can I walk there?", "answers":["Dá para ir a pé?", "Posso caminhar?", "É perto a pé?"], "translations":["Gives to go on foot? (can I walk?)", "Can I walk?", "Is close on foot?"] },
  { "d":1, "prompt":"Say thank you after someone gives you directions.", "answers":["Muito obrigado/a!", "Obrigado/a muito gentil!", "Obrigado/a pela ajuda!"], "translations":["Very obliged!", "Obliged very kind!", "Obliged for the help!"] },
  { "d":2, "prompt":"Ask how long it takes on foot.", "answers":["Quanto tempo a pé?", "Quantos minutos caminhando?", "Quanto demora a pé?"], "translations":["How much time on foot?", "How many minutes walking?", "How much (it) takes on foot?"] },
  { "d":2, "prompt":"Ask if there's a bus stop nearby.", "answers":["Tem ponto de ônibus perto?", "Onde fica o ponto?", "Tem ônibus aqui perto?"], "translations":["Has bus stop near?", "Where is the stop?", "Has bus here near?"] },
  { "d":2, "prompt":"You didn't understand the directions. Ask to repeat.", "answers":["Pode repetir?", "Não entendi pode repetir?", "Mais devagar por favor"], "translations":["Can (you) repeat?", "Didn't understand can (you) repeat?", "More slowly for favor"] },
  { "d":2, "prompt":"Say I'll use my phone's map.", "answers":["Vou usar o GPS do celular", "Vou ver no Google Maps", "Vou usar o mapa no telefone"], "translations":["I'll use the GPS of the cell phone", "I'll look in Google Maps", "I'll use the map in the phone"] },
  { "d":2, "prompt":"Ask which exit to use at the subway.", "answers":["Por qual saída?", "Qual é a saída?", "Que número de saída?"], "translations":["By which exit?", "What is the exit?", "What number of exit?"] },
  { "d":2, "prompt":"A stranger walked you to your destination. Thank warmly.", "answers":["Muito obrigado/a mesmo!", "Nossa que gentileza!", "Não precisava mas muito obrigado/a!"], "translations":["Very obliged indeed!", "Wow what kindness!", "Didn't need to but very obliged!"] },
  { "d":3, "prompt":"Say I think I went the wrong way.", "answers":["Acho que fui pelo caminho errado", "Parece que errei o caminho", "Acho que me perdi de novo"], "translations":["I think I went by the wrong way", "Seems that I missed the way", "I think I lost myself again"] },
  { "d":3, "prompt":"Ask is this the right direction for [destination]?", "answers":["É por aqui para [destination]?", "Estou indo na direção certa?", "Esse caminho vai para [destination]?"], "translations":["Is by here to [destination]?", "I am going in the right direction?", "This way goes to [destination]?"] },
  { "d":3, "prompt":"Ask if there's a taxi stand nearby.", "answers":["Tem ponto de taxi perto?", "Onde posso pegar um taxi?", "Tem taxi stand aqui perto?"], "translations":["Has taxi stand near?", "Where can I catch a taxi?", "Has taxi stand here near?"] },
  { "d":4, "prompt":"Acknowledge complex directions: turn left then straight then second right.", "answers":["Esquerda em frente segunda à direita. É isso?", "Entendido esquerda reto e segunda à direita", "Esquerda direto e depois segunda à direita?"], "translations":["Left ahead second to the right. Is that it?", "Understood left straight and second to the right", "Left straight and then second to the right?"] },
  { "d":4, "prompt":"You found the place. Express relief and gratitude.", "answers":["Encontrei! Muito obrigado/a que alívio!", "Oba achei! Muito obrigado/a pela ajuda!", "Estava aqui! Obrigado/a salvou minha vida!"], "translations":["Found it! Very obliged what relief!", "Yay found it! Very obliged for the help!", "Was here! Obliged saved my life!"] }
];
