window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["directions"] = [
  { "d":1, "prompt":"Say I'm lost.", "answers":["Estou perdido/a", "Não sei onde estou", "Me perdi"], "translations":["I am lost", "I don't know where I am", "I lost myself"], "notes":"Me perdi (I lost myself) is the most natural phrasing — Portuguese uses reflexive verbs for this. Brazilians are very helpful with directions; don't hesitate to ask anyone." },
  { "d":1, "prompt":"Ask where the subway / train station is.", "answers":["Onde fica o metrô?", "Onde é a estação?", "Como chego à estação?"], "translations":["Where is the subway?", "Where is the station?", "How do I get to the station?"], "notes":"Metrô (from French métro) is the subway. São Paulo and Rio have extensive metro systems. Estação means station. Fica (stays/is located) is the natural verb for asking where things are." },
  { "d":1, "prompt":"Ask is it far?", "answers":["É longe?", "Fica longe?", "É muito longe?"], "translations":["Is it far?", "Is it (located) far?", "Is it very far?"], "notes":"Brazilians have a relaxed sense of distance — 'near' can mean 15 minutes on foot or a short bus ride. Always follow up with Quantos minutos a pé? (how many minutes walking?)" },
  { "d":1, "prompt":"Ask can I walk there?", "answers":["Dá para ir a pé?", "Posso caminhar?", "É perto a pé?"], "translations":["Is it possible to go on foot?", "Can I walk?", "Is it close on foot?"], "notes":"Dá para ir a pé? — dá para means 'is it possible' or 'can you/one' in casual Brazilian Portuguese. Extremely useful construction: dá para + infinitive verb." },
  { "d":1, "prompt":"Say thank you after someone gives you directions.", "answers":["Muito obrigado/a!", "Obrigado/a muito gentil!", "Obrigado/a pela ajuda!"], "translations":["Very thank you!", "Thank you, very kind!", "Thank you for the help!"], "notes":"Brazilians who give directions often go out of their way to help — sometimes walking you to your destination. Match that warmth with a genuine, heartfelt obrigado/a!" },
  { "d":2, "prompt":"Ask how long it takes on foot.", "answers":["Quanto tempo a pé?", "Quantos minutos caminhando?", "Quanto demora a pé?"], "translations":["How much time on foot?", "How many minutes walking?", "How long does it take on foot?"], "notes":"A pé (on foot) is the key phrase — literally 'on foot.' Brazilians often underestimate walking times, so mentally add a few extra minutes to whatever they tell you." },
  { "d":2, "prompt":"Ask if there's a bus stop nearby.", "answers":["Tem ponto de ônibus perto?", "Onde fica o ponto?", "Tem ônibus aqui perto?"], "translations":["Is there a bus stop nearby?", "Where is the stop?", "Is there a bus here nearby?"], "notes":"Ponto de ônibus (bus stop point) — ponto means stop/point. Ônibus (city bus) comes from French omnibus. Brazilian cities have extensive bus networks, often the main way locals get around." },
  { "d":2, "prompt":"You didn't understand the directions. Ask to repeat.", "answers":["Pode repetir?", "Não entendi pode repetir?", "Mais devagar por favor"], "translations":["Can you repeat?", "I didn't understand, can you repeat?", "More slowly, please"], "notes":"Mais devagar (more slowly) and Pode repetir? (can you repeat?) are both useful here. Brazilians never mind being asked to repeat — they'll happily slow down and clarify." },
  { "d":2, "prompt":"Say I'll use my phone's map.", "answers":["Vou usar o GPS do celular", "Vou ver no Google Maps", "Vou usar o mapa no telefone"], "translations":["I'll use the GPS of the cell phone", "I'll check in Google Maps", "I'll use the map on the phone"], "notes":"GPS do celular (cell phone GPS) is universally understood. Celular is the Brazilian word for mobile phone. Google Maps works very well in Brazil; Waze is popular for driving." },
  { "d":2, "prompt":"Ask which exit to use at the subway.", "answers":["Por qual saída?", "Qual é a saída?", "Que número de saída?"], "translations":["By which exit?", "What is the exit?", "What exit number?"], "notes":"Saída (exit) at Brazilian metro stations is usually numbered or named. Por qual saída? (by which exit?) is very practical and specific — much better than just asking 'which way.'" },
  { "d":2, "prompt":"A stranger walked you to your destination. Thank warmly.", "answers":["Muito obrigado/a mesmo!", "Nossa que gentileza!", "Não precisava mas muito obrigado/a!"], "translations":["Very thank you indeed!", "Wow, what kindness!", "You didn't need to, but very thank you!"], "notes":"Nossa que gentileza! (Wow what kindness!) shows genuine appreciation for an extraordinary gesture. Brazilians are often this helpful — don't be surprised, and match their warmth." },
  { "d":3, "prompt":"Say I think I went the wrong way.", "answers":["Acho que fui pelo caminho errado", "Parece que errei o caminho", "Acho que me perdi de novo"], "translations":["I think I went the wrong way", "It seems I missed the way", "I think I lost myself again"], "notes":"Errei o caminho (I made a mistake with the path) — errar (to err/make a mistake) is very commonly used in Brazil for any kind of mistake. Acho que (I think) softens it." },
  { "d":3, "prompt":"Ask is this the right direction for [destination]?", "answers":["É por aqui para [destination]?", "Estou indo na direção certa?", "Esse caminho vai para [destination]?"], "translations":["Is it this way to [destination]?", "Am I going in the right direction?", "Does this way go to [destination]?"], "notes":"É por aqui para [destination]? (is it this way to...?) is the most practical phrase for double-checking your direction without getting a whole new set of instructions." },
  { "d":3, "prompt":"Ask if there's a taxi stand nearby.", "answers":["Tem ponto de taxi perto?", "Onde posso pegar um taxi?", "Tem taxi stand aqui perto?"], "translations":["Is there a taxi stand nearby?", "Where can I catch a taxi?", "Is there a taxi stand nearby?"], "notes":"Pegar um táxi (catch a taxi) is the natural phrasing. In cities, apps like Uber and 99 have largely replaced traditional taxi stands — but stands still exist near airports and hotels." },
  { "d":4, "prompt":"Acknowledge complex directions: turn left then straight then second right.", "answers":["Esquerda em frente segunda à direita. É isso?", "Entendido esquerda reto e segunda à direita", "Esquerda direto e depois segunda à direita?"], "translations":["Left, ahead, second to the right. Is that it?", "Understood, left, straight, and second to the right", "Left, straight, and then second to the right?"], "notes":"Repeating directions back is great practice and very appreciated — it confirms you understood and gives the other person a chance to correct any misunderstanding." },
  { "d":4, "prompt":"You found the place. Express relief and gratitude.", "answers":["Encontrei! Muito obrigado/a que alívio!", "Oba achei! Muito obrigado/a pela ajuda!", "Estava aqui! Obrigado/a salvou minha vida!"], "translations":["Found it! Very thank you, what relief!", "Yay, found it! Very thank you for the help!", "It was here! Thank you, you saved my life!"], "notes":"Que alívio! (What relief!) is very expressive. Obrigado/a salvou minha vida! (you saved my life!) is dramatic but Brazilians use it genuinely — hyperbole is common and warm." }
];
