window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["introductions"] = [
  { "d":1, "prompt":"Say hello.", "answers":["Olá!", "Oi!", "Bom dia!"], "translations":["Hello!", "Hey/Hi!", "Good day!"] },
  { "d":1, "prompt":"Say good morning.", "answers":["Bom dia!", "Boa manhã!", "Olá, bom dia!"], "translations":["Good day!", "Good morning!", "Hello, good day!"] },
  { "d":1, "prompt":"Say good evening.", "answers":["Boa noite!", "Boa tarde!", "Olá, boa noite!"], "translations":["Good evening/night!", "Good afternoon/evening!", "Hello, good evening!"] },
  { "d":1, "prompt":"Say thank you.", "answers":["Obrigado/a!", "Muito obrigado/a!", "Valeu!"], "translations":["Obliged! (thank you)", "Very obliged!", "Worth it! (informal thanks)"] },
  { "d":1, "prompt":"Say sorry / excuse me.", "answers":["Desculpe", "Com licença", "Perdão"], "translations":["Excuse/Sorry (formal)", "With permission", "Pardon"] },
  { "d":1, "prompt":"Say yes.", "answers":["Sim", "Claro", "Com certeza"], "translations":["Yes", "Of course/Clear", "With certainty"] },
  { "d":1, "prompt":"Say no.", "answers":["Não", "Não, obrigado/a", "Não mesmo"], "translations":["No", "No, obliged (no thanks)", "No indeed"] },
  { "d":1, "prompt":"Say please.", "answers":["Por favor", "Faz favor", "Se faz favor"], "translations":["For favor (please)", "Does favor", "If does favor"] },
  { "d":1, "prompt":"Introduce your name.", "answers":["Meu nome é [your name]", "Me chamo [your name]", "Sou [your name]"], "translations":["My name is [your name]", "I call myself [your name]", "I am [your name]"] },
  { "d":1, "prompt":"Say 'nice to meet you.'", "answers":["Prazer em conhecer!", "Muito prazer!", "É um prazer!"], "translations":["Pleasure in knowing!", "Much pleasure!", "It is a pleasure!"] },
  { "d":1, "prompt":"Say goodbye.", "answers":["Tchau!", "Até logo!", "Xau!"], "translations":["Bye! (from Italian ciao)", "Until soon!", "Bye! (variant)"] },
  { "d":1, "prompt":"Say 'see you later.'", "answers":["Até mais!", "Até logo!", "A gente se vê!"], "translations":["Until more!", "Until soon!", "The people (we) see each other!"] },
  { "d":2, "prompt":"Ask 'how are you?'", "answers":["Como você está?", "Tudo bem?", "Como vai?"], "translations":["How you are?", "Everything well?", "How goes?"] },
  { "d":2, "prompt":"Respond: 'I'm fine, thank you.'", "answers":["Bem, obrigado/a", "Tudo bem, obrigado/a", "Estou bem, valeu"], "translations":["Well, obliged", "Everything well, obliged", "I am well, worth it (informal)"] },
  { "d":2, "prompt":"Say 'I don't understand.'", "answers":["Não entendo", "Não compreendo", "Não estou entendendo"], "translations":["I don't understand", "I don't comprehend", "I am not understanding"] },
  { "d":2, "prompt":"Ask 'do you speak English?'", "answers":["Você fala inglês?", "Fala inglês?", "Sabe inglês?"], "translations":["You speak English?", "Speaks English?", "Knows English?"] },
  { "d":2, "prompt":"Say 'I speak a little [language].'", "answers":["Falo um pouco", "Só um pouquinho", "Ainda estou aprendendo"], "translations":["I speak a little", "Only a tiny little", "Still I am learning"] },
  { "d":2, "prompt":"Say where you're from.", "answers":["Sou de [your country]", "Venho de [your country]", "Sou [nationality]"], "translations":["I am from [your country]", "I come from [your country]", "I am [nationality]"] },
  { "d":2, "prompt":"Ask someone's name.", "answers":["Como você se chama?", "Qual é o seu nome?", "Como é o seu nome?"], "translations":["How you call yourself?", "What is your name?", "How is your name?"] },
  { "d":2, "prompt":"Ask 'where are you from?'", "answers":["De onde você é?", "De onde você vem?", "Você é de onde?"], "translations":["From where you are?", "From where you come?", "You are from where?"] },
  { "d":2, "prompt":"Say you live in [your city].", "answers":["Moro em [your city]", "Estou em [your city]", "Vivo em [your city]"], "translations":["I live in [your city]", "I am in [your city]", "I live in [your city]"] },
  { "d":3, "prompt":"Say 'can you speak more slowly, please?'", "answers":["Pode falar mais devagar?", "Mais devagar, por favor", "Fala mais lento, por favor"], "translations":["Can speak more slowly?", "More slowly, for favor", "Speak more slow, for favor"] },
  { "d":3, "prompt":"Say 'I'm still learning [language].'", "answers":["Ainda estou aprendendo", "Ainda estou estudando", "Estou aprendendo ainda"], "translations":["Still I am learning", "Still I am studying", "I am learning still"] },
  { "d":3, "prompt":"Say 'I understand a little but speaking is still hard.'", "answers":["Entendo um pouco mas falar ainda é difícil", "Consigo entender mas não falo muito bem", "Entendo mas falar é complicado"], "translations":["I understand a little but to-speak still is difficult", "I manage to understand but not speak very well", "I understand but to-speak is complicated"] },
  { "d":3, "prompt":"Ask what someone does for work.", "answers":["O que você faz?", "Com o que trabalha?", "Qual é a sua profissão?"], "translations":["What you do?", "With what (you) work?", "What is your profession?"] },
  { "d":3, "prompt":"Say what you do for work.", "answers":["Sou [job]", "Trabalho como [job]", "Faço [job]"], "translations":["I am [job]", "I work as [job]", "I do [job]"] },
  { "d":4, "prompt":"Say you've been trying to learn the language for a few months.", "answers":["Estudo português há alguns meses", "Comecei faz pouco tempo", "Já estudo há uns meses"], "translations":["I study Portuguese for some months", "I started a short time ago", "Already I study for some months"] },
  { "d":4, "prompt":"Compliment someone's language skills and ask how they learned.", "answers":["Você fala muito bem! Como aprendeu?", "Seu português é ótimo! Onde aprendeu?", "Como você aprendeu tão bem?"], "translations":["You speak very well! How (you) learned?", "Your Portuguese is great! Where (you) learned?", "How you learned so well?"] }
];
