window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["market"] = [
  { "d":1, "prompt":"Greet the vendor at the stall.", "answers":["Olá boa tarde!", "Bom dia!", "Oi!"], "translations":["Hello, good afternoon!", "Good day!", "Hey/Hi!"], "notes":"Always greet vendors warmly — Brazilians find skipping the greeting rude. A simple Oi! or Bom dia! sets a positive tone and often gets you better service and deals." },
  { "d":1, "prompt":"Ask how much something is.", "answers":["Quanto custa?", "Qual o preço?", "Quanto é?"], "translations":["How much does it cost?", "What is the price?", "How much is it?"], "notes":"Quanto é? (how much is it?) is the most casual and shortest. Qual o preço? is slightly more formal. Both are equally appropriate at any market stall." },
  { "d":1, "prompt":"Say I'll take this one.", "answers":["Vou levar esse", "Esse por favor", "Levo esse"], "translations":["I'll take this one", "This one, please", "I take this one"], "notes":"Esse (this one, masc.) or Essa (this one, fem.) — the gender agrees with the item. Vou levar and Levo both mean 'I'll take it' — the first is slightly more formal." },
  { "d":1, "prompt":"Say something looks too expensive.", "answers":["Está caro", "É um pouco caro", "Está muito caro"], "translations":["It is expensive", "It is a little expensive", "It is very expensive"], "notes":"Está caro is neutral and very common. At Brazilian street markets (feiras), saying it's expensive is the natural opening to price negotiation — vendors expect it." },
  { "d":1, "prompt":"Ask to try a sample.", "answers":["Posso experimentar?", "Deixa provar?", "Tem amostra?"], "translations":["Can I try?", "Let me taste?", "Do you have a sample?"], "notes":"Pode deixar provar? (can you let me taste?) is very natural. Most Brazilian market vendors happily offer tastes — it's part of the culture and a good way to build rapport." },
  { "d":1, "prompt":"Sample is delicious. React.", "answers":["Que delícia!", "Está ótimo!", "Muito bom!"], "translations":["What delight!", "It is great!", "Very good!"], "notes":"Que delícia! (What delight!) is the go-to exclamation in Brazil. Delícia is used for food, places, and weather — anything wonderful. It always goes down well." },
  { "d":1, "prompt":"Say see you next time.", "answers":["Até a próxima!", "Até logo!", "Volto em breve!"], "translations":["Until next time!", "Until soon!", "I'll be back soon!"], "notes":"Volto em breve (I'll be back soon) makes vendors happy and might even get you a better deal next time — it signals loyalty, which matters in market culture." },
  { "d":2, "prompt":"Ask if it's fresh.", "answers":["Está fresco?", "É de hoje?", "Quando chegou?"], "translations":["Is it fresh?", "Is it from today?", "When did it arrive?"], "notes":"É de hoje? (Is it from today?) is very natural and direct. Brazilians care a lot about freshness — don't be shy to ask. Vendors rarely take offence." },
  { "d":2, "prompt":"Ask for a smaller portion.", "answers":["Pode colocar menos?", "Tem porção menor?", "Um pouco menos"], "translations":["Can you put less?", "Do you have a smaller portion?", "A little less"], "notes":"Brazilian market portions are often generous — it's completely fine to ask for less. Um pouco menos (a little less) is the simplest, most direct way to say it." },
  { "d":2, "prompt":"Ask for a bag.", "answers":["Uma sacola por favor", "Pode dar uma sacola?", "Tem sacola?"], "translations":["A bag, please", "Can you give me a bag?", "Do you have a bag?"], "notes":"Sacola (bag) is the word. Some markets now charge for bags as part of sustainability efforts. Tem sacola? checks availability before assuming one is free." },
  { "d":2, "prompt":"Pay in cash.", "answers":["Pago em dinheiro", "No dinheiro", "Vou pagar em espécie"], "translations":["I pay in cash", "In the money (cash)", "I'll pay in cash"], "notes":"Em espécie (in cash) is more formal — espécie literally means 'species/kind.' Dinheiro (money/cash) is more casual. Cash is still widely preferred at many street markets." },
  { "d":2, "prompt":"The vendor speaks too fast. Ask to slow down.", "answers":["Mais devagar por favor", "Pode falar mais devagar?", "Não entendi de novo?"], "translations":["More slowly, please", "Can you speak more slowly?", "I didn't understand, again?"], "notes":"Brazilians speak quickly! Mais devagar is your best friend at markets. No one minds — vendors are used to helping non-native speakers and usually enjoy the interaction." },
  { "d":2, "prompt":"Say I come here often.", "answers":["Venho aqui sempre", "Sou cliente frequente", "Costumo vir aqui"], "translations":["I come here always", "I am a frequent client", "I usually come here"], "notes":"Costumo vir aqui (I usually come here) signals you're a regular. Regular customers (clientes frequentes) often get better prices, extra items, and the best produce." },
  { "d":3, "prompt":"Ask what's in season.", "answers":["O que está na época?", "O que está mais fresco agora?", "O que você recomenda desta estação?"], "translations":["What is in season?", "What is most fresh now?", "What do you recommend this season?"], "notes":"Na época means in season. Brazilian produce is incredibly fresh and seasonal — in-season fruit is much cheaper and tastier. This question also signals you know what you're doing." },
  { "d":3, "prompt":"Ask how to cook an unfamiliar vegetable.", "answers":["Como cozinha isso?", "Como usa isso?", "Para que serve?"], "translations":["How do you cook this?", "How do you use this?", "What is this for?"], "notes":"Para que serve? (What is it for?) opens a great conversation. Brazilians love sharing recipes — market vendors often have the best practical cooking tips for local produce." },
  { "d":3, "prompt":"Ask for a discount for buying multiple items.", "answers":["Se comprar mais tem desconto?", "Tem desconto na quantidade?", "Levo mais se fizer preço"], "translations":["If I buy more, is there a discount?", "Is there a quantity discount?", "I'll take more if you give me a deal"], "notes":"Levo mais se fizer preço (I'll take more if you make a price) is a classic negotiating line at Brazilian markets — very natural and usually effective." },
  { "d":3, "prompt":"Compliment the vendor's produce.", "answers":["Os produtos aqui sempre estão frescos!", "Sempre muito fresco aqui!", "Dá pra ver que você cuida da qualidade!"], "translations":["The products here are always fresh!", "Always very fresh here!", "You can tell you care about quality!"], "notes":"Dá pra ver que você cuida da qualidade! (you can tell you care about quality!) is a genuine compliment that vendors love. Brazilians respond very warmly to sincere praise." },
  { "d":4, "prompt":"Vendor says can't go lower. Accept gracefully.", "answers":["Tudo bem vou levar mesmo assim", "Ok fico com ele", "Tudo bem aceito o preço"], "translations":["All fine, I'll take it anyway", "Ok, I'll keep/take it", "All fine, I accept the price"], "notes":"Tudo bem aceito o preço (alright, I accept the price) closes the negotiation respectfully. Graceful acceptance after negotiation is good manners in Brazilian market culture." },
  { "d":4, "prompt":"Vendor throws in a free extra. Express surprise and thanks.", "answers":["Que gentileza obrigado/a!", "Nossa muito obrigado/a!", "Não precisava mas obrigado/a!"], "translations":["What kindness, thank you!", "Wow, very thank you!", "You didn't need to, but thank you!"], "notes":"Não precisava (you didn't need to) is the polite response to unexpected generosity. Brazilians are known for this kind of warmth with regular or friendly customers." }
];
