window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["office"] = [
  { "d":1, "prompt":"Greet a colleague in the morning.", "answers":["Bom dia!", "Oi bom dia!", "Olá bom dia!"], "translations":["Good day!", "Hey, good day!", "Hello, good day!"], "notes":"Oi bom dia! is the standard warm office greeting in Brazil. A simple bom dia to everyone you pass — even in a large office — is considered polite and expected." },
  { "d":1, "prompt":"Say see you tomorrow.", "answers":["Até amanhã!", "A gente se vê amanhã", "Até logo!"], "translations":["Until tomorrow!", "We'll see each other tomorrow", "Until soon!"], "notes":"A gente se vê amanhã — a gente (literally 'the people') replaces nós (we) in almost all casual Brazilian speech. Using it makes you sound very natural." },
  { "d":1, "prompt":"Colleague apologizes for something small. Reassure them.", "answers":["Não tem problema!", "Tranquilo/a", "Sem problemas"], "translations":["No problem!", "Calm / No worries", "Without problems"], "notes":"Tranquilo/a means calm/relaxed — -o for male speaker, -a for female. It's the Brazilian way to say 'no worries' or 'chill.' Não tem problema is universally understood everywhere." },
  { "d":1, "prompt":"Say I'll be right back.", "answers":["Já volto", "Venho já", "Um segundo"], "translations":["I return right now", "I come right now", "A second"], "notes":"Já means 'already/right now' in Brazilian Portuguese — a very versatile word. Já volto (I'm coming right back) literally means 'I already return' — the já implies immediacy." },
  { "d":1, "prompt":"Ask where the bathroom is.", "answers":["Onde fica o banheiro?", "Onde são os banheiros?", "Tem banheiro por aqui?"], "translations":["Where is the bathroom?", "Where are the bathrooms?", "Is there a bathroom around here?"], "notes":"Banheiro is the Brazilian word for bathroom/restroom. In Portugal they say casa de banho (house of bath). WC is also widely understood in Brazil. Fica (is located) is the natural verb." },
  { "d":1, "prompt":"Say I'm going home now.", "answers":["Vou embora", "Tô indo", "Até amanhã estou saindo"], "translations":["I'm going away", "I'm going (informal)", "Until tomorrow, I'm leaving"], "notes":"Tô indo is very casual — tô is an informal contraction of estou. Vou embora (I'm going away) is more complete and common when saying goodbye at the end of the workday." },
  { "d":2, "prompt":"Apologize for being late.", "answers":["Desculpe o atraso", "Me desculpe por chegar atrasado/a", "Sinto muito pelo atraso"], "translations":["Excuse the lateness", "Excuse me for arriving late", "I feel very sorry for the lateness"], "notes":"Desculpe o atraso (excuse the lateness) is the most natural and concise. Brazilians are known for flexible timing socially, but in professional settings punctuality is generally expected." },
  { "d":2, "prompt":"Say I'm still learning.", "answers":["Ainda estou aprendendo", "Ainda estou no processo", "Estou evoluindo"], "translations":["Still I am learning", "Still I am in the process", "I am evolving/improving"], "notes":"Estou evoluindo (I am evolving) is a positive, growth-oriented way to frame ongoing learning. Brazilians appreciate this framing — it sounds humble yet forward-looking." },
  { "d":2, "prompt":"Sympathize with a tired colleague.", "answers":["Coitado/a! Descansa um pouco", "Boa vai descansar!", "Anima já falta pouco!"], "translations":["Poor thing! Rest a little", "Good, go rest!", "Cheer up, not much left!"], "notes":"Anima! (cheer up!) comes from animar (to cheer/animate). Já falta pouco! (not much left!) is an encouraging phrase. Coitado/a (poor thing) — -o/-a for gender — shows empathy warmly." },
  { "d":2, "prompt":"Ask do you want coffee?", "answers":["Quer um café?", "Te ofereço um café?", "Um café?"], "translations":["Do you want a coffee?", "Can I offer you a coffee?", "A coffee?"], "notes":"Coffee (café) is a social ritual in Brazilian offices — offered constantly throughout the day. Quer um café? is practically a greeting in itself. Always accept — it builds collegiality." },
  { "d":2, "prompt":"Say proper goodbye to a leaving colleague.", "answers":["Até amanhã!", "Até logo bom descanso!", "Boa tarde!"], "translations":["Until tomorrow!", "Until soon, good rest!", "Good afternoon!"], "notes":"Bom descanso (good rest) is a warm farewell at end of day. Boa tarde can be used as both hello and goodbye in the afternoon — very versatile." },
  { "d":2, "prompt":"Colleague invites you to lunch. Say yes!", "answers":["Sim vamos!", "Claro vou!", "Que ótimo vou sim!"], "translations":["Yes, let's go!", "Of course, I'll go!", "How great, I'll go, yes!"], "notes":"Brazilians take lunch seriously — it's a social event, not just a meal. Almoço (lunch) is often the biggest meal of the day in Brazil. Always accept a lunch invite when you can." },
  { "d":3, "prompt":"Politely excuse yourself from a conversation.", "answers":["Com licença preciso resolver algo", "Desculpe tenho que ir um segundo", "Com licença um momentinho"], "translations":["With permission, I need to resolve something", "Excuse me, I have to go a second", "With permission, a little moment"], "notes":"Com licença (with permission) is the social lubricant of Brazilian Portuguese — use it whenever you need to interrupt or exit gracefully. Momentinho is the diminutive of momento (a little moment)." },
  { "d":3, "prompt":"Say you don't understand. Ask for clarification.", "answers":["Não entendi pode explicar?", "Não ficou claro pode repetir?", "Pode explicar de outra forma?"], "translations":["Didn't understand, can you explain?", "Didn't become clear, can you repeat?", "Can you explain in another way?"], "notes":"Não ficou claro (it didn't become clear) is a very polite way to say you didn't understand — ficou framing it as a clarity issue, not a speaker problem. Ficar is a key verb in Brazilian Portuguese." },
  { "d":3, "prompt":"Thank a colleague who genuinely helped you.", "answers":["Muito obrigado/a você me ajudou muito", "De verdade agradeço muito", "Valeu mesmo não sei o que faria sem você"], "translations":["Very thank you, you helped me a lot", "For real, I thank you very much", "Thanks indeed, I don't know what I'd do without you"], "notes":"Não sei o que faria sem você (I don't know what I'd do without you) is heartfelt. Brazilians use this genuinely — warmth and emotional expression are part of the work culture." },
  { "d":4, "prompt":"Ask for feedback on your work politely.", "answers":["Pode me dar um feedback sobre meu trabalho?", "Tem algum comentário sobre o que fiz?", "Gostaria de saber o que melhorar"], "translations":["Can you give me feedback on my work?", "Do you have any comment on what I did?", "I would like to know what to improve"], "notes":"Feedback (pronounced 'fee-DEH-chi' in Brazil) is commonly used in professional settings — a direct English loanword. Gostaria (I would like) is the conditional tense — very polite." },
  { "d":4, "prompt":"Say I'll try my best.", "answers":["Vou dar o meu melhor", "Farei tudo que puder", "Vou me esforçar ao máximo"], "translations":["I'll give my best", "I'll do everything I can", "I'll make effort to the maximum"], "notes":"Vou me esforçar ao máximo — esforçar means to make an effort/strive. Ao máximo (to the maximum) adds intensity. Vou dar o meu melhor (I'll give my best) is the warmest, most natural version." }
];
