window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["pharmacy"] = [
  { "d":1, "prompt":"Say you have a headache.", "answers":["Estou com dor de cabeça", "Minha cabeça está doendo", "Tenho dor de cabeça"], "translations":["I am with headache", "My head is hurting", "I have headache"], "notes":"Estou com dor de cabeça — Brazilians use estar com (to be with) for symptoms. Literally 'I am with headache.' This construction works for almost any pain or illness." },
  { "d":1, "prompt":"Say you have a stomachache.", "answers":["Estou com dor de barriga", "Meu estômago está doendo", "Tenho dor de estômago"], "translations":["I am with belly-ache", "My stomach is hurting", "I have stomach-ache"], "notes":"Dor de barriga (belly pain) is more casual; dor de estômago (stomach pain) is slightly more formal. Barriga literally means belly — both are widely used and understood." },
  { "d":1, "prompt":"Say you have a fever.", "answers":["Estou com febre", "Tenho febre", "Acho que estou com febre"], "translations":["I am with fever", "I have fever", "I think I am with fever"], "notes":"Febre (fever) in Brazil is generally considered 37.5°C or above. A pharmacist will take this seriously — they may recommend you see a doctor at the UPA (urgent care) if it's high." },
  { "d":1, "prompt":"Say you have a cold.", "answers":["Estou resfriado/a", "Peguei um resfriado", "Estou com gripe"], "translations":["I am cold-ed (have a cold)", "I caught a cold", "I am with flu/cold"], "notes":"Gripe (flu/bad cold) and resfriado (mild cold) are technically different. Brazilians often say gripe for any bad cold. Peguei means 'I caught' — a natural phrasing." },
  { "d":1, "prompt":"Ask for pain medication.", "answers":["Tem remédio pra dor?", "Me dá um analgésico?", "Preciso de algo pra dor"], "translations":["Do you have medicine for pain?", "Give me a painkiller?", "I need something for pain"], "notes":"Dipirona is Brazil's most loved OTC painkiller — very effective, not found in many countries, and the first thing Brazilians reach for. Ask for it by name and trust the pharmacist." },
  { "d":1, "prompt":"Say it hurts here.", "answers":["Dói aqui", "Tenho dor aqui", "Aqui está doendo"], "translations":["Hurts here", "I have pain here", "Here is hurting"], "notes":"Dói aqui (hurts here) — pointing to the location while saying this is completely natural and universal. Dói comes from doer (to hurt/ache), pronounced 'DOY.'" },
  { "d":1, "prompt":"Pharmacist gives you medicine. Say thank you.", "answers":["Muito obrigado/a!", "Obrigado/a!", "Obrigado/a pela ajuda"], "translations":["Very thank you!", "Thank you!", "Thank you for the help"], "notes":"Brazilian pharmacists (farmacêuticos) are highly trained and often provide good medical advice — treat them with the same respect as a doctor. They're a first port of call for many Brazilians." },
  { "d":2, "prompt":"Ask how many times a day to take the medicine.", "answers":["Quantas vezes por dia?", "De quantas em quantas horas?", "Qual a dosagem?"], "translations":["How many times per day?", "Every how many hours?", "What is the dosage?"], "notes":"De quantas em quantas horas? (every how many hours?) is the most precise way to ask about dosing intervals — very useful when the label is unclear or in Portuguese only." },
  { "d":2, "prompt":"Say you feel dizzy.", "answers":["Estou com tontura", "Estou tonto/a", "Estou com vertigem"], "translations":["I am with dizziness", "I am dizzy", "I am with vertigo"], "notes":"Tontura is general dizziness; vertigem is more like spinning vertigo. Estou tonto/a (I am dizzy) — tonto/a is also used colloquially to mean silly or confused in other contexts." },
  { "d":2, "prompt":"Say you feel nauseous.", "answers":["Estou com náusea", "Sinto enjoo", "Estou enjoado/a"], "translations":["I am with nausea", "I feel queasiness/nausea", "I am nauseated"], "notes":"Enjoo (nausea/queasiness) is a very broad word — used for seasickness, motion sickness, and general nausea. Estou enjoado/a (I'm nauseated) is clear enough for any pharmacist." },
  { "d":2, "prompt":"Ask if you need a prescription.", "answers":["Precisa de receita?", "Posso comprar sem receita?", "Precisa de prescrição médica?"], "translations":["Does it need a prescription?", "Can I buy it without a prescription?", "Does it need a medical prescription?"], "notes":"Receita médica is the medical prescription. Some medications that require prescriptions elsewhere are OTC in Brazil, and vice versa. Always check — pharmacists will tell you clearly." },
  { "d":2, "prompt":"Ask for a bandage.", "answers":["Um curativo por favor", "Tem band-aid?", "Um esparadrapo?"], "translations":["A bandage, please", "Do you have a band-aid?", "Medical tape?"], "notes":"Curativo is the general word for bandage/dressing. Band-aid is used as a brand name (like in English). Esparadrapo is medical adhesive tape — good for larger wound coverage." },
  { "d":2, "prompt":"Ask for a thermometer.", "answers":["Tem termômetro?", "Um termômetro por favor", "Me dá um termômetro?"], "translations":["Do you have a thermometer?", "A thermometer, please", "Give me a thermometer?"], "notes":"Termômetro digital (digital thermometer) is most common — de ouvido (ear) or de testa (forehead) types are widely sold. Mercury thermometers (de mercúrio) are now largely banned in Brazil." },
  { "d":3, "prompt":"Say you have a sore throat.", "answers":["Estou com dor de garganta", "Minha garganta está doendo", "Tenho garganta inflamada"], "translations":["I am with throat pain", "My throat is hurting", "I have an inflamed throat"], "notes":"Garganta inflamada (inflamed throat) is the precise medical term. Brazilians often treat this with a throat spray (spray para garganta) or pastilhas (lozenges) before seeing a doctor." },
  { "d":3, "prompt":"Say you have a cough.", "answers":["Estou com tosse", "Tenho muita tosse", "Não paro de tossir"], "translations":["I am with cough", "I have much cough", "I don't stop coughing"], "notes":"Tosse is cough — pronounced 'TOH-see.' Não paro de tossir (I can't stop coughing) is a very vivid and natural description. Xarope (syrup) is the common remedy pharmacists recommend." },
  { "d":3, "prompt":"Say you have a runny nose.", "answers":["Meu nariz está escorrendo", "Estou com coriza", "Nariz entupido"], "translations":["My nose is running", "I have a runny nose (medical term)", "Stuffy/blocked nose"], "notes":"Coriza is the medical term for runny nose. Nariz escorrendo (nose running) is more colloquial. Nariz entupido (stuffed nose) is a different symptom — congested rather than runny." },
  { "d":3, "prompt":"Ask if you should see a doctor.", "answers":["Devo ir ao médico?", "Preciso de médico?", "É sério o suficiente para ir ao médico?"], "translations":["Should I go to the doctor?", "Do I need a doctor?", "Is it serious enough to go to the doctor?"], "notes":"UPA (Unidade de Pronto Atendimento) is Brazil's urgent care center — free for everyone. UBS is the local public health post for less urgent issues. Pharmacists will point you to the right place." },
  { "d":4, "prompt":"Declare an allergy to a specific medicine.", "answers":["Tenho alergia a [medicine]", "Não posso tomar [medicine]", "Sou alérgico/a a [medicine]"], "translations":["I have allergy to [medicine]", "I cannot take [medicine]", "I am allergic to [medicine]"], "notes":"Alérgico/a — -o for male, -a for female. Always state medicine allergies clearly and firmly. Brazilian pharmacists take this seriously and will check for contraindications carefully." },
  { "d":4, "prompt":"Pharmacist says go to hospital. Ask where.", "answers":["Ah então preciso ir ao hospital? Onde fica?", "Entendido onde é o hospital mais próximo?", "Ok pode me dizer onde fica o hospital?"], "translations":["Ah, then I need to go to the hospital? Where is it?", "Understood, where is the nearest hospital?", "Ok, can you tell me where the hospital is?"], "notes":"For non-emergencies, ask for the nearest UPA (urgent care) rather than a full hospital — it's faster and free. For emergencies, SAMU is Brazil's 192 ambulance service." }
];
