window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["restro"] = [
  { "d":1, "prompt":"Get the server's attention.", "answers":["Com licença!", "Por favor!", "Oi com licença!"], "translations":["With permission!", "Please!", "Hey, with permission!"], "notes":"Com licença! (with permission) is the polite standard. Some Brazilians call Moço! (young man) or Moça! (young woman), but Com licença is more universally polished." },
  { "d":1, "prompt":"Staff asks how many people. Say two.", "answers":["Somos dois", "Para duas pessoas", "Dois por favor"], "translations":["We are two", "For two people", "Two, please"], "notes":"Dois (two, masculine) or duas (two, feminine) — when counting people, Brazilians usually say Somos dois/duas (we are two), or Para duas pessoas (for two people)." },
  { "d":1, "prompt":"Ask for water.", "answers":["Água por favor", "Me traz água?", "Um copo d'água"], "translations":["Water, please", "Bring me water?", "A glass of water"], "notes":"After ordering water you'll often be asked: com gás ou sem gás? (sparkling or still?). Sem gás = still, com gás = sparkling. Still (sem gás) is the default preference in Brazil." },
  { "d":1, "prompt":"Ask for the menu.", "answers":["O cardápio por favor", "Me traz o cardápio?", "Pode trazer o menu?"], "translations":["The menu, please", "Bring me the menu?", "Can you bring the menu?"], "notes":"Cardápio is the Brazilian word for menu. In Portugal they say ementa. Both cardápio and menu are understood throughout Brazil — cardápio is more local." },
  { "d":1, "prompt":"Food arrives. Server says enjoy. Respond.", "answers":["Obrigado/a!", "Tá ótimo!", "Muito obrigado/a"], "translations":["Thank you!", "It's great!", "Very thank you!"], "notes":"Bom apetite (good appetite) or Bom proveito (good enjoyment) are the typical bon appétit phrases. A warm Obrigado/a! back to the server is always appreciated." },
  { "d":1, "prompt":"Ask for the bill.", "answers":["A conta por favor", "Pode fechar a conta?", "Quanto ficou?"], "translations":["The bill, please", "Can you close the bill?", "How much did it come to?"], "notes":"Pode fechar a conta? (can you close the bill?) is the most natural phrasing. Brazilians often don't split in restaurants — one person pays and others settle up later." },
  { "d":1, "prompt":"Pay by card.", "answers":["No cartão", "Aceita cartão?", "Vou pagar no cartão"], "translations":["On the card", "Do you accept card?", "I'll pay on the card"], "notes":"After saying no cartão, you'll usually be asked: débito ou crédito? (debit or credit?). Vendors often prefer débito (debit) as the fees are lower for them." },
  { "d":1, "prompt":"Say you're full.", "answers":["Estou satisfeito/a", "Não consigo mais", "Tô cheio/a"], "translations":["I am satisfied", "I can't (eat) any more", "I'm full"], "notes":"Tô cheio/a is very casual — cheio/a literally means 'full' (cheio masc., cheia fem.). Estou satisfeito/a is more formal and polite — great for a restaurant setting." },
  { "d":2, "prompt":"Ask if this dish is spicy.", "answers":["É picante?", "Tem pimenta?", "Pica muito?"], "translations":["Is it spicy?", "Does it have pepper?", "Does it sting a lot?"], "notes":"Pica muito? (does it sting a lot?) is very colloquial. Brazilians generally love pimenta (pepper), but spice levels vary a lot by region — northeast Brazil is significantly hotter." },
  { "d":2, "prompt":"Say no onions please.", "answers":["Sem cebola por favor", "Pode tirar a cebola?", "Sem cebola obrigado/a"], "translations":["Without onion, please", "Can you remove the onion?", "Without onion, thanks"], "notes":"Pode tirar? (can you remove?) is polite and very effective for modifications. Brazilians are generally accommodating with food adjustments — just ask nicely." },
  { "d":2, "prompt":"Ask for more side dishes / bread / rice.", "answers":["Mais pão por favor?", "Mais guarnição?", "Pode trazer mais disso?"], "translations":["More bread, please?", "More side dish?", "Can you bring more of this?"], "notes":"Guarnição means side dish or garnish. In Brazil, rice and beans (arroz e feijão) are always offered as sides — a staple of virtually every Brazilian meal." },
  { "d":2, "prompt":"Ask for napkins.", "answers":["Guardanapos por favor", "Me traz guardanapos?", "Guardanapos?"], "translations":["Napkins, please", "Bring me napkins?", "Napkins?"], "notes":"Guardanapo is the word for napkin — pronounced 'gwar-dah-NAH-po.' Brazilians use the diminutive guardanapinho (little napkin) in casual settings, which sounds friendlier." },
  { "d":2, "prompt":"Ask if a dish has meat in it.", "answers":["Tem carne?", "Isso tem carne?", "Leva carne?"], "translations":["Does it have meat?", "Does this have meat?", "Does it carry/contain meat?"], "notes":"Leva carne? (does it carry meat?) is very colloquial. Important note: in casual Brazilian speech, frango (chicken) and peixe (fish) are often NOT considered 'carne' — always specify." },
  { "d":2, "prompt":"Say you don't eat meat.", "answers":["Não como carne", "Sou vegetariano/a", "Sem carne"], "translations":["I don't eat meat", "I am vegetarian", "Without meat"], "notes":"Vegetariano/a has the -o/-a gender agreement. Vegetarian options are growing in Brazilian cities, especially São Paulo. In traditional churrascarias (BBQ restaurants), options are very limited." },
  { "d":2, "prompt":"Ask for a takeaway box.", "answers":["Pode empacotar para levar?", "Para levar o que sobrou", "Me dá uma embalagem?"], "translations":["Can you package it to take?", "To take what was left over", "Give me a container?"], "notes":"Embalagem means packaging/container. Taking leftovers home is completely normal and common in Brazil — there's no social stigma around asking to pack your food." },
  { "d":3, "prompt":"Ask for a vegetarian option.", "answers":["Tem opção vegetariana?", "Tem algum prato sem carne?", "Menu vegetariano?"], "translations":["Do you have a vegetarian option?", "Do you have any dish without meat?", "Vegetarian menu?"], "notes":"Prato sem carne (dish without meat) is the safest wording. In cities, comida vegetariana is growing fast. Per-kilo (por quilo) restaurants often have the most vegetarian variety." },
  { "d":3, "prompt":"Ask what the most popular dish is.", "answers":["Qual é o mais popular?", "O que você recomenda?", "Qual o carro-chefe?"], "translations":["What is the most popular?", "What do you recommend?", "What is the flagship dish?"], "notes":"Carro-chefe (literally 'head car') means the signature or flagship dish — the thing a restaurant is known for. A very useful and impressive local vocabulary word." },
  { "d":3, "prompt":"Accept a server's dish recommendation.", "answers":["Ótimo vou querer esse!", "Então traz esse", "Vou levar esse obrigado/a"], "translations":["Great, I'll want that!", "Then bring that one", "I'll take that, thanks"], "notes":"Então traz esse (then bring that one) is very natural and decisive — Brazilians appreciate directness when ordering. Vou levar literally means 'I'll carry/take it.'" },
  { "d":3, "prompt":"Say you'll pay separately.", "answers":["Vamos pagar separado", "Cada um paga o seu", "Pode separar a conta?"], "translations":["We'll pay separately", "Each one pays their own", "Can you separate the bill?"], "notes":"Splitting evenly is called rachar a conta (to crack the bill). Pode separar a conta? is the formal request to get individual bills — not always possible in smaller restaurants." },
  { "d":3, "prompt":"The food is wrong. Politely say so.", "answers":["Desculpe acho que não é o meu pedido", "Não foi isso que pedi", "Acho que houve um engano"], "translations":["Excuse me, I think this is not my order", "That was not what I ordered", "I think there was a mistake"], "notes":"Acho que houve um engano (I think there was a mistake) frames it as a misunderstanding, not an accusation — very polite. Acho que (I think) softens any complaint in Brazil." },
  { "d":3, "prompt":"Compliment the food as you leave.", "answers":["Estava tudo delicioso! Obrigado/a", "A comida estava ótima", "Com certeza volto obrigado/a!"], "translations":["Was everything delicious! Thanks", "The food was great", "I'll certainly be back, thanks!"], "notes":"Com certeza volto (I'll certainly be back) is the ultimate compliment to a restaurant — it signals you'll return, which vendors and staff genuinely appreciate." },
  { "d":4, "prompt":"Ask about allergens — you're allergic to nuts.", "answers":["Tenho alergia a nozes tem?", "Sou alérgico/a a castanhas tem no prato?", "Tem frutos secos? Sou alérgico/a"], "translations":["I have allergy to walnuts, does it have any?", "I am allergic to nuts, is there any in the dish?", "Does it have dried fruits/nuts? I am allergic"], "notes":"Nozes = walnuts, castanhas = cashews/chestnuts, frutos secos = nuts/dried fruits generally. Always be specific about which nut you're allergic to for clarity." },
  { "d":4, "prompt":"Compliment the chef and ask if they'll pass on the message.", "answers":["Estava incrível pode passar a mensagem ao cozinheiro?", "Por favor diga ao chef que estava ótimo", "Pode dar os parabéns ao cozinheiro?"], "translations":["Was incredible, can you pass the message to the cook?", "Please tell the chef it was great", "Can you give congratulations to the cook?"], "notes":"Pode dar os parabéns ao cozinheiro? (can you give congratulations to the cook?) is a lovely phrase — parabéns means congratulations. Brazilians love this gesture of appreciation." }
];
