window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["shopping"] = [
  { "d":1, "prompt":"Staff greets you. You're just browsing.", "answers":["Só estou olhando", "Só dando uma olhada", "Obrigado/a só vou ver"], "translations":["Only I am looking", "Only giving a look", "Obliged only I'll see (just browsing)"] },
  { "d":1, "prompt":"Ask how much something is.", "answers":["Quanto custa?", "Qual é o preço?", "Quanto é?"], "translations":["How much costs?", "What is the price?", "How much is it?"] },
  { "d":1, "prompt":"You decided to buy it.", "answers":["Vou levar", "Quero esse", "Pode separar esse"], "translations":["I'll take it", "I want this one", "Can (you) set this one aside?"] },
  { "d":1, "prompt":"The item is too small.", "answers":["Ficou pequeno", "É pequeno demais", "Preciso de um maior"], "translations":["It is too small", "It is small too much", "I need a bigger one"] },
  { "d":1, "prompt":"The item is too big.", "answers":["Ficou grande", "É grande demais", "Preciso de um menor"], "translations":["It is too big", "It is big too much", "I need a smaller one"] },
  { "d":1, "prompt":"Ask if you can try it on.", "answers":["Posso experimentar?", "Onde fica o provador?", "Tem cabine?"], "translations":["Can I try?", "Where is the fitting room?", "Has fitting booth?"] },
  { "d":1, "prompt":"It fits perfectly!", "answers":["Ficou perfeito!", "É exatamente do meu tamanho!", "Assentou muito bem!"], "translations":["Fit perfectly!", "It is exactly of my size!", "Settled/fit very well!"] },
  { "d":2, "prompt":"Ask for a different color.", "answers":["Tem em outra cor?", "Há outras cores?", "Tem em azul / preto?"], "translations":["Has in another color?", "There are other colors?", "Has in blue / black?"] },
  { "d":2, "prompt":"Ask for a bigger size.", "answers":["Tem um tamanho maior?", "Tem no GG?", "Preciso de um tamanho acima"], "translations":["Has a bigger size?", "Has in XL?", "I need a size above"] },
  { "d":2, "prompt":"Ask if there's a sale on.", "answers":["Tem promoção?", "Está em oferta?", "Tem desconto?"], "translations":["Has promotion?", "Is on offer?", "Has discount?"] },
  { "d":2, "prompt":"Ask for gift wrapping.", "answers":["Pode embrulhar de presente?", "Embrulho de presente por favor", "Pode fazer embrulho?"], "translations":["Can (you) wrap as gift?", "Gift wrapping for favor", "Can (you) do wrapping?"] },
  { "d":2, "prompt":"Staff says they're sold out. Respond.", "answers":["Ah que pena", "Que chato", "Não tem mais mesmo?"], "translations":["Ah what a pity", "How annoying (lit: boring)", "Doesn't have more really?"] },
  { "d":2, "prompt":"Ask if they can order it for you.", "answers":["Podem encomendar pra mim?", "Dá para pedir?", "Quando chega mais?"], "translations":["Can (they) order for me?", "Gives to order? (can you order?)", "When arrives more?"] },
  { "d":3, "prompt":"Ask about the return policy.", "answers":["Qual é a política de trocas?", "Posso devolver se não gostar?", "Até quando posso trocar?"], "translations":["What is the policy of exchanges?", "Can I return if not like?", "Until when can I exchange?"] },
  { "d":3, "prompt":"Ask what material the item is made of.", "answers":["De que material é?", "Que tecido é esse?", "Qual é a composição?"], "translations":["Of what material is it?", "What fabric is this?", "What is the composition?"] },
  { "d":3, "prompt":"Ask for a discount if buying multiple items.", "answers":["Se eu comprar vários tem desconto?", "Desconto por quantidade?", "Se levar mais tem preço melhor?"], "translations":["If I buy various has discount?", "Discount by quantity?", "If take more has better price?"] },
  { "d":3, "prompt":"Exchange an item — wrong size.", "answers":["Posso trocar de tamanho?", "Quero trocar de tamanho", "Troca de tamanho por favor"], "translations":["Can I exchange size?", "I want to exchange size", "Exchange of size for favor"] },
  { "d":4, "prompt":"Ask for a gift receipt.", "answers":["É um presente tem recibo de troca?", "Recibo de presente por favor", "Pode me dar um recibo para presentes?"], "translations":["It is a gift has exchange receipt?", "Gift receipt for favor", "Can give-me a receipt for gifts?"] },
  { "d":4, "prompt":"Complain that the item broke after one use and ask for a refund.", "answers":["Quebrou na primeira vez quero meu dinheiro de volta", "Está com defeito quero o reembolso", "Usou uma vez e estragou pode reembolsar?"], "translations":["Broke on the first time I want my money back", "It is with defect I want the refund", "Used one time and broke can (you) reimburse?"] }
];
