window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["shopping"] = [
  { "d":1, "prompt":"Staff greets you. You're just browsing.", "answers":["Só estou olhando", "Só dando uma olhada", "Obrigado/a só vou ver"], "translations":["Only I am looking", "Only giving a look", "Thanks, I'll just look"], "notes":"Só estou olhando is the standard 'just browsing' phrase. Brazilian staff will still hover nearby — a smile and Obrigado/a keeps things friendly without committing to anything." },
  { "d":1, "prompt":"Ask how much something is.", "answers":["Quanto custa?", "Qual é o preço?", "Quanto é?"], "translations":["How much does it cost?", "What is the price?", "How much is it?"], "notes":"Quanto é? (how much is it?) is shortest and most casual. In shopping malls, prices are tagged. In markets and smaller shops, always ask — prices can sometimes be negotiable." },
  { "d":1, "prompt":"You decided to buy it.", "answers":["Vou levar", "Quero esse", "Pode separar esse"], "translations":["I'll take it", "I want this one", "Can you set this one aside?"], "notes":"Pode separar esse? (can you set this aside?) is useful if you want to keep browsing. Vou levar (I'll take it) is the final commitment — from levar, to carry/take." },
  { "d":1, "prompt":"The item is too small.", "answers":["Ficou pequeno", "É pequeno demais", "Preciso de um maior"], "translations":["It came out small (it's too small)", "It is too small", "I need a bigger one"], "notes":"Ficou pequeno — ficou is from ficar (to become/stay), used for how something fits. Ficou largo (too wide), ficou curto (too short) — ficar is your essential fitting-room verb." },
  { "d":1, "prompt":"The item is too big.", "answers":["Ficou grande", "É grande demais", "Preciso de um menor"], "translations":["It came out big (it's too big)", "It is too big", "I need a smaller one"], "notes":"Ficou grande — same ficou construction. Demais (too much) intensifies any adjective. Ficou + adjective is by far the most natural way to describe fit in a Brazilian store." },
  { "d":1, "prompt":"Ask if you can try it on.", "answers":["Posso experimentar?", "Onde fica o provador?", "Tem cabine?"], "translations":["Can I try it?", "Where is the fitting room?", "Is there a fitting booth?"], "notes":"Provador (fitting room) comes from provar (to try/taste) — same verb for tasting food and trying on clothes. Tem cabine? (Is there a booth?) is the simplest way to ask." },
  { "d":1, "prompt":"It fits perfectly!", "answers":["Ficou perfeito!", "É exatamente do meu tamanho!", "Assentou muito bem!"], "translations":["It fit perfectly!", "It is exactly my size!", "It settled/fit very well!"], "notes":"Ficou perfeito! — again the key verb ficar. Assentou (from assentar, to sit/settle) is a more elegant way to say something fits well. Both are natural and widely used." },
  { "d":2, "prompt":"Ask for a different color.", "answers":["Tem em outra cor?", "Há outras cores?", "Tem em azul / preto?"], "translations":["Do you have it in another color?", "Are there other colors?", "Do you have it in blue / black?"], "notes":"Cor (color) is feminine — essa cor (this color), outra cor (another color). Colors: azul (blue), preto (black), vermelho (red), branco (white), verde (green), amarelo (yellow)." },
  { "d":2, "prompt":"Ask for a bigger size.", "answers":["Tem um tamanho maior?", "Tem no GG?", "Preciso de um tamanho acima"], "translations":["Do you have a bigger size?", "Do you have it in XL?", "I need a size above"], "notes":"Brazilian sizing: PP (extra small), P (small), M (medium), G (large), GG (extra large), XGG (XXL). GGG also exists! It's a completely different system from EU or US sizing." },
  { "d":2, "prompt":"Ask if there's a sale on.", "answers":["Tem promoção?", "Está em oferta?", "Tem desconto?"], "translations":["Is there a promotion/sale?", "Is it on offer?", "Is there a discount?"], "notes":"Promoção in Brazil means both 'promotion' and 'sale/discount' — any discounted item qualifies. Está em oferta? and Tem desconto? are equally natural alternatives." },
  { "d":2, "prompt":"Ask for gift wrapping.", "answers":["Pode embrulhar de presente?", "Embrulho de presente por favor", "Pode fazer embrulho?"], "translations":["Can you wrap it as a gift?", "Gift wrapping, please", "Can you do a wrapping?"], "notes":"Embrulhar means to wrap. Gift wrapping is widely offered in Brazilian stores — often free during festive seasons like Natal (Christmas) and Dia das Mães (Mother's Day)." },
  { "d":2, "prompt":"Staff says they're sold out. Respond.", "answers":["Ah que pena", "Que chato", "Não tem mais mesmo?"], "translations":["Ah, what a pity", "How annoying (lit: boring/flat)", "Really doesn't have more?"], "notes":"Que chato! literally means 'how boring/flat' but is used to mean 'what a shame' or 'how annoying' — like 'that's a bummer.' Esgotado is the technical word for sold out." },
  { "d":2, "prompt":"Ask if they can order it for you.", "answers":["Podem encomendar pra mim?", "Dá para pedir?", "Quando chega mais?"], "translations":["Can they order it for me?", "Is it possible to order?", "When does more arrive?"], "notes":"Encomendar means to order/commission something specially. Quando chega mais? (When does more arrive?) is great if you can come back — staff genuinely appreciate the commitment." },
  { "d":3, "prompt":"Ask about the return policy.", "answers":["Qual é a política de trocas?", "Posso devolver se não gostar?", "Até quando posso trocar?"], "translations":["What is the exchange policy?", "Can I return it if I don't like it?", "Until when can I exchange it?"], "notes":"In Brazil you typically have 30 days to exchange items with a receipt (nota fiscal). The Código de Defesa do Consumidor (Consumer Protection Code) gives shoppers strong rights." },
  { "d":3, "prompt":"Ask what material the item is made of.", "answers":["De que material é?", "Que tecido é esse?", "Qual é a composição?"], "translations":["What material is it?", "What fabric is this?", "What is the composition?"], "notes":"Tecido means fabric/cloth. Composição (composition) on clothing labels shows the blend: algodão (cotton), poliéster (polyester), couro (leather), linho (linen), seda (silk)." },
  { "d":3, "prompt":"Ask for a discount if buying multiple items.", "answers":["Se eu comprar vários tem desconto?", "Desconto por quantidade?", "Se levar mais tem preço melhor?"], "translations":["If I buy several, is there a discount?", "Discount by quantity?", "If I take more, is there a better price?"], "notes":"Se levar mais tem preço melhor? is natural negotiation phrasing at smaller Brazilian shops. The worst they say is não — in many shops and markets this is completely expected." },
  { "d":3, "prompt":"Exchange an item — wrong size.", "answers":["Posso trocar de tamanho?", "Quero trocar de tamanho", "Troca de tamanho por favor"], "translations":["Can I exchange the size?", "I want to exchange the size", "Size exchange, please"], "notes":"Troca (exchange) is the key word for any return or exchange in Brazil. Keep your nota fiscal (official receipt) — it's legally required for exchanges and protects your consumer rights." },
  { "d":4, "prompt":"Ask for a gift receipt.", "answers":["É um presente tem recibo de troca?", "Recibo de presente por favor", "Pode me dar um recibo para presentes?"], "translations":["It's a gift, do you have an exchange receipt?", "Gift receipt, please", "Can you give me a receipt for gifts?"], "notes":"Recibo de troca (exchange receipt) is what you need for gift purchases. The nota fiscal (official tax receipt) is the most important document for any return or exchange in Brazil." },
  { "d":4, "prompt":"Complain that the item broke after one use and ask for a refund.", "answers":["Quebrou na primeira vez quero meu dinheiro de volta", "Está com defeito quero o reembolso", "Usou uma vez e estragou pode reembolsar?"], "translations":["Broke the first time, I want my money back", "It has a defect, I want the refund", "Used once and it broke, can you reimburse?"], "notes":"Com defeito (with defect/faulty) is the key phrase. Reembolso (reimbursement) is the formal word for refund. Brazil's consumer protection law is strong — know your rights." }
];
