window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["small_talk"] = [
  { "d":1, "prompt":"Ask how someone is (casual).", "answers":["Tudo bem?", "Tudo bom?", "Como vai?"], "translations":["Everything well?", "Everything good?", "How goes?"], "notes":"Tudo bem? (everything well?) is both a greeting AND a question in Brazil. The reply is often just Tudo! (everything!) — meaning all is good. It's the social lubricant of Brazilian Portuguese." },
  { "d":1, "prompt":"Reply that everything is great.", "answers":["Tudo bem!", "Tudo ótimo!", "Tô bem, valeu!"], "translations":["Everything well!", "Everything great!", "I'm well, thanks! (informal)"], "notes":"Tô is a very common contraction of estou — used constantly in casual speech. Valeu (worth it/thanks) is extremely informal and friendly, like 'cheers' in English." },
  { "d":1, "prompt":"Say it's very hot today.", "answers":["Que calor hoje!", "Tá um calor!", "Hoje tá quente demais!"], "translations":["What heat today!", "It's a heat! (informal)", "Today it's too hot!"], "notes":"Brazilians talk about heat constantly — it's a major small talk topic! Tá um calor! drops the subject entirely, which is natural in casual speech. Quente = 'KEN-chi' (not 'KEN-teh')." },
  { "d":1, "prompt":"Say the weather is beautiful.", "answers":["Que dia lindo!", "Que tempo gostoso!", "Dia perfeito!"], "translations":["What a beautiful day!", "What nice/pleasant weather!", "Perfect day!"], "notes":"Gostoso/a (tasty/pleasant) is wonderfully versatile in Brazil — used for food, weather, music, and experiences. Que tempo gostoso! (what pleasant weather!) is very distinctly Brazilian." },
  { "d":1, "prompt":"Say you're very hungry.", "answers":["Estou com muita fome!", "Tô morrendo de fome!", "Que fome!"], "translations":["I am with much hunger!", "I'm dying of hunger!", "What hunger!"], "notes":"Tô morrendo de fome! (I'm dying of hunger!) is a classic Brazilian hyperbole. Brazilians love dramatic food expressions — and they're always used warmly, never literally." },
  { "d":1, "prompt":"Say you're tired.", "answers":["Estou cansado/a", "Tô morto/a de cansaço", "Que canseira!"], "translations":["I am tired", "I'm dead of tiredness", "What tiredness!"], "notes":"Tô morto/a de cansaço (I'm dead tired) — -o for male, -a for female. Brazilians use death metaphors for tiredness and hunger all the time — it's expressive, not dramatic." },
  { "d":1, "prompt":"Agree enthusiastically.", "answers":["Com certeza!", "Exatamente!", "É isso mesmo!"], "translations":["With certainty!", "Exactly!", "That's it exactly!"], "notes":"É isso mesmo! (that's it exactly!) is very satisfying to say and very Brazilian. Brazilians value enthusiastic agreement — it shows you're fully engaged and listening." },
  { "d":1, "prompt":"Express surprise.", "answers":["Nossa!", "Caramba!", "Sério?!"], "translations":["Our Lady! (wow/wow!)", "Dang! / Wow!", "Serious? / Really?!"], "notes":"Nossa! is uniquely Brazilian — short for Nossa Senhora (Our Lady) but now just an exclamation like 'wow!' Caramba! is a mild euphemism (originally stronger). Both are totally appropriate." },
  { "d":1, "prompt":"Say you don't know.", "answers":["Não sei", "Não faço ideia", "Sei lá!"], "translations":["I don't know", "I don't make/have an idea", "Know there! (no idea)"], "notes":"Sei lá! (literally 'know there!') is uniquely Brazilian — meaning 'I have no idea' with a casual shrug. Very commonly used in everyday speech, especially among younger Brazilians." },
  { "d":1, "prompt":"Say something is very good.", "answers":["Que bom!", "Ótimo!", "Demais!"], "translations":["How good!", "Great!", "Too much! (awesome)"], "notes":"Demais! (too much!) is used positively in Brazil — meaning 'awesome!' or 'amazing!' It started as slang but is now completely mainstream. Ótimo (great) comes from óptimo (optimal)." },
  { "d":2, "prompt":"Ask what someone's been up to.", "answers":["O que você tem feito?", "E aí, como tem sido?", "O que há de novo?"], "translations":["What have you been doing?", "And there, how has it been?", "What's new?"], "notes":"E aí? (And there?) is the ultra-casual Brazilian opener — like 'so what's up?' or 'hey!' O que há de novo? (What's new?) is slightly more formal but equally natural." },
  { "d":2, "prompt":"Say you've been busy.", "answers":["Tenho estado muito ocupado/a", "Andei correndo muito", "Fui a mil essa semana!"], "translations":["I have been very busy", "I've been running a lot", "I went to a thousand this week! (super busy)"], "notes":"Fui a mil essa semana! (I went to a thousand this week!) means you've been going full speed. Mil (thousand) in Brazil signals maximum intensity — a very expressive idiom." },
  { "d":2, "prompt":"Say the food was delicious.", "answers":["Que delícia!", "Estava uma delícia!", "Que saboroso!"], "translations":["What delight!", "It was a delight!", "How tasty!"], "notes":"Que delícia! is one of the most useful phrases in all of Brazilian Portuguese — works for food, news, weather, a song, anything wonderful. Use it freely and you'll sound very natural." },
  { "d":2, "prompt":"Say you love it here.", "answers":["Estou adorando aqui!", "Esse lugar é incrível!", "Não quero ir embora!"], "translations":["I am loving it here!", "This place is incredible!", "I don't want to go away!"], "notes":"Não quero ir embora! (I don't want to leave!) is the highest compliment you can give a place or a city. Brazilians will be genuinely touched by this." },
  { "d":2, "prompt":"React to good news someone shares.", "answers":["Que ótimo!", "Que notícia incrível!", "Não acredito, que bom!"], "translations":["How great!", "What incredible news!", "I don't believe it, how good!"], "notes":"Não acredito! (I don't believe it!) is an exclamation of pleasant surprise — not actual disbelief. Brazilians use it to signal they're happily shocked by good news." },
  { "d":2, "prompt":"Say something is very cheap.", "answers":["Que barato!", "Muito em conta!", "Baratíssimo!"], "translations":["How cheap!", "Very affordable!", "Very cheapest!"], "notes":"Baratíssimo uses the superlative suffix -íssimo (very + adjective) — a very productive suffix in Portuguese. Muito em conta (very affordable) is a more polished way to say the same thing." },
  { "d":2, "prompt":"Ask if they've tried local food.", "answers":["Você já provou a comida local?", "Já experimentou as comidas típicas?", "O que você já comeu aqui?"], "translations":["Have you already tasted the local food?", "Have you tried the typical foods?", "What have you already eaten here?"], "notes":"Comida típica (typical/local food) signals you want the real deal, not tourist food. Asking this opens great foodie conversations — Brazilians are passionate about their regional cuisine." },
  { "d":3, "prompt":"Say you've been exploring the city.", "answers":["Tenho explorado a cidade toda", "Andei muito a pé conhecendo o lugar", "Já fui a vários lugares diferentes"], "translations":["I have explored the whole city", "I walked a lot getting to know the place", "I already went to various different places"], "notes":"Andei muito a pé (I walked a lot on foot) — andei is the past tense of andar (to walk/get around). Very natural for describing city exploration. Conhecendo (getting to know) is a lovely word." },
  { "d":3, "prompt":"Ask for a local tip nobody tells tourists.", "answers":["Me dá uma dica de lugar que só local conhece?", "Tem algum lugar escondido que vale a pena?", "O que turista não sabe que deveria saber?"], "translations":["Give me a tip for a place only locals know?", "Is there a hidden place worth it?", "What don't tourists know that they should know?"], "notes":"Lugar que só local conhece (a place only locals know) — this phrase signals you want authentic tips, not tourist traps. Brazilians love sharing hidden gems and will be genuinely enthusiastic." },
  { "d":3, "prompt":"Say you prefer it here over where you live.", "answers":["Honestamente prefiro aqui ao meu país", "É bem diferente de onde moro, mas adoro", "A qualidade de vida aqui me surpreendeu"], "translations":["Honestly I prefer here to my country", "It's quite different from where I live, but I love it", "The quality of life here surprised me"], "notes":"A qualidade de vida aqui me surpreendeu (the quality of life here surprised me) is a thoughtful, sincere observation. Brazilians appreciate when visitors notice things beyond the surface." },
  { "d":3, "prompt":"React to something amazing you just saw.", "answers":["Nunca vi nada assim!", "Que experiência incrível!", "Isso foi surreal, não acredito!"], "translations":["Never saw anything like this!", "What an incredible experience!", "This was surreal, I can't believe it!"], "notes":"Nunca vi nada assim! (I've never seen anything like this!) is emphatic and genuine. Surreal is used in Brazilian Portuguese exactly like English — for something so extraordinary it feels unreal." },
  { "d":4, "prompt":"Compare something to your home country.", "answers":["No meu país é bem diferente, mas gosto muito de como é aqui", "Tem coisas aqui que não existem onde moro e vice-versa", "Acho que cada cultura tem seu charme único"], "translations":["In my country it's quite different, but I like how it is here", "There are things here that don't exist where I live and vice-versa", "I think each culture has its unique charm"], "notes":"Cada cultura tem seu charme único (each culture has its unique charm) is a diplomatic and genuinely true way to compare without offending — Brazilians appreciate this balanced perspective." },
  { "d":4, "prompt":"Have a genuine exchange about cultural differences.", "answers":["O que mais me surpreendeu foi a abertura das pessoas aqui", "Aprendi muito sobre minha própria cultura ao compará-la com a daqui", "Culturalmente é fascinante como as prioridades são tão diferentes"], "translations":["What most surprised me was the openness of the people here", "I learned a lot about my own culture comparing it with the one here", "Culturally it's fascinating how the priorities are so different"], "notes":"Aprendi muito sobre minha própria cultura (I learned a lot about my own culture) — this kind of reflection really resonates with Brazilians who value genuine cultural exchange over superficial tourism." }
];
