window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["small_talk"] = [
  { "d":1, "prompt":"Ask how someone is (casual).", "answers":["Tudo bem?", "Tudo bom?", "Como vai?"], "translations":["Everything well?", "Everything good?", "How goes?"] },
  { "d":1, "prompt":"Reply that everything is great.", "answers":["Tudo bem!", "Tudo ótimo!", "Tô bem, valeu!"], "translations":["Everything well!", "Everything great!", "I'm well, thanks! (informal)"] },
  { "d":1, "prompt":"Say it's very hot today.", "answers":["Que calor hoje!", "Tá um calor!", "Hoje tá quente demais!"], "translations":["What heat today!", "It's a heat!", "Today it's hot too much!"] },
  { "d":1, "prompt":"Say the weather is beautiful.", "answers":["Que dia lindo!", "Que tempo gostoso!", "Dia perfeito!"], "translations":["What a beautiful day!", "What nice/pleasant weather!", "Perfect day!"] },
  { "d":1, "prompt":"Say you're very hungry.", "answers":["Estou com muita fome!", "Tô morrendo de fome!", "Que fome!"], "translations":["I am with much hunger!", "I'm dying of hunger!", "What hunger!"] },
  { "d":1, "prompt":"Say you're tired.", "answers":["Estou cansado/a", "Tô morto/a de cansaço", "Que canseira!"], "translations":["I am tired", "I'm dead of tiredness", "What tiredness!"] },
  { "d":1, "prompt":"Agree enthusiastically.", "answers":["Com certeza!", "Exatamente!", "É isso mesmo!"], "translations":["With certainty!", "Exactly!", "That's it exactly!"] },
  { "d":1, "prompt":"Express surprise.", "answers":["Nossa!", "Caramba!", "Sério?!"], "translations":["Our! (exclamation)", "Dang!/Wow!", "Serious?! / Really?!"] },
  { "d":1, "prompt":"Say you don't know.", "answers":["Não sei", "Não faço ideia", "Sei lá!"], "translations":["I don't know", "I don't make (have) an idea", "Know there! (no idea, informal)"] },
  { "d":1, "prompt":"Say something is very good.", "answers":["Que bom!", "Ótimo!", "Demais!"], "translations":["How good!", "Optimal/Great!", "Too much! (awesome, informal)"] },
  { "d":2, "prompt":"Ask what someone's been up to.", "answers":["O que você tem feito?", "E aí, como tem sido?", "O que há de novo?"], "translations":["What you have done?", "And there, how has it been?", "What has of new?"] },
  { "d":2, "prompt":"Say you've been busy.", "answers":["Tenho estado muito ocupado/a", "Andei correndo muito", "Fui a mil essa semana!"], "translations":["I have been very busy", "I've been running a lot", "I went to a thousand this week! (super busy)"] },
  { "d":2, "prompt":"Say the food was delicious.", "answers":["Que delícia!", "Estava uma delícia!", "Que saboroso!"], "translations":["What delight!", "It was a delight!", "How tasty!"] },
  { "d":2, "prompt":"Say you love it here.", "answers":["Estou adorando aqui!", "Esse lugar é incrível!", "Não quero ir embora!"], "translations":["I am loving here!", "This place is incredible!", "I don't want to go away!"] },
  { "d":2, "prompt":"React to good news someone shares.", "answers":["Que ótimo!", "Que notícia incrível!", "Não acredito, que bom!"], "translations":["How great!", "What incredible news!", "I don't believe it, how good!"] },
  { "d":2, "prompt":"Say something is very cheap.", "answers":["Que barato!", "Muito em conta!", "Baratíssimo!"], "translations":["How cheap!", "Very in account/affordable!", "Very cheapest!"] },
  { "d":2, "prompt":"Ask if they've tried local food.", "answers":["Você já provou a comida local?", "Já experimentou as comidas típicas?", "O que você já comeu aqui?"], "translations":["You already tasted the local food?", "Already tried the typical foods?", "What you already ate here?"] },
  { "d":3, "prompt":"Say you've been exploring the city.", "answers":["Tenho explorado a cidade toda", "Andei muito a pé conhecendo o lugar", "Já fui a vários lugares diferentes"], "translations":["I have explored the whole city", "I walked a lot on foot getting-to-know the place", "Already went to various different places"] },
  { "d":3, "prompt":"Ask for a local tip nobody tells tourists.", "answers":["Me dá uma dica de lugar que só local conhece?", "Tem algum lugar escondido que vale a pena?", "O que turista não sabe que deveria saber?"], "translations":["Give-me a tip of place that only local knows?", "Has some hidden place that is worth it?", "What tourist doesn't know that should know?"] },
  { "d":3, "prompt":"Say you prefer it here over where you live.", "answers":["Honestamente prefiro aqui ao meu país", "É bem diferente de onde moro, mas adoro", "A qualidade de vida aqui me surpreendeu"], "translations":["Honestly I prefer here to my country", "It's quite different from where I live, but I love it", "The quality of life here surprised me"] },
  { "d":3, "prompt":"React to something amazing you just saw.", "answers":["Nunca vi nada assim!", "Que experiência incrível!", "Isso foi surreal, não acredito!"], "translations":["Never saw nothing like this!", "What incredible experience!", "This was surreal, I don't believe it!"] },
  { "d":4, "prompt":"Compare something to your home country.", "answers":["No meu país é bem diferente, mas gosto muito de como é aqui", "Tem coisas aqui que não existem onde moro e vice-versa", "Acho que cada cultura tem seu charme único"], "translations":["In my country it's quite different, but I like a lot how it is here", "There are things here that don't exist where I live and vice-versa", "I think each culture has its unique charm"] },
  { "d":4, "prompt":"Have a genuine exchange about cultural differences.", "answers":["O que mais me surpreendeu foi a abertura das pessoas aqui", "Aprendi muito sobre minha própria cultura ao compará-la com a daqui", "Culturalmente é fascinante como as prioridades são tão diferentes"], "translations":["What most surprised me was the openness of the people here", "I learned a lot about my own culture comparing-it with the one from here", "Culturally it is fascinating how the priorities are so different"] }
];
