window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["social"] = [
  { "d":1, "prompt":"Say good luck!", "answers":["Boa sorte!", "Vai com tudo!", "Confia!"], "translations":["Good luck!", "Go with everything!", "Trust (it)!"], "notes":"Vai com tudo! (go with everything!) is a high-energy Brazilian encouragement — meaning 'give it your all!' Confia! (trust it! / believe in yourself!) is short, punchy, and very warm." },
  { "d":1, "prompt":"Say me too / same here.", "answers":["Eu também!", "Igualmente!", "Comigo também!"], "translations":["I also!", "Likewise!", "With me also!"], "notes":"Igualmente (likewise) is also the standard reply to Prazer (nice to meet you) — it's a versatile word. Eu também is the simplest and works in any context." },
  { "d":1, "prompt":"Agree enthusiastically: Exactly! That's right!", "answers":["Exatamente!", "Claro!", "Isso mesmo!"], "translations":["Exactly!", "Of course!", "That itself! (that's right)"], "notes":"Isso mesmo! (that itself/exactly that!) is very Brazilian — isso (this/that) is used as a strong affirmation. Claro! (clear/of course!) is equally common for enthusiastic agreement." },
  { "d":1, "prompt":"Say that's a great idea!", "answers":["Que boa ideia!", "Ótima ideia!", "Que ideia incrível!"], "translations":["What a good idea!", "Great idea!", "What an incredible idea!"], "notes":"Incrível (incredible) is used constantly in Brazilian Portuguese for anything impressive or exciting. Que boa ideia! is the most natural, casual version for everyday conversation." },
  { "d":1, "prompt":"Compliment someone who looks nice today.", "answers":["Você está ótimo/a hoje!", "Que linda roupa!", "Você está muito bonito/a hoje!"], "translations":["You are great today!", "What beautiful clothing!", "You are very pretty/handsome today!"], "notes":"Brazilians are very open with appearance compliments — it's considered warm and friendly, not inappropriate. Bonito/a (pretty/handsome) — -o for men, -a for women. Linda roupa = beautiful outfit." },
  { "d":1, "prompt":"Someone made you laugh. React.", "answers":["Que engraçado!", "Hahaha tô rindo!", "Isso foi muito bom!"], "translations":["How funny!", "Hahaha, I'm laughing!", "That was very good!"], "notes":"Engraçado means funny/amusing — pronounced 'en-gra-SAH-do.' Tô rindo! (I'm laughing!) is very expressive and natural. Brazilians love humor and laugh easily — lean into it." },
  { "d":2, "prompt":"Say I'm so happy to meet you.", "answers":["Fico muito feliz em te conhecer", "Prazer em te conhecer", "Estou muito feliz de te conhecer"], "translations":["I stay/become very happy to know you", "Pleasure in knowing you", "I am very happy to know you"], "notes":"Fico muito feliz uses ficar (to become/stay) — one of the most important verbs in Brazilian Portuguese, expressing a state change. Fico feliz = I become happy. Te = informal 'you.'" },
  { "d":2, "prompt":"Say don't worry about it.", "answers":["Não se preocupe", "Não tem problema", "Fique tranquilo/a"], "translations":["Don't worry yourself", "No problem", "Stay calm/relaxed"], "notes":"Fique tranquilo/a (stay calm) is very warm and reassuring — -o/-a for gender. Não se preocupe (don't worry yourself) is the standard. Brazilians find visible anxiety socially uncomfortable — reassurance is valued." },
  { "d":2, "prompt":"Say I really enjoyed today.", "answers":["Me diverti muito hoje!", "Foi um dia incrível!", "Hoje foi ótimo!"], "translations":["I amused myself a lot today!", "It was an incredible day!", "Today was great!"], "notes":"Me diverti muito (I amused myself a lot) — divirtir-se is the reflexive verb for enjoying yourself/having fun. Always the natural phrase for saying you had a great time." },
  { "d":2, "prompt":"Someone shares good news. React with excitement.", "answers":["Que notícia incrível!", "Não acredito!", "Que legal!"], "translations":["What incredible news!", "I don't believe it!", "How cool!"], "notes":"Que legal! (how cool!) is the quintessential Brazilian exclamation — legal literally means 'legal/lawful' but means cool/awesome in Brazilian slang. Não acredito! is excitement, not literal disbelief." },
  { "d":2, "prompt":"Say you're so kind to someone who did something nice.", "answers":["Você é muito gentil!", "Que gentileza!", "Muito atencioso/a!"], "translations":["You are very kind!", "What kindness!", "Very attentive/caring!"], "notes":"Gentileza (kindness) is a beautiful word in Brazilian culture — there's even a famous Rio street artist known as 'O Profeta da Gentileza.' Atencioso/a (attentive) suggests thoughtful, considered care." },
  { "d":2, "prompt":"Encourage someone nervous before a presentation.", "answers":["Vai arrasar!", "Você consegue!", "Confia vai dar tudo certo!"], "translations":["You'll smash it! (lit: you'll tear down)", "You can do it!", "Trust, it'll all work out!"], "notes":"Vai arrasar! (you'll smash it!) literally means 'you'll tear it down' — used for totally crushing/nailing something. Very high energy. Você consegue! (you can do it!) is warm and simple." },
  { "d":3, "prompt":"Say take care of yourself.", "answers":["Cuida-se!", "Se cuida!", "Tome cuidado!"], "translations":["Take care of yourself!", "Take care of yourself! (informal)", "Take care!"], "notes":"Se cuida and Cuida-se are the same phrase — reflexive cuida in two positions. Se cuida is more casual and very common. Tome cuidado (take care) is slightly more formal." },
  { "d":3, "prompt":"Say let's do this again!", "answers":["Vamos repetir!", "Que não seja a última!", "Combinamos de repetir!"], "translations":["Let's repeat!", "May it not be the last!", "We agreed to repeat!"], "notes":"Que não seja a última! (May it not be the last!) is a beautiful, genuinely Brazilian phrase — expressing the hope that this won't be the last time you see each other. Very heartfelt." },
  { "d":3, "prompt":"Thank someone genuinely — beyond just thank you.", "answers":["Muito obrigado/a mesmo", "Não sabe o quanto significa pra mim", "Te agradeço de coração"], "translations":["Very thank you indeed", "Doesn't know how much it means to me", "I thank you from the heart"], "notes":"De coração (from the heart) is used in Brazil for deep, sincere expressions. Te agradeço de coração is the most heartfelt thank-you available — reserve it for when you really mean it." },
  { "d":3, "prompt":"Say I'm proud of you.", "answers":["Estou muito orgulhoso/a de você!", "Você me deixa orgulhoso/a!", "Muito orgulhoso/a!"], "translations":["I am very proud of you!", "You make me proud!", "Very proud!"], "notes":"Você me deixa orgulhoso/a — deixar + adjective means 'to make someone feel.' Deixa-me feliz = makes me happy. Orgulhoso/a (proud) — -o/-a for gender. A very warm and generous phrase to give." },
  { "d":4, "prompt":"Say I believe in you!", "answers":["Acredito em você!", "Sei que você consegue!", "Tenho plena fé em você!"], "translations":["I believe in you!", "I know you can do it!", "I have full faith in you!"], "notes":"Tenho plena fé em você (I have full faith in you) is strong and sincere — plena (full/complete) intensifies it. Brazilians aren't shy about expressing belief in each other openly." },
  { "d":4, "prompt":"Make a self-deprecating joke about your language ability.", "answers":["Meu português melhora muito com uma cerveja!", "Falo melhor quando ninguém está prestando atenção", "Na minha cabeça é perfeito!"], "translations":["My Portuguese improves a lot with a beer!", "I speak better when nobody is paying attention", "In my head it is perfect!"], "notes":"Na minha cabeça é perfeito! (In my head it's perfect!) is a universally relatable language-learner joke — Brazilians will absolutely love it and laugh with you, not at you." },
  { "d":4, "prompt":"Respond humbly to a compliment and return it.", "answers":["Que nada! Você é muito melhor", "Obrigado/a mas você é quem realmente se destaca", "Exagero da sua parte você é que é incrível!"], "translations":["No way! You are much better", "Thank you, but you are the one who really stands out", "Exaggeration on your part, you are the one who is incredible!"], "notes":"Que nada! (nothing at all! / no way!) is how Brazilians deflect compliments. Exagero da sua parte (exaggeration on your part) is playful and warm — a great back-and-forth compliment exchange." }
];
