window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["social"] = [
  { "d":1, "prompt":"Say good luck!", "answers":["Boa sorte!", "Vai com tudo!", "Confia!"], "translations":["Good luck!", "Go with everything!", "Trust (it)!"] },
  { "d":1, "prompt":"Say me too / same here.", "answers":["Eu também!", "Igualmente!", "Comigo também!"], "translations":["I also!", "Equally/Likewise!", "With me also!"] },
  { "d":1, "prompt":"Agree enthusiastically: Exactly! That's right!", "answers":["Exatamente!", "Claro!", "Isso mesmo!"], "translations":["Exactly!", "Clear/Of course!", "That itself! (that's right)"] },
  { "d":1, "prompt":"Say that's a great idea!", "answers":["Que boa ideia!", "Ótima ideia!", "Que ideia incrível!"], "translations":["What good idea!", "Great idea!", "What incredible idea!"] },
  { "d":1, "prompt":"Compliment someone who looks nice today.", "answers":["Você está ótimo/a hoje!", "Que linda roupa!", "Você está muito bonito/a hoje!"], "translations":["You are great today!", "What beautiful clothing!", "You are very pretty/handsome today!"] },
  { "d":1, "prompt":"Someone made you laugh. React.", "answers":["Que engraçado!", "Hahaha tô rindo!", "Isso foi muito bom!"], "translations":["How funny!", "Hahaha I'm laughing!", "That was very good!"] },
  { "d":2, "prompt":"Say I'm so happy to meet you.", "answers":["Fico muito feliz em te conhecer", "Prazer em te conhecer", "Estou muito feliz de te conhecer"], "translations":["I stay very happy to know you (meet you)", "Pleasure in knowing you", "I am very happy to know you (meet you)"] },
  { "d":2, "prompt":"Say don't worry about it.", "answers":["Não se preocupe", "Não tem problema", "Fique tranquilo/a"], "translations":["Don't worry-yourself", "No problem", "Stay calm"] },
  { "d":2, "prompt":"Say I really enjoyed today.", "answers":["Me diverti muito hoje!", "Foi um dia incrível!", "Hoje foi ótimo!"], "translations":["I amused myself a lot today!", "Was an incredible day!", "Today was great!"] },
  { "d":2, "prompt":"Someone shares good news. React with excitement.", "answers":["Que notícia incrível!", "Não acredito!", "Que legal!"], "translations":["What incredible news!", "I don't believe it!", "How cool! (Brazilian slang)"] },
  { "d":2, "prompt":"Say you're so kind to someone who did something nice.", "answers":["Você é muito gentil!", "Que gentileza!", "Muito atencioso/a!"], "translations":["You are very kind!", "What kindness!", "Very attentive/caring!"] },
  { "d":2, "prompt":"Encourage someone nervous before a presentation.", "answers":["Vai arrasar!", "Você consegue!", "Confia vai dar tudo certo!"], "translations":["You'll smash it! (lit: you'll tear down)", "You manage it! (you can do it)", "Trust it'll all work out!"] },
  { "d":3, "prompt":"Say take care of yourself.", "answers":["Cuida-se!", "Se cuida!", "Tome cuidado!"], "translations":["Take care of yourself!", "Take care of yourself! (informal)", "Take care!"] },
  { "d":3, "prompt":"Say let's do this again!", "answers":["Vamos repetir!", "Que não seja a última!", "Combinamos de repetir!"], "translations":["Let's repeat!", "May it not be the last!", "We agreed to repeat!"] },
  { "d":3, "prompt":"Thank someone genuinely — beyond just thank you.", "answers":["Muito obrigado/a mesmo", "Não sabe o quanto significa pra mim", "Te agradeço de coração"], "translations":["Very obliged indeed", "Doesn't know how much it means to me", "I thank you from the heart"] },
  { "d":3, "prompt":"Say I'm proud of you.", "answers":["Estou muito orgulhoso/a de você!", "Você me deixa orgulhoso/a!", "Muito orgulhoso/a!"], "translations":["I am very proud of you!", "You leave me proud!", "Very proud!"] },
  { "d":4, "prompt":"Say I believe in you!", "answers":["Acredito em você!", "Sei que você consegue!", "Tenho plena fé em você!"], "translations":["I believe in you!", "I know you can do it!", "I have full faith in you!"] },
  { "d":4, "prompt":"Make a self-deprecating joke about your language ability.", "answers":["Meu [language] melhora muito com uma cerveja!", "Falo melhor quando ninguém está prestando atenção", "Na minha cabeça é perfeito!"], "translations":["My [language] improves a lot with a beer!", "I speak better when nobody is paying attention", "In my head it is perfect!"] },
  { "d":4, "prompt":"Respond humbly to a compliment and return it.", "answers":["Que nada! Você é muito melhor", "Obrigado/a mas você é quem realmente se destaca", "Exagero da sua parte você é que é incrível!"], "translations":["No way! You are much better", "Obliged but you are the one who really stands out", "Exaggeration on your part you are the one who is incredible!"] }
];
