window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["taxi"] = [
  { "d":1, "prompt":"You get in. Say where you're going.", "answers":["Para [destination] por favor", "Vou para [destination]", "Leva-me a [destination]"], "translations":["To [destination], please", "I'm going to [destination]", "Take me to [destination]"], "notes":"Leva-me a [destination] (take me to) is very direct and clear. Brazilian taxi and Uber drivers expect a clear destination name or address — just say it confidently." },
  { "d":1, "prompt":"Say please stop here.", "answers":["Para aqui por favor", "Pode parar aqui", "Aqui está ótimo"], "translations":["Stop here, please", "Can you stop here?", "Here is fine"], "notes":"Aqui está ótimo (here is fine) is polite and warm. Para aqui is more direct. Both are commonly used — drivers won't be surprised by either." },
  { "d":1, "prompt":"Ask if they accept card.", "answers":["Aceita cartão?", "Pode pagar no cartão?", "Tem maquininha?"], "translations":["Do you accept card?", "Can I pay by card?", "Do you have a card reader?"], "notes":"Maquininha literally means 'little machine' — the portable card reader. Uber and 99 (Brazil's main ride-hail apps) process payment automatically in-app, so asking isn't needed there." },
  { "d":1, "prompt":"Ask roughly how much the ride costs.", "answers":["Quanto vai custar mais ou menos?", "Mais ou menos quanto é?", "Qual o valor?"], "translations":["How much will it cost, more or less?", "More or less how much is it?", "What is the value?"], "notes":"For Uber and 99 apps, the price is shown upfront before you confirm. For traditional taxis, always ask Quanto vai custar? before getting in to avoid surprises." },
  { "d":1, "prompt":"Ask how long the ride will take.", "answers":["Quanto tempo leva?", "Quantos minutos?", "Quanto demora?"], "translations":["How much time does it take?", "How many minutes?", "How long does it take?"], "notes":"Trânsito (traffic) in Brazilian cities can be intense — always expect longer than estimated. São Paulo in particular is famous for its gridlock during rush hours." },
  { "d":1, "prompt":"You've arrived. Pay and thank the driver.", "answers":["Obrigado/a quanto é?", "Muito obrigado/a", "Valeu bom dia!"], "translations":["Thank you, how much is it?", "Very thank you!", "Thanks, good day!"], "notes":"Brazilians end interactions warmly. Valeu bom dia! (thanks, have a good day!) is a friendly, natural send-off — drivers appreciate the warmth." },
  { "d":2, "prompt":"Say a little further ahead please.", "answers":["Um pouco mais adiante", "Vai um pouco mais", "Mais pra frente"], "translations":["A little more ahead", "Go a little more", "More to the front/forward"], "notes":"Mais pra frente is very casual — pra is a contraction of para, extremely common in spoken Brazilian Portuguese. You'll hear it constantly in everyday speech." },
  { "d":2, "prompt":"Say turn left.", "answers":["Vira à esquerda", "Dobra à esquerda", "Vira aqui à esquerda"], "translations":["Turn to the left", "Turn to the left (fold)", "Turn here to the left"], "notes":"Dobra (from dobrar) and vira (from virar) both mean 'turn' and are interchangeable for directions. Esquerda (left) sounds like 'es-KEHR-da.'" },
  { "d":2, "prompt":"Say turn right.", "answers":["Vira à direita", "Dobra à direita", "Vira aqui à direita"], "translations":["Turn to the right", "Turn to the right (fold)", "Turn here to the right"], "notes":"Brazilians often give directions by landmarks rather than street names — 'after the pharmacy, turn right.' If your driver uses this style, watch for reference points." },
  { "d":2, "prompt":"Say go straight ahead.", "answers":["Vai em frente", "Segue em linha reta", "Direto"], "translations":["Go ahead/forward", "Follow in a straight line", "Straight/Direct"], "notes":"Direto (straight/direct) is the quickest single word for 'go straight.' Vai em frente (go forward) is the most natural complete phrase. Both are instantly understood." },
  { "d":2, "prompt":"Driver says cash only. Acknowledge.", "answers":["Ah tudo bem tenho dinheiro", "Não tem problema pago em dinheiro", "Ok tenho dinheiro"], "translations":["Ah, all fine, I have cash", "No problem, I'll pay in cash", "Ok, I have cash"], "notes":"Dinheiro means both money and cash. Em espécie (in cash/in kind) is more formal. Cash is still widely used with traditional taxis — always carry some." },
  { "d":2, "prompt":"Ask for a receipt.", "answers":["O recibo por favor", "Pode me dar um comprovante?", "Preciso do recibo"], "translations":["The receipt, please", "Can you give me a receipt?", "I need the receipt"], "notes":"Comprovante (proof) and recibo (receipt) are interchangeable. Very useful if you need to claim reimbursement for work travel. Always ask before getting out." },
  { "d":2, "prompt":"Ask the driver to drive more carefully.", "answers":["Pode ir mais devagar?", "Um pouco mais calmo por favor", "Mais devagar obrigado/a"], "translations":["Can you go more slowly?", "A little more calm, please", "More slowly, thank you"], "notes":"Um pouco mais calmo por favor (a little more calm, please) is gentle and effective. Brazilians drive fast — don't hesitate to ask. Drivers are used to the request." },
  { "d":3, "prompt":"Ask the driver to use GPS / fastest route.", "answers":["Usa o GPS por favor", "Vai pela rota mais rápida", "Pode ligar o GPS?"], "translations":["Use the GPS, please", "Go by the fastest route", "Can you turn on the GPS?"], "notes":"GPS is pronounced 'gê-pê-esse' in Brazil. Most drivers use Waze (pronounced 'ways') as their navigation app — it's extremely popular for avoiding Brazilian city traffic." },
  { "d":3, "prompt":"Traffic is bad. Ask if there's another route.", "answers":["Tem outro caminho?", "Podemos desviar do trânsito?", "Tem rota alternativa?"], "translations":["Is there another way?", "Can we deviate from the traffic?", "Is there an alternative route?"], "notes":"Trânsito means traffic or congestion — a very important word in Brazilian cities. Rota alternativa (alternative route) is commonly understood by all drivers." },
  { "d":3, "prompt":"Confirm you're going the right way.", "answers":["Estamos indo para [destination]?", "É por aqui para [destination]?", "Estamos no caminho certo?"], "translations":["Are we going to [destination]?", "Is it this way to [destination]?", "Are we on the right way?"], "notes":"Estamos no caminho certo? (Are we on the right path?) is a reassuring question in unfamiliar areas. Drivers generally respond positively to a passenger who's paying attention." },
  { "d":3, "prompt":"Ask the driver to wait a moment.", "answers":["Pode esperar um momento?", "Um segundo por favor", "Espera aí um instante"], "translations":["Can you wait a moment?", "A second, please", "Wait there, an instant"], "notes":"Espera aí means 'wait there.' Um instante (an instant) and um segundo (a second) are both polite ways to ask for a quick moment — interchangeable in casual speech." },
  { "d":4, "prompt":"Ask the driver for a local restaurant recommendation.", "answers":["Conhece algum restaurante bom por aqui?", "Onde os locais costumam comer?", "Tem sugestão de restaurante?"], "translations":["Do you know any good restaurant around here?", "Where do locals usually eat?", "Do you have a restaurant suggestion?"], "notes":"Taxi drivers are excellent local experts. Onde os locais costumam comer? (Where do locals usually eat?) is the phrase that gets you authentic tips, away from tourist traps." },
  { "d":4, "prompt":"The meter seems high. Politely question it.", "answers":["Com licença o taxímetro parece um pouco alto", "O valor parece alto para essa distância", "Está correto o valor?"], "translations":["With permission, the meter seems a little high", "The value seems high for this distance", "Is the value correct?"], "notes":"Taxímetro is the taxi meter. Traditional taxis have two rates — bandeira 1 (daytime) and bandeira 2 (night/holiday, which is higher). Always check which is running." }
];
