window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["taxi"] = [
  { "d":1, "prompt":"You get in. Say where you're going.", "answers":["Para [destination] por favor", "Vou para [destination]", "Leva-me a [destination]"], "translations":["To [destination] for favor", "I go to [destination]", "Take-me to [destination]"] },
  { "d":1, "prompt":"Say please stop here.", "answers":["Para aqui por favor", "Pode parar aqui", "Aqui está ótimo"], "translations":["Stop here for favor", "Can (you) stop here", "Here is fine"] },
  { "d":1, "prompt":"Ask if they accept card.", "answers":["Aceita cartão?", "Pode pagar no cartão?", "Tem maquininha?"], "translations":["Accepts card?", "Can (I) pay on the card?", "Has little machine? (card reader)"] },
  { "d":1, "prompt":"Ask roughly how much the ride costs.", "answers":["Quanto vai custar mais ou menos?", "Mais ou menos quanto é?", "Qual o valor?"], "translations":["How much will cost more or less?", "More or less how much is it?", "What the value?"] },
  { "d":1, "prompt":"Ask how long the ride will take.", "answers":["Quanto tempo leva?", "Quantos minutos?", "Quanto demora?"], "translations":["How much time takes?", "How many minutes?", "How much (it) takes?"] },
  { "d":1, "prompt":"You've arrived. Pay and thank the driver.", "answers":["Obrigado/a quanto é?", "Muito obrigado/a", "Valeu bom dia!"], "translations":["Obliged how much is it?", "Very obliged", "Worth it good day!"] },
  { "d":2, "prompt":"Say a little further ahead please.", "answers":["Um pouco mais adiante", "Vai um pouco mais", "Mais pra frente"], "translations":["A little more ahead", "Go a little more", "More to forward"] },
  { "d":2, "prompt":"Say turn left.", "answers":["Vira à esquerda", "Dobra à esquerda", "Vira aqui à esquerda"], "translations":["Turn to the left", "Fold/Turn to the left", "Turn here to the left"] },
  { "d":2, "prompt":"Say turn right.", "answers":["Vira à direita", "Dobra à direita", "Vira aqui à direita"], "translations":["Turn to the right", "Fold/Turn to the right", "Turn here to the right"] },
  { "d":2, "prompt":"Say go straight ahead.", "answers":["Vai em frente", "Segue em linha reta", "Direto"], "translations":["Go ahead/forward", "Follow in straight line", "Straight/Direct"] },
  { "d":2, "prompt":"Driver says cash only. Acknowledge.", "answers":["Ah tudo bem tenho dinheiro", "Não tem problema pago em dinheiro", "Ok tenho dinheiro"], "translations":["Ah all well I have money (cash)", "No problem I pay in cash", "Ok I have money (cash)"] },
  { "d":2, "prompt":"Ask for a receipt.", "answers":["O recibo por favor", "Pode me dar um comprovante?", "Preciso do recibo"], "translations":["The receipt for favor", "Can give-me a receipt?", "I need the receipt"] },
  { "d":2, "prompt":"Ask the driver to drive more carefully.", "answers":["Pode ir mais devagar?", "Um pouco mais calmo por favor", "Mais devagar obrigado/a"], "translations":["Can go more slowly?", "A little more calm for favor", "More slowly obliged"] },
  { "d":3, "prompt":"Ask the driver to use GPS / fastest route.", "answers":["Usa o GPS por favor", "Vai pela rota mais rápida", "Pode ligar o GPS?"], "translations":["Use the GPS for favor", "Go by the fastest route", "Can turn on the GPS?"] },
  { "d":3, "prompt":"Traffic is bad. Ask if there's another route.", "answers":["Tem outro caminho?", "Podemos desviar do trânsito?", "Tem rota alternativa?"], "translations":["Has another way?", "We can deviate from the traffic?", "Has alternative route?"] },
  { "d":3, "prompt":"Confirm you're going the right way.", "answers":["Estamos indo para [destination]?", "É por aqui para [destination]?", "Estamos no caminho certo?"], "translations":["We are going to [destination]?", "Is by here to [destination]?", "We are on the right way?"] },
  { "d":3, "prompt":"Ask the driver to wait a moment.", "answers":["Pode esperar um momento?", "Um segundo por favor", "Espera aí um instante"], "translations":["Can (you) wait a moment?", "A second for favor", "Wait there an instant"] },
  { "d":4, "prompt":"Ask the driver for a local restaurant recommendation.", "answers":["Conhece algum restaurante bom por aqui?", "Onde os locais costumam comer?", "Tem sugestão de restaurante?"], "translations":["Knows some good restaurant around here?", "Where the locals usually eat?", "Has restaurant suggestion?"] },
  { "d":4, "prompt":"The meter seems high. Politely question it.", "answers":["Com licença o taxímetro parece um pouco alto", "O valor parece alto para essa distância", "Está correto o valor?"], "translations":["With permission the taximeter seems a little high", "The value seems high for this distance", "Is correct the value?"] }
];
