window.DECKS = window.DECKS || {};
window.DECKS["pt"] = window.DECKS["pt"] || {};
window.DECKS["pt"]["workdinner"] = [
  { "d":1, "prompt":"Say cheers!", "answers":["Saúde!", "Tim-tim!", "Vamos brindar!"], "translations":["Health! (cheers)", "Ting-ting! (clink sound)", "Let's toast!"], "notes":"Saúde! (health!) is the universal Brazilian toast. Tim-tim! mimics the clinking sound of glasses. Vamos brindar! (let's toast!) invites everyone to raise their glasses together." },
  { "d":1, "prompt":"Compliment the food at the dinner.", "answers":["Está uma delícia!", "Que comida boa!", "Está tudo ótimo!"], "translations":["It is a delight!", "What good food!", "It is all great!"], "notes":"Que comida boa! (What good food!) is the natural exclamation. Brazilians are passionate about food — genuine enthusiasm for the meal is always the right social move at a dinner." },
  { "d":1, "prompt":"Respond to please eat a lot.", "answers":["Obrigado/a com certeza!", "Obrigado/a tudo parece delicioso!", "Com prazer obrigado/a!"], "translations":["Thank you, certainly!", "Thank you, everything looks delicious!", "With pleasure, thank you!"], "notes":"Com prazer (with pleasure) is a gracious response to any generous offer. Brazilians are generous hosts — matching their warmth and enthusiasm with equal energy is always appreciated." },
  { "d":1, "prompt":"Receive a drink poured for you. Accept graciously.", "answers":["Obrigado/a!", "Muito gentil obrigado/a!", "Que gentileza obrigado/a!"], "translations":["Thank you!", "Very kind, thank you!", "What kindness, thank you!"], "notes":"Que gentileza obrigado/a! (What kindness, thank you!) acknowledges the gesture beyond a simple thanks. Brazilians notice when appreciation is expressed warmly — it signals social awareness." },
  { "d":1, "prompt":"Say you had a wonderful time.", "answers":["Foi uma noite incrível!", "Me diverti muito!", "Foi ótimo obrigado/a!"], "translations":["It was an incredible night!", "I amused myself a lot!", "It was great, thank you!"], "notes":"Me diverti muito (I amused myself a lot) — divirtir (to amuse/enjoy) is the key verb for having fun in Portuguese. Always the right thing to say when leaving a dinner you enjoyed." },
  { "d":2, "prompt":"Politely decline more alcohol.", "answers":["Já estou bem obrigado/a", "Não precisa mais obrigado/a", "Já chega obrigado/a"], "translations":["I'm already fine, thank you", "No need more, thank you", "Already enough, thank you"], "notes":"Já estou bem (I'm already fine) is the gentle, face-saving way to decline. Não precisa (no need) works for any offer you want to refuse graciously. Always add obrigado/a." },
  { "d":2, "prompt":"Pour a drink for someone senior.", "answers":["Deixa eu servir", "Posso servir?", "Vou servir você"], "translations":["Let me serve", "Can I serve?", "I'll serve you"], "notes":"Serving seniors before yourself is a mark of respect in Brazilian professional culture. Taking initiative to pour is viewed very positively — it shows social awareness and thoughtfulness." },
  { "d":2, "prompt":"Say you'll have just one glass.", "answers":["Só uma taça", "Só um copo obrigado/a", "Tomarei só um"], "translations":["Only one wine glass", "Only one cup/glass, thanks", "I'll take only one"], "notes":"Taça (wine glass) vs copo (general cup/glass) — use taça for wine, copo for beer or water. Tomarei is the formal future tense of tomar (to take/drink) — sounds polished at a dinner." },
  { "d":2, "prompt":"Propose a toast to the team.", "answers":["Pelo time!", "Um brinde a todos nós!", "Pelo trabalho em equipe!"], "translations":["For the team!", "A toast to all of us!", "For the teamwork!"], "notes":"Um brinde (a toast) is the noun — fazer um brinde means to make a toast. Saúde! is always the closing word of any toast. Pelo time! is short, punchy, and very Brazilian." },
  { "d":2, "prompt":"Compliment the venue.", "answers":["Que lugar bonito!", "Que ambiente agradável!", "Adorei o local!"], "translations":["What a beautiful place!", "What an agreeable ambiance!", "I loved the venue!"], "notes":"Ambiente (ambiance/atmosphere) is an important word in Brazilian hospitality culture — Brazilians put great thought into setting, and noticing it explicitly is a meaningful compliment." },
  { "d":3, "prompt":"Offer to pay the bill.", "answers":["Deixa eu pagar", "Essa é por minha conta", "Vou pagar eu"], "translations":["Let me pay", "This one is on my account", "I'll pay"], "notes":"Essa é por minha conta (this one is on my account) is a generous and warm phrase. Treating colleagues or partners to dinner is a common and respected gesture of goodwill in Brazil." },
  { "d":3, "prompt":"Senior insists on paying. Thank and promise next time.", "answers":["Muito obrigado/a! A próxima é por minha conta", "Obrigado/a da próxima eu pago", "Muito gentil! Próxima vez é minha"], "translations":["Very thank you! The next is on my account", "Thank you, the next one I'll pay", "Very kind! Next time is mine"], "notes":"A próxima é por minha conta (the next one is on me) — graciously accepting while promising reciprocity is the perfect social response. It closes the gesture while opening the next one." },
  { "d":3, "prompt":"Ask what someone's research / work focuses on.", "answers":["Em que área você trabalha?", "Qual é o seu campo?", "O que você pesquisa?"], "translations":["In what area do you work?", "What is your field?", "What do you research?"], "notes":"Campo (field) and área (area) are both used for professional domains. O que você pesquisa? (What do you research?) is great for academic or scientific settings — it shows genuine curiosity." },
  { "d":3, "prompt":"Thank the host for organizing the dinner.", "answers":["Obrigado/a por organizar tudo", "Foi muito gentil nos convidar", "Obrigado/a pelo jantar foi ótimo!"], "translations":["Thank you for organizing everything", "It was very kind to invite us", "Thank you for the dinner, it was great!"], "notes":"Por organizar tudo (for organizing everything) acknowledges the effort behind the event — a mark of Brazilian social grace. Hosts genuinely appreciate when effort is seen and named." },
  { "d":4, "prompt":"Make a heartfelt toast speech.", "answers":["Foi uma honra estar com todos vocês esta noite! Saúde!", "Muito obrigado a todos por estarem aqui! Pelo time!", "Esta noite foi especial graças a vocês. Saúde!"], "translations":["It was an honor to be with all of you tonight! Health!", "Very thank you to all for being here! For the team!", "This night was special thanks to all of you. Health!"], "notes":"Foi uma honra (it was an honor) — honra is the go-to word for deep formal gratitude in Brazil. Always end a toast with Saúde! — it's expected and brings the group together." },
  { "d":4, "prompt":"Say whether you enjoy work dinners and socializing with colleagues.", "answers":["Sim adoro! É uma ótima forma de se conhecer melhor", "Gosto bastante cria laços de trabalho", "Adoro é bom conhecer as pessoas fora do trabalho"], "translations":["Yes, I love it! It's a great way to get to know each other better", "I like it quite a bit, it creates work bonds", "I love it, it's good to know people outside of work"], "notes":"Laços de trabalho (work bonds) — laços means ties/bonds, a meaningful word. Brazilians genuinely value personal relationships in professional contexts — warmth and rapport matter deeply." }
];
